# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: jocasta

before:
  hooks:
    - go mod download

builds:
  - id: jocasta
    main: ./cmd/jocasta
    binary: jocasta
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/pushkar-anand/jocasta/internal/version.tag={{ .Version }}
      - -X github.com/pushkar-anand/jocasta/internal/version.commit={{ .FullCommit }}
      - -X github.com/pushkar-anand/jocasta/internal/version.date={{ .CommitDate }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: jocasta
    ids:
      - jocasta
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - docs/*.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^build:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Other work
      order: 999

release:
  prerelease: auto
