// Package hosts has types and utilities for inspecting, resolving,
// and enriching network host metadata such as IP addresses, MAC addresses,
// vendor lookups, and reverse DNS hostnames.
package hosts

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/netip"

	"github.com/pushkar-anand/jocasta/pkg/oui"
)

// Host represents a discovered network host containing both raw input
// attributes and enriched metadata (parsed addresses, vendor info, reverse DNS).
type Host struct {
	// IP is the raw string representation of the device's IP address.
	IP string

	// MAC is the raw string representation of the hardware (MAC) address.
	// Note that this can be a locally administered or randomised identifier.
	MAC string

	// Interface is the identifier or name of the network interface the device is seen on.
	Interface string

	// VLAN is the Virtual LAN identifier associated with the host.
	VLAN int

	// addr holds the parsed, type-safe IP address representation.
	addr netip.Addr

	// mac holds the parsed, type-safe hardware address representation.
	mac net.HardwareAddr

	// hostname is the reverse DNS hostname of the device, if resolved.
	hostname string

	// vendor is the organisation name registered to the MAC address prefix (OUI) in the IEEE database.
	vendor string

	// shortName is a standardised or commonly recognised brand name/abbreviation for the vendor.
	shortName string

	// randomised indicates whether the MAC address is locally administered (randomised),
	// a common privacy measure on modern mobile devices and laptops to mitigate tracking.
	randomised bool
}

// HostInput carries the raw attributes a source reports for one host. It is
// the whole input to BuildHost, so a caller names each field at the call site
// rather than lining up a row of same-typed arguments.
type HostInput struct {
	// IP is the raw string representation of the device's IP address.
	IP string

	// MAC is the raw string representation of the hardware (MAC) address.
	MAC string

	// Hostname, when set, is the name the source already knows the host by,
	// such as a DHCP lease name.
	Hostname string

	// ResolveName asks for a reverse DNS lookup when Hostname is empty.
	//
	// Off by default, because a resolved name belongs to whoever resolved it.
	// A sweep asking the local resolver about an address it just probed is
	// reporting its own finding and sets this; a router's ARP table read from
	// elsewhere is not, and filling its nameless rows from this host's resolver
	// would file a name one source invented under another source's claim.
	ResolveName bool

	// Interface is the identifier or name of the network interface the device is seen on.
	Interface string

	// VLAN is the Virtual LAN identifier associated with the host.
	VLAN int
}

// BuildHost constructs and enriches a Host instance from the supplied network parameters.
// It parses the IP and MAC addresses into structured types, performs reverse DNS resolution
// if no explicit hostname is provided, and enriches MAC metadata via OUI lookup.
func BuildHost(ctx context.Context, in HostInput) (*Host, error) {
	h := &Host{
		IP:        in.IP,
		MAC:       in.MAC,
		Interface: in.Interface,
		VLAN:      in.VLAN,
		hostname:  in.Hostname,
	}

	if in.IP != "" {
		ipAddr, err := netip.ParseAddr(in.IP)
		if err != nil {
			return nil, fmt.Errorf("parse address %q: %w", in.IP, err)
		}

		h.addr = ipAddr
	}

	// Attempt to reverse DNS resolution if no explicit hostname was supplied
	// and the caller is a source that can honestly claim the answer.
	if in.ResolveName && h.hostname == "" && h.addr.IsValid() {
		h.hostname = resolveName(ctx, h.addr)
	}

	if in.MAC != "" {
		hw, err := net.ParseMAC(in.MAC)
		if err != nil {
			return nil, fmt.Errorf("parse MAC %q: %w", in.MAC, err)
		}

		h.mac = hw

		// A locally administered address was generated by the device, so a
		// registry entry it happens to collide with names nobody. Recording it
		// as randomised rather than leaving the vendor blank tells it apart
		// from a lookup miss, which suggests a stale table instead.
		if oui.IsLocallyAdministered(hw) {
			h.randomised = true
		} else if info, found := oui.Lookup(hw); found {
			h.shortName = info.Short
			h.vendor = info.Name
		}
	}

	return h, nil
}

// Address returns the parsed IP address as a netip.Addr.
func (h Host) Address() netip.Addr {
	return h.addr
}

// Vendor returns the organisation registered to the MAC OUI prefix.
func (h Host) Vendor() string {
	return h.vendor
}

// Hostname returns the host's resolved or assigned domain name.
func (h Host) Hostname() string {
	return h.hostname
}

// ShortName returns the shortened or canonical brand name for the hardware vendor.
func (h Host) ShortName() string {
	return h.shortName
}

// HardwareAddress returns the parsed MAC address as a net.HardwareAddr.
func (h Host) HardwareAddress() net.HardwareAddr {
	return h.mac
}

// Randomised reports whether the hardware address has its locally administered bit set.
func (h Host) Randomised() bool {
	return h.randomised
}

// MarshalJSON writes what a Host was enriched into rather than what it was
// built from. The name, vendor and randomised flag live in unexported fields,
// so the default encoding emits a Host with its useful half missing.
func (h Host) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		IP         string `json:"ip"`
		MAC        string `json:"mac,omitempty"`
		Hostname   string `json:"hostname,omitempty"`
		Vendor     string `json:"vendor,omitempty"`
		ShortName  string `json:"vendor_short,omitempty"`
		Randomised bool   `json:"randomised,omitempty"`
		Interface  string `json:"interface,omitempty"`
		VLAN       int    `json:"vlan,omitempty"`
	}{
		IP:         h.IP,
		MAC:        h.MAC,
		Hostname:   h.hostname,
		Vendor:     h.vendor,
		ShortName:  h.shortName,
		Randomised: h.randomised,
		Interface:  h.Interface,
		VLAN:       h.VLAN,
	})
}
