// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package models

import (
	"context"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, scope)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, name, token_hash, scope, created_at, last_used_at
`

type CreateAPITokenParams struct {
	UserID    int64             `json:"user_id"`
	Name      string            `json:"name"`
	TokenHash string            `json:"token_hash"`
	Scope     dbtype.TokenScope `json:"scope"`
}

// CreateAPIToken
//
//	INSERT INTO api_tokens (user_id, name, token_hash, scope)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, user_id, name, token_hash, scope, created_at, last_used_at
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (*ApiToken, error) {
	row := q.queryRow(ctx, q.createAPITokenStmt, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Scope,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE
FROM api_tokens
WHERE id = ?
  AND user_id = ?
`

type DeleteAPITokenParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// DeleteAPIToken
//
//	DELETE
//	FROM api_tokens
//	WHERE id = ?
//	  AND user_id = ?
func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.exec(ctx, q.deleteAPITokenStmt, deleteAPIToken, arg.ID, arg.UserID)
	return err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, user_id, name, token_hash, scope, created_at, last_used_at
FROM api_tokens
WHERE user_id = ?
ORDER BY created_at DESC
`

// ListAPITokensByUser
//
//	SELECT id, user_id, name, token_hash, scope, created_at, last_used_at
//	FROM api_tokens
//	WHERE user_id = ?
//	ORDER BY created_at DESC
func (q *Queries) ListAPITokensByUser(ctx context.Context, userID int64) ([]*ApiToken, error) {
	rows, err := q.query(ctx, q.listAPITokensByUserStmt, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPITokenByHash = `-- name: TouchAPITokenByHash :one
UPDATE api_tokens
SET last_used_at = ?
WHERE token_hash = ?
RETURNING id, user_id, name, token_hash, scope, created_at, last_used_at
`

type TouchAPITokenByHashParams struct {
	LastUsedAt dbtype.NullTime `json:"last_used_at"`
	TokenHash  string          `json:"token_hash"`
}

// Runs on every API request: finding the row and recording its use in one
// statement keeps that cost to a single round trip.
//
//	UPDATE api_tokens
//	SET last_used_at = ?
//	WHERE token_hash = ?
//	RETURNING id, user_id, name, token_hash, scope, created_at, last_used_at
func (q *Queries) TouchAPITokenByHash(ctx context.Context, arg TouchAPITokenByHashParams) (*ApiToken, error) {
	row := q.queryRow(ctx, q.touchAPITokenByHashStmt, touchAPITokenByHash, arg.LastUsedAt, arg.TokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}
