// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package models

import (
	"context"
	"database/sql"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const attemptPorts = `-- name: AttemptPorts :one
SELECT port_count, ports
FROM attempts_hourly
WHERE device_id = ?
  AND hour = ?
  AND source_id = ?
  AND peer_ip = ?
  AND protocol = ?
`

type AttemptPortsParams struct {
	DeviceID int64       `json:"device_id"`
	Hour     dbtype.Time `json:"hour"`
	SourceID int64       `json:"source_id"`
	PeerIP   dbtype.Addr `json:"peer_ip"`
	Protocol int64       `json:"protocol"`
}

type AttemptPortsRow struct {
	PortCount int64  `json:"port_count"`
	Ports     string `json:"ports"`
}

// The ports already on record for one device, peer and hour, so a flush can
// merge its own into them.
//
//	SELECT port_count, ports
//	FROM attempts_hourly
//	WHERE device_id = ?
//	  AND hour = ?
//	  AND source_id = ?
//	  AND peer_ip = ?
//	  AND protocol = ?
func (q *Queries) AttemptPorts(ctx context.Context, arg AttemptPortsParams) (*AttemptPortsRow, error) {
	row := q.queryRow(ctx, q.attemptPortsStmt, attemptPorts,
		arg.DeviceID,
		arg.Hour,
		arg.SourceID,
		arg.PeerIP,
		arg.Protocol,
	)
	var i AttemptPortsRow
	err := row.Scan(&i.PortCount, &i.Ports)
	return &i, err
}

const deleteAttemptsBefore = `-- name: DeleteAttemptsBefore :execrows
DELETE
FROM attempts_hourly
WHERE hour < ?
`

// DeleteAttemptsBefore
//
//	DELETE
//	FROM attempts_hourly
//	WHERE hour < ?
func (q *Queries) DeleteAttemptsBefore(ctx context.Context, hour dbtype.Time) (int64, error) {
	result, err := q.exec(ctx, q.deleteAttemptsBeforeStmt, deleteAttemptsBefore, hour)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deviceAttempts = `-- name: DeviceAttempts :many
SELECT CAST(COALESCE(a.peer_device_id, 0) AS INTEGER) AS peer_device_id,
       CAST(a.peer_ip AS TEXT)                        AS peer_ip,
       CAST(COALESCE(MAX(a.peer_asn), 0) AS INTEGER)  AS peer_asn,
       CAST(COALESCE(MAX(pd.label), '') AS TEXT)      AS peer_label,
       CAST(COALESCE(MAX(pd.hostname), '') AS TEXT)   AS peer_hostname,
       CAST(COALESCE(MAX(pd.mac), '') AS TEXT)        AS peer_mac,
       a.protocol,
       CAST(SUM(a.attempts) AS INTEGER)               AS attempts,
       CAST(SUM(a.answered) AS INTEGER)               AS answered,
       CAST(MAX(a.port_count) AS INTEGER)             AS port_count,
       CAST(GROUP_CONCAT(a.ports, ',') AS TEXT)       AS ports,
       CAST(MAX(a.hour) AS TEXT)                      AS last_hour
FROM attempts_hourly a
         LEFT JOIN devices pd ON pd.id = a.peer_device_id
WHERE a.device_id = ?
  AND a.hour >= ?
GROUP BY COALESCE(a.peer_device_id, 0), a.peer_ip, a.protocol
ORDER BY SUM(a.attempts) DESC, a.peer_ip
LIMIT ?
`

type DeviceAttemptsParams struct {
	DeviceID int64       `json:"device_id"`
	Hour     dbtype.Time `json:"hour"`
	Limit    int64       `json:"limit"`
}

type DeviceAttemptsRow struct {
	PeerDeviceID int64  `json:"peer_device_id"`
	PeerIP       string `json:"peer_ip"`
	PeerASN      int64  `json:"peer_asn"`
	PeerLabel    string `json:"peer_label"`
	PeerHostname string `json:"peer_hostname"`
	PeerMAC      string `json:"peer_mac"`
	Protocol     int64  `json:"protocol"`
	Attempts     int64  `json:"attempts"`
	Answered     int64  `json:"answered"`
	PortCount    int64  `json:"port_count"`
	Ports        string `json:"ports"`
	LastHour     string `json:"last_hour"`
}

// What one device tried to reach since a given hour, one row per peer and
// protocol, most attempts first. ports is every hour's sample joined; the
// caller merges them.
//
//	SELECT CAST(COALESCE(a.peer_device_id, 0) AS INTEGER) AS peer_device_id,
//	       CAST(a.peer_ip AS TEXT)                        AS peer_ip,
//	       CAST(COALESCE(MAX(a.peer_asn), 0) AS INTEGER)  AS peer_asn,
//	       CAST(COALESCE(MAX(pd.label), '') AS TEXT)      AS peer_label,
//	       CAST(COALESCE(MAX(pd.hostname), '') AS TEXT)   AS peer_hostname,
//	       CAST(COALESCE(MAX(pd.mac), '') AS TEXT)        AS peer_mac,
//	       a.protocol,
//	       CAST(SUM(a.attempts) AS INTEGER)               AS attempts,
//	       CAST(SUM(a.answered) AS INTEGER)               AS answered,
//	       CAST(MAX(a.port_count) AS INTEGER)             AS port_count,
//	       CAST(GROUP_CONCAT(a.ports, ',') AS TEXT)       AS ports,
//	       CAST(MAX(a.hour) AS TEXT)                      AS last_hour
//	FROM attempts_hourly a
//	         LEFT JOIN devices pd ON pd.id = a.peer_device_id
//	WHERE a.device_id = ?
//	  AND a.hour >= ?
//	GROUP BY COALESCE(a.peer_device_id, 0), a.peer_ip, a.protocol
//	ORDER BY SUM(a.attempts) DESC, a.peer_ip
//	LIMIT ?
func (q *Queries) DeviceAttempts(ctx context.Context, arg DeviceAttemptsParams) ([]*DeviceAttemptsRow, error) {
	rows, err := q.query(ctx, q.deviceAttemptsStmt, deviceAttempts, arg.DeviceID, arg.Hour, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DeviceAttemptsRow
	for rows.Next() {
		var i DeviceAttemptsRow
		if err := rows.Scan(
			&i.PeerDeviceID,
			&i.PeerIP,
			&i.PeerASN,
			&i.PeerLabel,
			&i.PeerHostname,
			&i.PeerMAC,
			&i.Protocol,
			&i.Attempts,
			&i.Answered,
			&i.PortCount,
			&i.Ports,
			&i.LastHour,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const probingHours = `-- name: ProbingHours :many
SELECT a.device_id,
       CAST(COALESCE(d.label, '') AS TEXT)    AS label,
       CAST(COALESCE(d.hostname, '') AS TEXT) AS hostname,
       CAST(COALESCE(d.mac, '') AS TEXT)      AS mac,
       CAST(a.hour AS TEXT)                   AS hour,
       CAST(COUNT(DISTINCT a.peer_ip) AS INTEGER) AS peers,
       CAST(MAX(a.port_count) AS INTEGER)     AS max_ports,
       CAST(SUM(a.attempts) AS INTEGER)       AS attempts,
       CAST(SUM(a.answered) AS INTEGER)       AS answered,
       CAST(GROUP_CONCAT(a.ports, ',') AS TEXT) AS ports
FROM attempts_hourly a
         JOIN devices d ON d.id = a.device_id
WHERE a.hour >= ?1
  AND a.peer_asn IS NULL
  AND d.is_ignored = 0
  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
GROUP BY a.device_id, a.hour
HAVING COUNT(DISTINCT a.peer_ip) >= CAST(?3 AS INTEGER)
    OR MAX(a.port_count) >= CAST(?4 AS INTEGER)
ORDER BY a.hour DESC, a.device_id
`

type ProbingHoursParams struct {
	Since     dbtype.Time    `json:"since"`
	GroupName sql.NullString `json:"group_name"`
	MinPeers  int64          `json:"min_peers"`
	MinPorts  int64          `json:"min_ports"`
}

type ProbingHoursRow struct {
	DeviceID int64  `json:"device_id"`
	Label    string `json:"label"`
	Hostname string `json:"hostname"`
	MAC      string `json:"mac"`
	Hour     string `json:"hour"`
	Peers    int64  `json:"peers"`
	MaxPorts int64  `json:"max_ports"`
	Attempts int64  `json:"attempts"`
	Answered int64  `json:"answered"`
	Ports    string `json:"ports"`
}

// Each hour a device tried many local addresses, or many ports on one of
// them: what a scan of the home network looks like. Internet peers are left
// out -- a device failing to reach a busy service's many addresses is not
// scanning anything.
//
//	SELECT a.device_id,
//	       CAST(COALESCE(d.label, '') AS TEXT)    AS label,
//	       CAST(COALESCE(d.hostname, '') AS TEXT) AS hostname,
//	       CAST(COALESCE(d.mac, '') AS TEXT)      AS mac,
//	       CAST(a.hour AS TEXT)                   AS hour,
//	       CAST(COUNT(DISTINCT a.peer_ip) AS INTEGER) AS peers,
//	       CAST(MAX(a.port_count) AS INTEGER)     AS max_ports,
//	       CAST(SUM(a.attempts) AS INTEGER)       AS attempts,
//	       CAST(SUM(a.answered) AS INTEGER)       AS answered,
//	       CAST(GROUP_CONCAT(a.ports, ',') AS TEXT) AS ports
//	FROM attempts_hourly a
//	         JOIN devices d ON d.id = a.device_id
//	WHERE a.hour >= ?1
//	  AND a.peer_asn IS NULL
//	  AND d.is_ignored = 0
//	  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
//	GROUP BY a.device_id, a.hour
//	HAVING COUNT(DISTINCT a.peer_ip) >= CAST(?3 AS INTEGER)
//	    OR MAX(a.port_count) >= CAST(?4 AS INTEGER)
//	ORDER BY a.hour DESC, a.device_id
func (q *Queries) ProbingHours(ctx context.Context, arg ProbingHoursParams) ([]*ProbingHoursRow, error) {
	rows, err := q.query(ctx, q.probingHoursStmt, probingHours,
		arg.Since,
		arg.GroupName,
		arg.MinPeers,
		arg.MinPorts,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProbingHoursRow
	for rows.Next() {
		var i ProbingHoursRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Label,
			&i.Hostname,
			&i.MAC,
			&i.Hour,
			&i.Peers,
			&i.MaxPorts,
			&i.Attempts,
			&i.Answered,
			&i.Ports,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttempts = `-- name: UpsertAttempts :exec
INSERT INTO attempts_hourly (source_id, device_id, hour, peer_device_id, peer_ip, peer_asn,
                             protocol, attempts, answered, port_count, ports)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (device_id, hour, source_id, peer_ip, protocol) DO UPDATE
    SET peer_device_id = COALESCE(excluded.peer_device_id, peer_device_id),
        peer_asn       = COALESCE(excluded.peer_asn, peer_asn),
        attempts       = attempts + excluded.attempts,
        answered       = answered + excluded.answered,
        port_count     = MAX(port_count, excluded.port_count),
        ports          = excluded.ports
`

type UpsertAttemptsParams struct {
	SourceID     int64         `json:"source_id"`
	DeviceID     int64         `json:"device_id"`
	Hour         dbtype.Time   `json:"hour"`
	PeerDeviceID sql.NullInt64 `json:"peer_device_id"`
	PeerIP       dbtype.Addr   `json:"peer_ip"`
	PeerASN      sql.NullInt64 `json:"peer_asn"`
	Protocol     int64         `json:"protocol"`
	Attempts     int64         `json:"attempts"`
	Answered     int64         `json:"answered"`
	PortCount    int64         `json:"port_count"`
	Ports        string        `json:"ports"`
}

// One flush adds to the hour's attempt counts. The caller has already merged
// the port sample with the one on record, so it replaces it; port_count only
// ever grows, since a restarted process counts again from nothing.
//
//	INSERT INTO attempts_hourly (source_id, device_id, hour, peer_device_id, peer_ip, peer_asn,
//	                             protocol, attempts, answered, port_count, ports)
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
//	ON CONFLICT (device_id, hour, source_id, peer_ip, protocol) DO UPDATE
//	    SET peer_device_id = COALESCE(excluded.peer_device_id, peer_device_id),
//	        peer_asn       = COALESCE(excluded.peer_asn, peer_asn),
//	        attempts       = attempts + excluded.attempts,
//	        answered       = answered + excluded.answered,
//	        port_count     = MAX(port_count, excluded.port_count),
//	        ports          = excluded.ports
func (q *Queries) UpsertAttempts(ctx context.Context, arg UpsertAttemptsParams) error {
	_, err := q.exec(ctx, q.upsertAttemptsStmt, upsertAttempts,
		arg.SourceID,
		arg.DeviceID,
		arg.Hour,
		arg.PeerDeviceID,
		arg.PeerIP,
		arg.PeerASN,
		arg.Protocol,
		arg.Attempts,
		arg.Answered,
		arg.PortCount,
		arg.Ports,
	)
	return err
}
