// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcasts.sql

package models

import (
	"context"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const deleteBroadcastsBefore = `-- name: DeleteBroadcastsBefore :execrows
DELETE
FROM broadcasts_hourly
WHERE hour < ?
`

// DeleteBroadcastsBefore
//
//	DELETE
//	FROM broadcasts_hourly
//	WHERE hour < ?
func (q *Queries) DeleteBroadcastsBefore(ctx context.Context, hour dbtype.Time) (int64, error) {
	result, err := q.exec(ctx, q.deleteBroadcastsBeforeStmt, deleteBroadcastsBefore, hour)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deviceBroadcasts = `-- name: DeviceBroadcasts :many
SELECT CAST(dst_ip AS TEXT)          AS dst_ip,
       CAST(MAX(kind) AS TEXT)       AS kind,
       protocol,
       port,
       CAST(SUM(bytes) AS INTEGER)   AS bytes,
       CAST(SUM(packets) AS INTEGER) AS packets,
       CAST(MAX(hour) AS TEXT)       AS last_hour
FROM broadcasts_hourly
WHERE device_id = ?
  AND hour >= ?
GROUP BY dst_ip, protocol, port
ORDER BY SUM(packets) DESC, dst_ip, protocol, port
`

type DeviceBroadcastsParams struct {
	DeviceID int64       `json:"device_id"`
	Hour     dbtype.Time `json:"hour"`
}

type DeviceBroadcastsRow struct {
	DstIP    string `json:"dst_ip"`
	Kind     string `json:"kind"`
	Protocol int64  `json:"protocol"`
	Port     int64  `json:"port"`
	Bytes    int64  `json:"bytes"`
	Packets  int64  `json:"packets"`
	LastHour string `json:"last_hour"`
}

// What one device sent to everyone since a given hour, one row per group,
// protocol and port, most packets first.
//
//	SELECT CAST(dst_ip AS TEXT)          AS dst_ip,
//	       CAST(MAX(kind) AS TEXT)       AS kind,
//	       protocol,
//	       port,
//	       CAST(SUM(bytes) AS INTEGER)   AS bytes,
//	       CAST(SUM(packets) AS INTEGER) AS packets,
//	       CAST(MAX(hour) AS TEXT)       AS last_hour
//	FROM broadcasts_hourly
//	WHERE device_id = ?
//	  AND hour >= ?
//	GROUP BY dst_ip, protocol, port
//	ORDER BY SUM(packets) DESC, dst_ip, protocol, port
func (q *Queries) DeviceBroadcasts(ctx context.Context, arg DeviceBroadcastsParams) ([]*DeviceBroadcastsRow, error) {
	rows, err := q.query(ctx, q.deviceBroadcastsStmt, deviceBroadcasts, arg.DeviceID, arg.Hour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DeviceBroadcastsRow
	for rows.Next() {
		var i DeviceBroadcastsRow
		if err := rows.Scan(
			&i.DstIP,
			&i.Kind,
			&i.Protocol,
			&i.Port,
			&i.Bytes,
			&i.Packets,
			&i.LastHour,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBroadcast = `-- name: UpsertBroadcast :exec
INSERT INTO broadcasts_hourly (source_id, device_id, hour, dst_ip, kind, protocol, port, bytes, packets)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (device_id, hour, source_id, dst_ip, protocol, port) DO UPDATE
    SET bytes   = bytes + excluded.bytes,
        packets = packets + excluded.packets
`

type UpsertBroadcastParams struct {
	SourceID int64       `json:"source_id"`
	DeviceID int64       `json:"device_id"`
	Hour     dbtype.Time `json:"hour"`
	DstIP    dbtype.Addr `json:"dst_ip"`
	Kind     string      `json:"kind"`
	Protocol int64       `json:"protocol"`
	Port     int64       `json:"port"`
	Bytes    int64       `json:"bytes"`
	Packets  int64       `json:"packets"`
}

// One flush adds to the hour's totals for a device, group and port.
//
//	INSERT INTO broadcasts_hourly (source_id, device_id, hour, dst_ip, kind, protocol, port, bytes, packets)
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
//	ON CONFLICT (device_id, hour, source_id, dst_ip, protocol, port) DO UPDATE
//	    SET bytes   = bytes + excluded.bytes,
//	        packets = packets + excluded.packets
func (q *Queries) UpsertBroadcast(ctx context.Context, arg UpsertBroadcastParams) error {
	_, err := q.exec(ctx, q.upsertBroadcastStmt, upsertBroadcast,
		arg.SourceID,
		arg.DeviceID,
		arg.Hour,
		arg.DstIP,
		arg.Kind,
		arg.Protocol,
		arg.Port,
		arg.Bytes,
		arg.Packets,
	)
	return err
}
