// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adoptCurationStmt, err = db.PrepareContext(ctx, adoptCuration); err != nil {
		return nil, fmt.Errorf("error preparing query AdoptCuration: %w", err)
	}
	if q.allCurrentAddressesStmt, err = db.PrepareContext(ctx, allCurrentAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query AllCurrentAddresses: %w", err)
	}
	if q.allNetworksStmt, err = db.PrepareContext(ctx, allNetworks); err != nil {
		return nil, fmt.Errorf("error preparing query AllNetworks: %w", err)
	}
	if q.answerAttemptsStmt, err = db.PrepareContext(ctx, answerAttempts); err != nil {
		return nil, fmt.Errorf("error preparing query AnswerAttempts: %w", err)
	}
	if q.answerProbesStmt, err = db.PrepareContext(ctx, answerProbes); err != nil {
		return nil, fmt.Errorf("error preparing query AnswerProbes: %w", err)
	}
	if q.anyTrafficStmt, err = db.PrepareContext(ctx, anyTraffic); err != nil {
		return nil, fmt.Errorf("error preparing query AnyTraffic: %w", err)
	}
	if q.attemptPortsStmt, err = db.PrepareContext(ctx, attemptPorts); err != nil {
		return nil, fmt.Errorf("error preparing query AttemptPorts: %w", err)
	}
	if q.busiestDevicesStmt, err = db.PrepareContext(ctx, busiestDevices); err != nil {
		return nil, fmt.Errorf("error preparing query BusiestDevices: %w", err)
	}
	if q.closePortStmt, err = db.PrepareContext(ctx, closePort); err != nil {
		return nil, fmt.Errorf("error preparing query ClosePort: %w", err)
	}
	if q.commonOpenServicesStmt, err = db.PrepareContext(ctx, commonOpenServices); err != nil {
		return nil, fmt.Errorf("error preparing query CommonOpenServices: %w", err)
	}
	if q.countUnusedRecoveryCodesByUserStmt, err = db.PrepareContext(ctx, countUnusedRecoveryCodesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query CountUnusedRecoveryCodesByUser: %w", err)
	}
	if q.countUsersStmt, err = db.PrepareContext(ctx, countUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsers: %w", err)
	}
	if q.createAPITokenStmt, err = db.PrepareContext(ctx, createAPIToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAPIToken: %w", err)
	}
	if q.createDeviceStmt, err = db.PrepareContext(ctx, createDevice); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDevice: %w", err)
	}
	if q.createEventStmt, err = db.PrepareContext(ctx, createEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEvent: %w", err)
	}
	if q.createRecoveryCodeStmt, err = db.PrepareContext(ctx, createRecoveryCode); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRecoveryCode: %w", err)
	}
	if q.createScanStmt, err = db.PrepareContext(ctx, createScan); err != nil {
		return nil, fmt.Errorf("error preparing query CreateScan: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.currentAddressesStmt, err = db.PrepareContext(ctx, currentAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query CurrentAddresses: %w", err)
	}
	if q.currentHoldersStmt, err = db.PrepareContext(ctx, currentHolders); err != nil {
		return nil, fmt.Errorf("error preparing query CurrentHolders: %w", err)
	}
	if q.deleteAPITokenStmt, err = db.PrepareContext(ctx, deleteAPIToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAPIToken: %w", err)
	}
	if q.deleteAttemptsBeforeStmt, err = db.PrepareContext(ctx, deleteAttemptsBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAttemptsBefore: %w", err)
	}
	if q.deleteBroadcastsBeforeStmt, err = db.PrepareContext(ctx, deleteBroadcastsBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBroadcastsBefore: %w", err)
	}
	if q.deleteDeviceStmt, err = db.PrepareContext(ctx, deleteDevice); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDevice: %w", err)
	}
	if q.deleteEventsBeforeStmt, err = db.PrepareContext(ctx, deleteEventsBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEventsBefore: %w", err)
	}
	if q.deleteProbesBeforeStmt, err = db.PrepareContext(ctx, deleteProbesBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProbesBefore: %w", err)
	}
	if q.deleteRecoveryCodesByUserStmt, err = db.PrepareContext(ctx, deleteRecoveryCodesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRecoveryCodesByUser: %w", err)
	}
	if q.deleteScansBeforeStmt, err = db.PrepareContext(ctx, deleteScansBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteScansBefore: %w", err)
	}
	if q.deleteTrafficBeforeStmt, err = db.PrepareContext(ctx, deleteTrafficBefore); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTrafficBefore: %w", err)
	}
	if q.deviceAttemptsStmt, err = db.PrepareContext(ctx, deviceAttempts); err != nil {
		return nil, fmt.Errorf("error preparing query DeviceAttempts: %w", err)
	}
	if q.deviceBroadcastsStmt, err = db.PrepareContext(ctx, deviceBroadcasts); err != nil {
		return nil, fmt.Errorf("error preparing query DeviceBroadcasts: %w", err)
	}
	if q.deviceNetworkNamesStmt, err = db.PrepareContext(ctx, deviceNetworkNames); err != nil {
		return nil, fmt.Errorf("error preparing query DeviceNetworkNames: %w", err)
	}
	if q.deviceStatsStmt, err = db.PrepareContext(ctx, deviceStats); err != nil {
		return nil, fmt.Errorf("error preparing query DeviceStats: %w", err)
	}
	if q.deviceTrafficStmt, err = db.PrepareContext(ctx, deviceTraffic); err != nil {
		return nil, fmt.Errorf("error preparing query DeviceTraffic: %w", err)
	}
	if q.disableUserTOTPStmt, err = db.PrepareContext(ctx, disableUserTOTP); err != nil {
		return nil, fmt.Errorf("error preparing query DisableUserTOTP: %w", err)
	}
	if q.earliestTrafficStmt, err = db.PrepareContext(ctx, earliestTraffic); err != nil {
		return nil, fmt.Errorf("error preparing query EarliestTraffic: %w", err)
	}
	if q.enableUserTOTPStmt, err = db.PrepareContext(ctx, enableUserTOTP); err != nil {
		return nil, fmt.Errorf("error preparing query EnableUserTOTP: %w", err)
	}
	if q.finishScanStmt, err = db.PrepareContext(ctx, finishScan); err != nil {
		return nil, fmt.Errorf("error preparing query FinishScan: %w", err)
	}
	if q.firstContactsStmt, err = db.PrepareContext(ctx, firstContacts); err != nil {
		return nil, fmt.Errorf("error preparing query FirstContacts: %w", err)
	}
	if q.getAddressStmt, err = db.PrepareContext(ctx, getAddress); err != nil {
		return nil, fmt.Errorf("error preparing query GetAddress: %w", err)
	}
	if q.getDeviceStmt, err = db.PrepareContext(ctx, getDevice); err != nil {
		return nil, fmt.Errorf("error preparing query GetDevice: %w", err)
	}
	if q.getDeviceByCurrentIPStmt, err = db.PrepareContext(ctx, getDeviceByCurrentIP); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeviceByCurrentIP: %w", err)
	}
	if q.getDeviceByMACStmt, err = db.PrepareContext(ctx, getDeviceByMAC); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeviceByMAC: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.identifyDeviceStmt, err = db.PrepareContext(ctx, identifyDevice); err != nil {
		return nil, fmt.Errorf("error preparing query IdentifyDevice: %w", err)
	}
	if q.incomingFromInternetStmt, err = db.PrepareContext(ctx, incomingFromInternet); err != nil {
		return nil, fmt.Errorf("error preparing query IncomingFromInternet: %w", err)
	}
	if q.insertAddressStmt, err = db.PrepareContext(ctx, insertAddress); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAddress: %w", err)
	}
	if q.latestSuccessfulScanFinishedAtStmt, err = db.PrepareContext(ctx, latestSuccessfulScanFinishedAt); err != nil {
		return nil, fmt.Errorf("error preparing query LatestSuccessfulScanFinishedAt: %w", err)
	}
	if q.listAPITokensByUserStmt, err = db.PrepareContext(ctx, listAPITokensByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListAPITokensByUser: %w", err)
	}
	if q.listDeviceAddressesStmt, err = db.PrepareContext(ctx, listDeviceAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeviceAddresses: %w", err)
	}
	if q.listDeviceEventsStmt, err = db.PrepareContext(ctx, listDeviceEvents); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeviceEvents: %w", err)
	}
	if q.listDeviceOpenPortsStmt, err = db.PrepareContext(ctx, listDeviceOpenPorts); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeviceOpenPorts: %w", err)
	}
	if q.listDevicePortsStmt, err = db.PrepareContext(ctx, listDevicePorts); err != nil {
		return nil, fmt.Errorf("error preparing query ListDevicePorts: %w", err)
	}
	if q.listDeviceSourcesStmt, err = db.PrepareContext(ctx, listDeviceSources); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeviceSources: %w", err)
	}
	if q.listDevicesStmt, err = db.PrepareContext(ctx, listDevices); err != nil {
		return nil, fmt.Errorf("error preparing query ListDevices: %w", err)
	}
	if q.listGroupsStmt, err = db.PrepareContext(ctx, listGroups); err != nil {
		return nil, fmt.Errorf("error preparing query ListGroups: %w", err)
	}
	if q.listNetworksStmt, err = db.PrepareContext(ctx, listNetworks); err != nil {
		return nil, fmt.Errorf("error preparing query ListNetworks: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.moveAddressesStmt, err = db.PrepareContext(ctx, moveAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query MoveAddresses: %w", err)
	}
	if q.moveDeviceSourcesStmt, err = db.PrepareContext(ctx, moveDeviceSources); err != nil {
		return nil, fmt.Errorf("error preparing query MoveDeviceSources: %w", err)
	}
	if q.moveEventsStmt, err = db.PrepareContext(ctx, moveEvents); err != nil {
		return nil, fmt.Errorf("error preparing query MoveEvents: %w", err)
	}
	if q.organisationDevicesStmt, err = db.PrepareContext(ctx, organisationDevices); err != nil {
		return nil, fmt.Errorf("error preparing query OrganisationDevices: %w", err)
	}
	if q.outsideAddressesStmt, err = db.PrepareContext(ctx, outsideAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query OutsideAddresses: %w", err)
	}
	if q.portStatsStmt, err = db.PrepareContext(ctx, portStats); err != nil {
		return nil, fmt.Errorf("error preparing query PortStats: %w", err)
	}
	if q.probePortsStmt, err = db.PrepareContext(ctx, probePorts); err != nil {
		return nil, fmt.Errorf("error preparing query ProbePorts: %w", err)
	}
	if q.probedDevicesStmt, err = db.PrepareContext(ctx, probedDevices); err != nil {
		return nil, fmt.Errorf("error preparing query ProbedDevices: %w", err)
	}
	if q.probingHoursStmt, err = db.PrepareContext(ctx, probingHours); err != nil {
		return nil, fmt.Errorf("error preparing query ProbingHours: %w", err)
	}
	if q.redeemRecoveryCodeStmt, err = db.PrepareContext(ctx, redeemRecoveryCode); err != nil {
		return nil, fmt.Errorf("error preparing query RedeemRecoveryCode: %w", err)
	}
	if q.refreshAddressStmt, err = db.PrepareContext(ctx, refreshAddress); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshAddress: %w", err)
	}
	if q.releaseAddressStmt, err = db.PrepareContext(ctx, releaseAddress); err != nil {
		return nil, fmt.Errorf("error preparing query ReleaseAddress: %w", err)
	}
	if q.retireAddressStmt, err = db.PrepareContext(ctx, retireAddress); err != nil {
		return nil, fmt.Errorf("error preparing query RetireAddress: %w", err)
	}
	if q.scanEventsStmt, err = db.PrepareContext(ctx, scanEvents); err != nil {
		return nil, fmt.Errorf("error preparing query ScanEvents: %w", err)
	}
	if q.scanSummaryStmt, err = db.PrepareContext(ctx, scanSummary); err != nil {
		return nil, fmt.Errorf("error preparing query ScanSummary: %w", err)
	}
	if q.setDeviceClassStmt, err = db.PrepareContext(ctx, setDeviceClass); err != nil {
		return nil, fmt.Errorf("error preparing query SetDeviceClass: %w", err)
	}
	if q.setDeviceHostnameStmt, err = db.PrepareContext(ctx, setDeviceHostname); err != nil {
		return nil, fmt.Errorf("error preparing query SetDeviceHostname: %w", err)
	}
	if q.setUserTOTPSecretStmt, err = db.PrepareContext(ctx, setUserTOTPSecret); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserTOTPSecret: %w", err)
	}
	if q.topOrganisationsStmt, err = db.PrepareContext(ctx, topOrganisations); err != nil {
		return nil, fmt.Errorf("error preparing query TopOrganisations: %w", err)
	}
	if q.touchAPITokenByHashStmt, err = db.PrepareContext(ctx, touchAPITokenByHash); err != nil {
		return nil, fmt.Errorf("error preparing query TouchAPITokenByHash: %w", err)
	}
	if q.touchDeviceStmt, err = db.PrepareContext(ctx, touchDevice); err != nil {
		return nil, fmt.Errorf("error preparing query TouchDevice: %w", err)
	}
	if q.trafficMapDevicesStmt, err = db.PrepareContext(ctx, trafficMapDevices); err != nil {
		return nil, fmt.Errorf("error preparing query TrafficMapDevices: %w", err)
	}
	if q.trafficMapLinksStmt, err = db.PrepareContext(ctx, trafficMapLinks); err != nil {
		return nil, fmt.Errorf("error preparing query TrafficMapLinks: %w", err)
	}
	if q.trafficWorldPeersStmt, err = db.PrepareContext(ctx, trafficWorldPeers); err != nil {
		return nil, fmt.Errorf("error preparing query TrafficWorldPeers: %w", err)
	}
	if q.updateDeviceCurationStmt, err = db.PrepareContext(ctx, updateDeviceCuration); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDeviceCuration: %w", err)
	}
	if q.upsertAttemptsStmt, err = db.PrepareContext(ctx, upsertAttempts); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAttempts: %w", err)
	}
	if q.upsertBroadcastStmt, err = db.PrepareContext(ctx, upsertBroadcast); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertBroadcast: %w", err)
	}
	if q.upsertDeviceSourceStmt, err = db.PrepareContext(ctx, upsertDeviceSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertDeviceSource: %w", err)
	}
	if q.upsertNetworkStmt, err = db.PrepareContext(ctx, upsertNetwork); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertNetwork: %w", err)
	}
	if q.upsertNetworkIdentityStmt, err = db.PrepareContext(ctx, upsertNetworkIdentity); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertNetworkIdentity: %w", err)
	}
	if q.upsertOpenPortStmt, err = db.PrepareContext(ctx, upsertOpenPort); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertOpenPort: %w", err)
	}
	if q.upsertOutsideAddressStmt, err = db.PrepareContext(ctx, upsertOutsideAddress); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertOutsideAddress: %w", err)
	}
	if q.upsertProbesStmt, err = db.PrepareContext(ctx, upsertProbes); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertProbes: %w", err)
	}
	if q.upsertSourceStmt, err = db.PrepareContext(ctx, upsertSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSource: %w", err)
	}
	if q.upsertTrafficStmt, err = db.PrepareContext(ctx, upsertTraffic); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertTraffic: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adoptCurationStmt != nil {
		if cerr := q.adoptCurationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adoptCurationStmt: %w", cerr)
		}
	}
	if q.allCurrentAddressesStmt != nil {
		if cerr := q.allCurrentAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing allCurrentAddressesStmt: %w", cerr)
		}
	}
	if q.allNetworksStmt != nil {
		if cerr := q.allNetworksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing allNetworksStmt: %w", cerr)
		}
	}
	if q.answerAttemptsStmt != nil {
		if cerr := q.answerAttemptsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing answerAttemptsStmt: %w", cerr)
		}
	}
	if q.answerProbesStmt != nil {
		if cerr := q.answerProbesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing answerProbesStmt: %w", cerr)
		}
	}
	if q.anyTrafficStmt != nil {
		if cerr := q.anyTrafficStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing anyTrafficStmt: %w", cerr)
		}
	}
	if q.attemptPortsStmt != nil {
		if cerr := q.attemptPortsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing attemptPortsStmt: %w", cerr)
		}
	}
	if q.busiestDevicesStmt != nil {
		if cerr := q.busiestDevicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing busiestDevicesStmt: %w", cerr)
		}
	}
	if q.closePortStmt != nil {
		if cerr := q.closePortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing closePortStmt: %w", cerr)
		}
	}
	if q.commonOpenServicesStmt != nil {
		if cerr := q.commonOpenServicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing commonOpenServicesStmt: %w", cerr)
		}
	}
	if q.countUnusedRecoveryCodesByUserStmt != nil {
		if cerr := q.countUnusedRecoveryCodesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUnusedRecoveryCodesByUserStmt: %w", cerr)
		}
	}
	if q.countUsersStmt != nil {
		if cerr := q.countUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersStmt: %w", cerr)
		}
	}
	if q.createAPITokenStmt != nil {
		if cerr := q.createAPITokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAPITokenStmt: %w", cerr)
		}
	}
	if q.createDeviceStmt != nil {
		if cerr := q.createDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeviceStmt: %w", cerr)
		}
	}
	if q.createEventStmt != nil {
		if cerr := q.createEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEventStmt: %w", cerr)
		}
	}
	if q.createRecoveryCodeStmt != nil {
		if cerr := q.createRecoveryCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRecoveryCodeStmt: %w", cerr)
		}
	}
	if q.createScanStmt != nil {
		if cerr := q.createScanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createScanStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.currentAddressesStmt != nil {
		if cerr := q.currentAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing currentAddressesStmt: %w", cerr)
		}
	}
	if q.currentHoldersStmt != nil {
		if cerr := q.currentHoldersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing currentHoldersStmt: %w", cerr)
		}
	}
	if q.deleteAPITokenStmt != nil {
		if cerr := q.deleteAPITokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAPITokenStmt: %w", cerr)
		}
	}
	if q.deleteAttemptsBeforeStmt != nil {
		if cerr := q.deleteAttemptsBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAttemptsBeforeStmt: %w", cerr)
		}
	}
	if q.deleteBroadcastsBeforeStmt != nil {
		if cerr := q.deleteBroadcastsBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBroadcastsBeforeStmt: %w", cerr)
		}
	}
	if q.deleteDeviceStmt != nil {
		if cerr := q.deleteDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDeviceStmt: %w", cerr)
		}
	}
	if q.deleteEventsBeforeStmt != nil {
		if cerr := q.deleteEventsBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEventsBeforeStmt: %w", cerr)
		}
	}
	if q.deleteProbesBeforeStmt != nil {
		if cerr := q.deleteProbesBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProbesBeforeStmt: %w", cerr)
		}
	}
	if q.deleteRecoveryCodesByUserStmt != nil {
		if cerr := q.deleteRecoveryCodesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRecoveryCodesByUserStmt: %w", cerr)
		}
	}
	if q.deleteScansBeforeStmt != nil {
		if cerr := q.deleteScansBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteScansBeforeStmt: %w", cerr)
		}
	}
	if q.deleteTrafficBeforeStmt != nil {
		if cerr := q.deleteTrafficBeforeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTrafficBeforeStmt: %w", cerr)
		}
	}
	if q.deviceAttemptsStmt != nil {
		if cerr := q.deviceAttemptsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deviceAttemptsStmt: %w", cerr)
		}
	}
	if q.deviceBroadcastsStmt != nil {
		if cerr := q.deviceBroadcastsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deviceBroadcastsStmt: %w", cerr)
		}
	}
	if q.deviceNetworkNamesStmt != nil {
		if cerr := q.deviceNetworkNamesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deviceNetworkNamesStmt: %w", cerr)
		}
	}
	if q.deviceStatsStmt != nil {
		if cerr := q.deviceStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deviceStatsStmt: %w", cerr)
		}
	}
	if q.deviceTrafficStmt != nil {
		if cerr := q.deviceTrafficStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deviceTrafficStmt: %w", cerr)
		}
	}
	if q.disableUserTOTPStmt != nil {
		if cerr := q.disableUserTOTPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing disableUserTOTPStmt: %w", cerr)
		}
	}
	if q.earliestTrafficStmt != nil {
		if cerr := q.earliestTrafficStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing earliestTrafficStmt: %w", cerr)
		}
	}
	if q.enableUserTOTPStmt != nil {
		if cerr := q.enableUserTOTPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing enableUserTOTPStmt: %w", cerr)
		}
	}
	if q.finishScanStmt != nil {
		if cerr := q.finishScanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing finishScanStmt: %w", cerr)
		}
	}
	if q.firstContactsStmt != nil {
		if cerr := q.firstContactsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing firstContactsStmt: %w", cerr)
		}
	}
	if q.getAddressStmt != nil {
		if cerr := q.getAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAddressStmt: %w", cerr)
		}
	}
	if q.getDeviceStmt != nil {
		if cerr := q.getDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceStmt: %w", cerr)
		}
	}
	if q.getDeviceByCurrentIPStmt != nil {
		if cerr := q.getDeviceByCurrentIPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceByCurrentIPStmt: %w", cerr)
		}
	}
	if q.getDeviceByMACStmt != nil {
		if cerr := q.getDeviceByMACStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceByMACStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.identifyDeviceStmt != nil {
		if cerr := q.identifyDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing identifyDeviceStmt: %w", cerr)
		}
	}
	if q.incomingFromInternetStmt != nil {
		if cerr := q.incomingFromInternetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incomingFromInternetStmt: %w", cerr)
		}
	}
	if q.insertAddressStmt != nil {
		if cerr := q.insertAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAddressStmt: %w", cerr)
		}
	}
	if q.latestSuccessfulScanFinishedAtStmt != nil {
		if cerr := q.latestSuccessfulScanFinishedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing latestSuccessfulScanFinishedAtStmt: %w", cerr)
		}
	}
	if q.listAPITokensByUserStmt != nil {
		if cerr := q.listAPITokensByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAPITokensByUserStmt: %w", cerr)
		}
	}
	if q.listDeviceAddressesStmt != nil {
		if cerr := q.listDeviceAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeviceAddressesStmt: %w", cerr)
		}
	}
	if q.listDeviceEventsStmt != nil {
		if cerr := q.listDeviceEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeviceEventsStmt: %w", cerr)
		}
	}
	if q.listDeviceOpenPortsStmt != nil {
		if cerr := q.listDeviceOpenPortsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeviceOpenPortsStmt: %w", cerr)
		}
	}
	if q.listDevicePortsStmt != nil {
		if cerr := q.listDevicePortsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDevicePortsStmt: %w", cerr)
		}
	}
	if q.listDeviceSourcesStmt != nil {
		if cerr := q.listDeviceSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeviceSourcesStmt: %w", cerr)
		}
	}
	if q.listDevicesStmt != nil {
		if cerr := q.listDevicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDevicesStmt: %w", cerr)
		}
	}
	if q.listGroupsStmt != nil {
		if cerr := q.listGroupsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGroupsStmt: %w", cerr)
		}
	}
	if q.listNetworksStmt != nil {
		if cerr := q.listNetworksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNetworksStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.moveAddressesStmt != nil {
		if cerr := q.moveAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing moveAddressesStmt: %w", cerr)
		}
	}
	if q.moveDeviceSourcesStmt != nil {
		if cerr := q.moveDeviceSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing moveDeviceSourcesStmt: %w", cerr)
		}
	}
	if q.moveEventsStmt != nil {
		if cerr := q.moveEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing moveEventsStmt: %w", cerr)
		}
	}
	if q.organisationDevicesStmt != nil {
		if cerr := q.organisationDevicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing organisationDevicesStmt: %w", cerr)
		}
	}
	if q.outsideAddressesStmt != nil {
		if cerr := q.outsideAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing outsideAddressesStmt: %w", cerr)
		}
	}
	if q.portStatsStmt != nil {
		if cerr := q.portStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing portStatsStmt: %w", cerr)
		}
	}
	if q.probePortsStmt != nil {
		if cerr := q.probePortsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing probePortsStmt: %w", cerr)
		}
	}
	if q.probedDevicesStmt != nil {
		if cerr := q.probedDevicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing probedDevicesStmt: %w", cerr)
		}
	}
	if q.probingHoursStmt != nil {
		if cerr := q.probingHoursStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing probingHoursStmt: %w", cerr)
		}
	}
	if q.redeemRecoveryCodeStmt != nil {
		if cerr := q.redeemRecoveryCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing redeemRecoveryCodeStmt: %w", cerr)
		}
	}
	if q.refreshAddressStmt != nil {
		if cerr := q.refreshAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshAddressStmt: %w", cerr)
		}
	}
	if q.releaseAddressStmt != nil {
		if cerr := q.releaseAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing releaseAddressStmt: %w", cerr)
		}
	}
	if q.retireAddressStmt != nil {
		if cerr := q.retireAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing retireAddressStmt: %w", cerr)
		}
	}
	if q.scanEventsStmt != nil {
		if cerr := q.scanEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing scanEventsStmt: %w", cerr)
		}
	}
	if q.scanSummaryStmt != nil {
		if cerr := q.scanSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing scanSummaryStmt: %w", cerr)
		}
	}
	if q.setDeviceClassStmt != nil {
		if cerr := q.setDeviceClassStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setDeviceClassStmt: %w", cerr)
		}
	}
	if q.setDeviceHostnameStmt != nil {
		if cerr := q.setDeviceHostnameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setDeviceHostnameStmt: %w", cerr)
		}
	}
	if q.setUserTOTPSecretStmt != nil {
		if cerr := q.setUserTOTPSecretStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserTOTPSecretStmt: %w", cerr)
		}
	}
	if q.topOrganisationsStmt != nil {
		if cerr := q.topOrganisationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing topOrganisationsStmt: %w", cerr)
		}
	}
	if q.touchAPITokenByHashStmt != nil {
		if cerr := q.touchAPITokenByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing touchAPITokenByHashStmt: %w", cerr)
		}
	}
	if q.touchDeviceStmt != nil {
		if cerr := q.touchDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing touchDeviceStmt: %w", cerr)
		}
	}
	if q.trafficMapDevicesStmt != nil {
		if cerr := q.trafficMapDevicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing trafficMapDevicesStmt: %w", cerr)
		}
	}
	if q.trafficMapLinksStmt != nil {
		if cerr := q.trafficMapLinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing trafficMapLinksStmt: %w", cerr)
		}
	}
	if q.trafficWorldPeersStmt != nil {
		if cerr := q.trafficWorldPeersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing trafficWorldPeersStmt: %w", cerr)
		}
	}
	if q.updateDeviceCurationStmt != nil {
		if cerr := q.updateDeviceCurationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDeviceCurationStmt: %w", cerr)
		}
	}
	if q.upsertAttemptsStmt != nil {
		if cerr := q.upsertAttemptsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAttemptsStmt: %w", cerr)
		}
	}
	if q.upsertBroadcastStmt != nil {
		if cerr := q.upsertBroadcastStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertBroadcastStmt: %w", cerr)
		}
	}
	if q.upsertDeviceSourceStmt != nil {
		if cerr := q.upsertDeviceSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertDeviceSourceStmt: %w", cerr)
		}
	}
	if q.upsertNetworkStmt != nil {
		if cerr := q.upsertNetworkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertNetworkStmt: %w", cerr)
		}
	}
	if q.upsertNetworkIdentityStmt != nil {
		if cerr := q.upsertNetworkIdentityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertNetworkIdentityStmt: %w", cerr)
		}
	}
	if q.upsertOpenPortStmt != nil {
		if cerr := q.upsertOpenPortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertOpenPortStmt: %w", cerr)
		}
	}
	if q.upsertOutsideAddressStmt != nil {
		if cerr := q.upsertOutsideAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertOutsideAddressStmt: %w", cerr)
		}
	}
	if q.upsertProbesStmt != nil {
		if cerr := q.upsertProbesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertProbesStmt: %w", cerr)
		}
	}
	if q.upsertSourceStmt != nil {
		if cerr := q.upsertSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSourceStmt: %w", cerr)
		}
	}
	if q.upsertTrafficStmt != nil {
		if cerr := q.upsertTrafficStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertTrafficStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	adoptCurationStmt                  *sql.Stmt
	allCurrentAddressesStmt            *sql.Stmt
	allNetworksStmt                    *sql.Stmt
	answerAttemptsStmt                 *sql.Stmt
	answerProbesStmt                   *sql.Stmt
	anyTrafficStmt                     *sql.Stmt
	attemptPortsStmt                   *sql.Stmt
	busiestDevicesStmt                 *sql.Stmt
	closePortStmt                      *sql.Stmt
	commonOpenServicesStmt             *sql.Stmt
	countUnusedRecoveryCodesByUserStmt *sql.Stmt
	countUsersStmt                     *sql.Stmt
	createAPITokenStmt                 *sql.Stmt
	createDeviceStmt                   *sql.Stmt
	createEventStmt                    *sql.Stmt
	createRecoveryCodeStmt             *sql.Stmt
	createScanStmt                     *sql.Stmt
	createUserStmt                     *sql.Stmt
	currentAddressesStmt               *sql.Stmt
	currentHoldersStmt                 *sql.Stmt
	deleteAPITokenStmt                 *sql.Stmt
	deleteAttemptsBeforeStmt           *sql.Stmt
	deleteBroadcastsBeforeStmt         *sql.Stmt
	deleteDeviceStmt                   *sql.Stmt
	deleteEventsBeforeStmt             *sql.Stmt
	deleteProbesBeforeStmt             *sql.Stmt
	deleteRecoveryCodesByUserStmt      *sql.Stmt
	deleteScansBeforeStmt              *sql.Stmt
	deleteTrafficBeforeStmt            *sql.Stmt
	deviceAttemptsStmt                 *sql.Stmt
	deviceBroadcastsStmt               *sql.Stmt
	deviceNetworkNamesStmt             *sql.Stmt
	deviceStatsStmt                    *sql.Stmt
	deviceTrafficStmt                  *sql.Stmt
	disableUserTOTPStmt                *sql.Stmt
	earliestTrafficStmt                *sql.Stmt
	enableUserTOTPStmt                 *sql.Stmt
	finishScanStmt                     *sql.Stmt
	firstContactsStmt                  *sql.Stmt
	getAddressStmt                     *sql.Stmt
	getDeviceStmt                      *sql.Stmt
	getDeviceByCurrentIPStmt           *sql.Stmt
	getDeviceByMACStmt                 *sql.Stmt
	getUserByIDStmt                    *sql.Stmt
	getUserByUsernameStmt              *sql.Stmt
	identifyDeviceStmt                 *sql.Stmt
	incomingFromInternetStmt           *sql.Stmt
	insertAddressStmt                  *sql.Stmt
	latestSuccessfulScanFinishedAtStmt *sql.Stmt
	listAPITokensByUserStmt            *sql.Stmt
	listDeviceAddressesStmt            *sql.Stmt
	listDeviceEventsStmt               *sql.Stmt
	listDeviceOpenPortsStmt            *sql.Stmt
	listDevicePortsStmt                *sql.Stmt
	listDeviceSourcesStmt              *sql.Stmt
	listDevicesStmt                    *sql.Stmt
	listGroupsStmt                     *sql.Stmt
	listNetworksStmt                   *sql.Stmt
	listUsersStmt                      *sql.Stmt
	moveAddressesStmt                  *sql.Stmt
	moveDeviceSourcesStmt              *sql.Stmt
	moveEventsStmt                     *sql.Stmt
	organisationDevicesStmt            *sql.Stmt
	outsideAddressesStmt               *sql.Stmt
	portStatsStmt                      *sql.Stmt
	probePortsStmt                     *sql.Stmt
	probedDevicesStmt                  *sql.Stmt
	probingHoursStmt                   *sql.Stmt
	redeemRecoveryCodeStmt             *sql.Stmt
	refreshAddressStmt                 *sql.Stmt
	releaseAddressStmt                 *sql.Stmt
	retireAddressStmt                  *sql.Stmt
	scanEventsStmt                     *sql.Stmt
	scanSummaryStmt                    *sql.Stmt
	setDeviceClassStmt                 *sql.Stmt
	setDeviceHostnameStmt              *sql.Stmt
	setUserTOTPSecretStmt              *sql.Stmt
	topOrganisationsStmt               *sql.Stmt
	touchAPITokenByHashStmt            *sql.Stmt
	touchDeviceStmt                    *sql.Stmt
	trafficMapDevicesStmt              *sql.Stmt
	trafficMapLinksStmt                *sql.Stmt
	trafficWorldPeersStmt              *sql.Stmt
	updateDeviceCurationStmt           *sql.Stmt
	upsertAttemptsStmt                 *sql.Stmt
	upsertBroadcastStmt                *sql.Stmt
	upsertDeviceSourceStmt             *sql.Stmt
	upsertNetworkStmt                  *sql.Stmt
	upsertNetworkIdentityStmt          *sql.Stmt
	upsertOpenPortStmt                 *sql.Stmt
	upsertOutsideAddressStmt           *sql.Stmt
	upsertProbesStmt                   *sql.Stmt
	upsertSourceStmt                   *sql.Stmt
	upsertTrafficStmt                  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		adoptCurationStmt:                  q.adoptCurationStmt,
		allCurrentAddressesStmt:            q.allCurrentAddressesStmt,
		allNetworksStmt:                    q.allNetworksStmt,
		answerAttemptsStmt:                 q.answerAttemptsStmt,
		answerProbesStmt:                   q.answerProbesStmt,
		anyTrafficStmt:                     q.anyTrafficStmt,
		attemptPortsStmt:                   q.attemptPortsStmt,
		busiestDevicesStmt:                 q.busiestDevicesStmt,
		closePortStmt:                      q.closePortStmt,
		commonOpenServicesStmt:             q.commonOpenServicesStmt,
		countUnusedRecoveryCodesByUserStmt: q.countUnusedRecoveryCodesByUserStmt,
		countUsersStmt:                     q.countUsersStmt,
		createAPITokenStmt:                 q.createAPITokenStmt,
		createDeviceStmt:                   q.createDeviceStmt,
		createEventStmt:                    q.createEventStmt,
		createRecoveryCodeStmt:             q.createRecoveryCodeStmt,
		createScanStmt:                     q.createScanStmt,
		createUserStmt:                     q.createUserStmt,
		currentAddressesStmt:               q.currentAddressesStmt,
		currentHoldersStmt:                 q.currentHoldersStmt,
		deleteAPITokenStmt:                 q.deleteAPITokenStmt,
		deleteAttemptsBeforeStmt:           q.deleteAttemptsBeforeStmt,
		deleteBroadcastsBeforeStmt:         q.deleteBroadcastsBeforeStmt,
		deleteDeviceStmt:                   q.deleteDeviceStmt,
		deleteEventsBeforeStmt:             q.deleteEventsBeforeStmt,
		deleteProbesBeforeStmt:             q.deleteProbesBeforeStmt,
		deleteRecoveryCodesByUserStmt:      q.deleteRecoveryCodesByUserStmt,
		deleteScansBeforeStmt:              q.deleteScansBeforeStmt,
		deleteTrafficBeforeStmt:            q.deleteTrafficBeforeStmt,
		deviceAttemptsStmt:                 q.deviceAttemptsStmt,
		deviceBroadcastsStmt:               q.deviceBroadcastsStmt,
		deviceNetworkNamesStmt:             q.deviceNetworkNamesStmt,
		deviceStatsStmt:                    q.deviceStatsStmt,
		deviceTrafficStmt:                  q.deviceTrafficStmt,
		disableUserTOTPStmt:                q.disableUserTOTPStmt,
		earliestTrafficStmt:                q.earliestTrafficStmt,
		enableUserTOTPStmt:                 q.enableUserTOTPStmt,
		finishScanStmt:                     q.finishScanStmt,
		firstContactsStmt:                  q.firstContactsStmt,
		getAddressStmt:                     q.getAddressStmt,
		getDeviceStmt:                      q.getDeviceStmt,
		getDeviceByCurrentIPStmt:           q.getDeviceByCurrentIPStmt,
		getDeviceByMACStmt:                 q.getDeviceByMACStmt,
		getUserByIDStmt:                    q.getUserByIDStmt,
		getUserByUsernameStmt:              q.getUserByUsernameStmt,
		identifyDeviceStmt:                 q.identifyDeviceStmt,
		incomingFromInternetStmt:           q.incomingFromInternetStmt,
		insertAddressStmt:                  q.insertAddressStmt,
		latestSuccessfulScanFinishedAtStmt: q.latestSuccessfulScanFinishedAtStmt,
		listAPITokensByUserStmt:            q.listAPITokensByUserStmt,
		listDeviceAddressesStmt:            q.listDeviceAddressesStmt,
		listDeviceEventsStmt:               q.listDeviceEventsStmt,
		listDeviceOpenPortsStmt:            q.listDeviceOpenPortsStmt,
		listDevicePortsStmt:                q.listDevicePortsStmt,
		listDeviceSourcesStmt:              q.listDeviceSourcesStmt,
		listDevicesStmt:                    q.listDevicesStmt,
		listGroupsStmt:                     q.listGroupsStmt,
		listNetworksStmt:                   q.listNetworksStmt,
		listUsersStmt:                      q.listUsersStmt,
		moveAddressesStmt:                  q.moveAddressesStmt,
		moveDeviceSourcesStmt:              q.moveDeviceSourcesStmt,
		moveEventsStmt:                     q.moveEventsStmt,
		organisationDevicesStmt:            q.organisationDevicesStmt,
		outsideAddressesStmt:               q.outsideAddressesStmt,
		portStatsStmt:                      q.portStatsStmt,
		probePortsStmt:                     q.probePortsStmt,
		probedDevicesStmt:                  q.probedDevicesStmt,
		probingHoursStmt:                   q.probingHoursStmt,
		redeemRecoveryCodeStmt:             q.redeemRecoveryCodeStmt,
		refreshAddressStmt:                 q.refreshAddressStmt,
		releaseAddressStmt:                 q.releaseAddressStmt,
		retireAddressStmt:                  q.retireAddressStmt,
		scanEventsStmt:                     q.scanEventsStmt,
		scanSummaryStmt:                    q.scanSummaryStmt,
		setDeviceClassStmt:                 q.setDeviceClassStmt,
		setDeviceHostnameStmt:              q.setDeviceHostnameStmt,
		setUserTOTPSecretStmt:              q.setUserTOTPSecretStmt,
		topOrganisationsStmt:               q.topOrganisationsStmt,
		touchAPITokenByHashStmt:            q.touchAPITokenByHashStmt,
		touchDeviceStmt:                    q.touchDeviceStmt,
		trafficMapDevicesStmt:              q.trafficMapDevicesStmt,
		trafficMapLinksStmt:                q.trafficMapLinksStmt,
		trafficWorldPeersStmt:              q.trafficWorldPeersStmt,
		updateDeviceCurationStmt:           q.updateDeviceCurationStmt,
		upsertAttemptsStmt:                 q.upsertAttemptsStmt,
		upsertBroadcastStmt:                q.upsertBroadcastStmt,
		upsertDeviceSourceStmt:             q.upsertDeviceSourceStmt,
		upsertNetworkStmt:                  q.upsertNetworkStmt,
		upsertNetworkIdentityStmt:          q.upsertNetworkIdentityStmt,
		upsertOpenPortStmt:                 q.upsertOpenPortStmt,
		upsertOutsideAddressStmt:           q.upsertOutsideAddressStmt,
		upsertProbesStmt:                   q.upsertProbesStmt,
		upsertSourceStmt:                   q.upsertSourceStmt,
		upsertTrafficStmt:                  q.upsertTrafficStmt,
	}
}
