// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adoptCurationStmt, err = db.PrepareContext(ctx, adoptCuration); err != nil {
		return nil, fmt.Errorf("error preparing query AdoptCuration: %w", err)
	}
	if q.allCurrentAddressesStmt, err = db.PrepareContext(ctx, allCurrentAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query AllCurrentAddresses: %w", err)
	}
	if q.allNetworksStmt, err = db.PrepareContext(ctx, allNetworks); err != nil {
		return nil, fmt.Errorf("error preparing query AllNetworks: %w", err)
	}
	if q.closePortStmt, err = db.PrepareContext(ctx, closePort); err != nil {
		return nil, fmt.Errorf("error preparing query ClosePort: %w", err)
	}
	if q.commonOpenServicesStmt, err = db.PrepareContext(ctx, commonOpenServices); err != nil {
		return nil, fmt.Errorf("error preparing query CommonOpenServices: %w", err)
	}
	if q.createAPITokenStmt, err = db.PrepareContext(ctx, createAPIToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAPIToken: %w", err)
	}
	if q.createDeviceStmt, err = db.PrepareContext(ctx, createDevice); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDevice: %w", err)
	}
	if q.createEventStmt, err = db.PrepareContext(ctx, createEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEvent: %w", err)
	}
	if q.createScanStmt, err = db.PrepareContext(ctx, createScan); err != nil {
		return nil, fmt.Errorf("error preparing query CreateScan: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.currentAddressesStmt, err = db.PrepareContext(ctx, currentAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query CurrentAddresses: %w", err)
	}
	if q.deleteAPITokenStmt, err = db.PrepareContext(ctx, deleteAPIToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAPIToken: %w", err)
	}
	if q.deleteDeviceStmt, err = db.PrepareContext(ctx, deleteDevice); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDevice: %w", err)
	}
	if q.deviceNetworkNamesStmt, err = db.PrepareContext(ctx, deviceNetworkNames); err != nil {
		return nil, fmt.Errorf("error preparing query DeviceNetworkNames: %w", err)
	}
	if q.deviceStatsStmt, err = db.PrepareContext(ctx, deviceStats); err != nil {
		return nil, fmt.Errorf("error preparing query DeviceStats: %w", err)
	}
	if q.finishScanStmt, err = db.PrepareContext(ctx, finishScan); err != nil {
		return nil, fmt.Errorf("error preparing query FinishScan: %w", err)
	}
	if q.getAddressStmt, err = db.PrepareContext(ctx, getAddress); err != nil {
		return nil, fmt.Errorf("error preparing query GetAddress: %w", err)
	}
	if q.getDeviceStmt, err = db.PrepareContext(ctx, getDevice); err != nil {
		return nil, fmt.Errorf("error preparing query GetDevice: %w", err)
	}
	if q.getDeviceByCurrentIPStmt, err = db.PrepareContext(ctx, getDeviceByCurrentIP); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeviceByCurrentIP: %w", err)
	}
	if q.getDeviceByMACStmt, err = db.PrepareContext(ctx, getDeviceByMAC); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeviceByMAC: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.identifyDeviceStmt, err = db.PrepareContext(ctx, identifyDevice); err != nil {
		return nil, fmt.Errorf("error preparing query IdentifyDevice: %w", err)
	}
	if q.insertAddressStmt, err = db.PrepareContext(ctx, insertAddress); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAddress: %w", err)
	}
	if q.latestSuccessfulScanFinishedAtStmt, err = db.PrepareContext(ctx, latestSuccessfulScanFinishedAt); err != nil {
		return nil, fmt.Errorf("error preparing query LatestSuccessfulScanFinishedAt: %w", err)
	}
	if q.listAPITokensByUserStmt, err = db.PrepareContext(ctx, listAPITokensByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListAPITokensByUser: %w", err)
	}
	if q.listDeviceAddressesStmt, err = db.PrepareContext(ctx, listDeviceAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeviceAddresses: %w", err)
	}
	if q.listDeviceEventsStmt, err = db.PrepareContext(ctx, listDeviceEvents); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeviceEvents: %w", err)
	}
	if q.listDeviceOpenPortsStmt, err = db.PrepareContext(ctx, listDeviceOpenPorts); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeviceOpenPorts: %w", err)
	}
	if q.listDevicePortsStmt, err = db.PrepareContext(ctx, listDevicePorts); err != nil {
		return nil, fmt.Errorf("error preparing query ListDevicePorts: %w", err)
	}
	if q.listDeviceSourcesStmt, err = db.PrepareContext(ctx, listDeviceSources); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeviceSources: %w", err)
	}
	if q.listDevicesStmt, err = db.PrepareContext(ctx, listDevices); err != nil {
		return nil, fmt.Errorf("error preparing query ListDevices: %w", err)
	}
	if q.listGroupsStmt, err = db.PrepareContext(ctx, listGroups); err != nil {
		return nil, fmt.Errorf("error preparing query ListGroups: %w", err)
	}
	if q.listNetworksStmt, err = db.PrepareContext(ctx, listNetworks); err != nil {
		return nil, fmt.Errorf("error preparing query ListNetworks: %w", err)
	}
	if q.moveAddressesStmt, err = db.PrepareContext(ctx, moveAddresses); err != nil {
		return nil, fmt.Errorf("error preparing query MoveAddresses: %w", err)
	}
	if q.moveDeviceSourcesStmt, err = db.PrepareContext(ctx, moveDeviceSources); err != nil {
		return nil, fmt.Errorf("error preparing query MoveDeviceSources: %w", err)
	}
	if q.moveEventsStmt, err = db.PrepareContext(ctx, moveEvents); err != nil {
		return nil, fmt.Errorf("error preparing query MoveEvents: %w", err)
	}
	if q.portStatsStmt, err = db.PrepareContext(ctx, portStats); err != nil {
		return nil, fmt.Errorf("error preparing query PortStats: %w", err)
	}
	if q.refreshAddressStmt, err = db.PrepareContext(ctx, refreshAddress); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshAddress: %w", err)
	}
	if q.releaseAddressStmt, err = db.PrepareContext(ctx, releaseAddress); err != nil {
		return nil, fmt.Errorf("error preparing query ReleaseAddress: %w", err)
	}
	if q.retireAddressStmt, err = db.PrepareContext(ctx, retireAddress); err != nil {
		return nil, fmt.Errorf("error preparing query RetireAddress: %w", err)
	}
	if q.setDeviceClassStmt, err = db.PrepareContext(ctx, setDeviceClass); err != nil {
		return nil, fmt.Errorf("error preparing query SetDeviceClass: %w", err)
	}
	if q.setDeviceHostnameStmt, err = db.PrepareContext(ctx, setDeviceHostname); err != nil {
		return nil, fmt.Errorf("error preparing query SetDeviceHostname: %w", err)
	}
	if q.touchAPITokenByHashStmt, err = db.PrepareContext(ctx, touchAPITokenByHash); err != nil {
		return nil, fmt.Errorf("error preparing query TouchAPITokenByHash: %w", err)
	}
	if q.touchDeviceStmt, err = db.PrepareContext(ctx, touchDevice); err != nil {
		return nil, fmt.Errorf("error preparing query TouchDevice: %w", err)
	}
	if q.updateDeviceCurationStmt, err = db.PrepareContext(ctx, updateDeviceCuration); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDeviceCuration: %w", err)
	}
	if q.upsertDeviceSourceStmt, err = db.PrepareContext(ctx, upsertDeviceSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertDeviceSource: %w", err)
	}
	if q.upsertNetworkStmt, err = db.PrepareContext(ctx, upsertNetwork); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertNetwork: %w", err)
	}
	if q.upsertNetworkIdentityStmt, err = db.PrepareContext(ctx, upsertNetworkIdentity); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertNetworkIdentity: %w", err)
	}
	if q.upsertOpenPortStmt, err = db.PrepareContext(ctx, upsertOpenPort); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertOpenPort: %w", err)
	}
	if q.upsertSourceStmt, err = db.PrepareContext(ctx, upsertSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSource: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adoptCurationStmt != nil {
		if cerr := q.adoptCurationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adoptCurationStmt: %w", cerr)
		}
	}
	if q.allCurrentAddressesStmt != nil {
		if cerr := q.allCurrentAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing allCurrentAddressesStmt: %w", cerr)
		}
	}
	if q.allNetworksStmt != nil {
		if cerr := q.allNetworksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing allNetworksStmt: %w", cerr)
		}
	}
	if q.closePortStmt != nil {
		if cerr := q.closePortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing closePortStmt: %w", cerr)
		}
	}
	if q.commonOpenServicesStmt != nil {
		if cerr := q.commonOpenServicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing commonOpenServicesStmt: %w", cerr)
		}
	}
	if q.createAPITokenStmt != nil {
		if cerr := q.createAPITokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAPITokenStmt: %w", cerr)
		}
	}
	if q.createDeviceStmt != nil {
		if cerr := q.createDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeviceStmt: %w", cerr)
		}
	}
	if q.createEventStmt != nil {
		if cerr := q.createEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEventStmt: %w", cerr)
		}
	}
	if q.createScanStmt != nil {
		if cerr := q.createScanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createScanStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.currentAddressesStmt != nil {
		if cerr := q.currentAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing currentAddressesStmt: %w", cerr)
		}
	}
	if q.deleteAPITokenStmt != nil {
		if cerr := q.deleteAPITokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAPITokenStmt: %w", cerr)
		}
	}
	if q.deleteDeviceStmt != nil {
		if cerr := q.deleteDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDeviceStmt: %w", cerr)
		}
	}
	if q.deviceNetworkNamesStmt != nil {
		if cerr := q.deviceNetworkNamesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deviceNetworkNamesStmt: %w", cerr)
		}
	}
	if q.deviceStatsStmt != nil {
		if cerr := q.deviceStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deviceStatsStmt: %w", cerr)
		}
	}
	if q.finishScanStmt != nil {
		if cerr := q.finishScanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing finishScanStmt: %w", cerr)
		}
	}
	if q.getAddressStmt != nil {
		if cerr := q.getAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAddressStmt: %w", cerr)
		}
	}
	if q.getDeviceStmt != nil {
		if cerr := q.getDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceStmt: %w", cerr)
		}
	}
	if q.getDeviceByCurrentIPStmt != nil {
		if cerr := q.getDeviceByCurrentIPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceByCurrentIPStmt: %w", cerr)
		}
	}
	if q.getDeviceByMACStmt != nil {
		if cerr := q.getDeviceByMACStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceByMACStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.identifyDeviceStmt != nil {
		if cerr := q.identifyDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing identifyDeviceStmt: %w", cerr)
		}
	}
	if q.insertAddressStmt != nil {
		if cerr := q.insertAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAddressStmt: %w", cerr)
		}
	}
	if q.latestSuccessfulScanFinishedAtStmt != nil {
		if cerr := q.latestSuccessfulScanFinishedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing latestSuccessfulScanFinishedAtStmt: %w", cerr)
		}
	}
	if q.listAPITokensByUserStmt != nil {
		if cerr := q.listAPITokensByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAPITokensByUserStmt: %w", cerr)
		}
	}
	if q.listDeviceAddressesStmt != nil {
		if cerr := q.listDeviceAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeviceAddressesStmt: %w", cerr)
		}
	}
	if q.listDeviceEventsStmt != nil {
		if cerr := q.listDeviceEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeviceEventsStmt: %w", cerr)
		}
	}
	if q.listDeviceOpenPortsStmt != nil {
		if cerr := q.listDeviceOpenPortsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeviceOpenPortsStmt: %w", cerr)
		}
	}
	if q.listDevicePortsStmt != nil {
		if cerr := q.listDevicePortsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDevicePortsStmt: %w", cerr)
		}
	}
	if q.listDeviceSourcesStmt != nil {
		if cerr := q.listDeviceSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeviceSourcesStmt: %w", cerr)
		}
	}
	if q.listDevicesStmt != nil {
		if cerr := q.listDevicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDevicesStmt: %w", cerr)
		}
	}
	if q.listGroupsStmt != nil {
		if cerr := q.listGroupsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGroupsStmt: %w", cerr)
		}
	}
	if q.listNetworksStmt != nil {
		if cerr := q.listNetworksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNetworksStmt: %w", cerr)
		}
	}
	if q.moveAddressesStmt != nil {
		if cerr := q.moveAddressesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing moveAddressesStmt: %w", cerr)
		}
	}
	if q.moveDeviceSourcesStmt != nil {
		if cerr := q.moveDeviceSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing moveDeviceSourcesStmt: %w", cerr)
		}
	}
	if q.moveEventsStmt != nil {
		if cerr := q.moveEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing moveEventsStmt: %w", cerr)
		}
	}
	if q.portStatsStmt != nil {
		if cerr := q.portStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing portStatsStmt: %w", cerr)
		}
	}
	if q.refreshAddressStmt != nil {
		if cerr := q.refreshAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshAddressStmt: %w", cerr)
		}
	}
	if q.releaseAddressStmt != nil {
		if cerr := q.releaseAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing releaseAddressStmt: %w", cerr)
		}
	}
	if q.retireAddressStmt != nil {
		if cerr := q.retireAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing retireAddressStmt: %w", cerr)
		}
	}
	if q.setDeviceClassStmt != nil {
		if cerr := q.setDeviceClassStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setDeviceClassStmt: %w", cerr)
		}
	}
	if q.setDeviceHostnameStmt != nil {
		if cerr := q.setDeviceHostnameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setDeviceHostnameStmt: %w", cerr)
		}
	}
	if q.touchAPITokenByHashStmt != nil {
		if cerr := q.touchAPITokenByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing touchAPITokenByHashStmt: %w", cerr)
		}
	}
	if q.touchDeviceStmt != nil {
		if cerr := q.touchDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing touchDeviceStmt: %w", cerr)
		}
	}
	if q.updateDeviceCurationStmt != nil {
		if cerr := q.updateDeviceCurationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDeviceCurationStmt: %w", cerr)
		}
	}
	if q.upsertDeviceSourceStmt != nil {
		if cerr := q.upsertDeviceSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertDeviceSourceStmt: %w", cerr)
		}
	}
	if q.upsertNetworkStmt != nil {
		if cerr := q.upsertNetworkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertNetworkStmt: %w", cerr)
		}
	}
	if q.upsertNetworkIdentityStmt != nil {
		if cerr := q.upsertNetworkIdentityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertNetworkIdentityStmt: %w", cerr)
		}
	}
	if q.upsertOpenPortStmt != nil {
		if cerr := q.upsertOpenPortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertOpenPortStmt: %w", cerr)
		}
	}
	if q.upsertSourceStmt != nil {
		if cerr := q.upsertSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSourceStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	adoptCurationStmt                  *sql.Stmt
	allCurrentAddressesStmt            *sql.Stmt
	allNetworksStmt                    *sql.Stmt
	closePortStmt                      *sql.Stmt
	commonOpenServicesStmt             *sql.Stmt
	createAPITokenStmt                 *sql.Stmt
	createDeviceStmt                   *sql.Stmt
	createEventStmt                    *sql.Stmt
	createScanStmt                     *sql.Stmt
	createUserStmt                     *sql.Stmt
	currentAddressesStmt               *sql.Stmt
	deleteAPITokenStmt                 *sql.Stmt
	deleteDeviceStmt                   *sql.Stmt
	deviceNetworkNamesStmt             *sql.Stmt
	deviceStatsStmt                    *sql.Stmt
	finishScanStmt                     *sql.Stmt
	getAddressStmt                     *sql.Stmt
	getDeviceStmt                      *sql.Stmt
	getDeviceByCurrentIPStmt           *sql.Stmt
	getDeviceByMACStmt                 *sql.Stmt
	getUserByUsernameStmt              *sql.Stmt
	identifyDeviceStmt                 *sql.Stmt
	insertAddressStmt                  *sql.Stmt
	latestSuccessfulScanFinishedAtStmt *sql.Stmt
	listAPITokensByUserStmt            *sql.Stmt
	listDeviceAddressesStmt            *sql.Stmt
	listDeviceEventsStmt               *sql.Stmt
	listDeviceOpenPortsStmt            *sql.Stmt
	listDevicePortsStmt                *sql.Stmt
	listDeviceSourcesStmt              *sql.Stmt
	listDevicesStmt                    *sql.Stmt
	listGroupsStmt                     *sql.Stmt
	listNetworksStmt                   *sql.Stmt
	moveAddressesStmt                  *sql.Stmt
	moveDeviceSourcesStmt              *sql.Stmt
	moveEventsStmt                     *sql.Stmt
	portStatsStmt                      *sql.Stmt
	refreshAddressStmt                 *sql.Stmt
	releaseAddressStmt                 *sql.Stmt
	retireAddressStmt                  *sql.Stmt
	setDeviceClassStmt                 *sql.Stmt
	setDeviceHostnameStmt              *sql.Stmt
	touchAPITokenByHashStmt            *sql.Stmt
	touchDeviceStmt                    *sql.Stmt
	updateDeviceCurationStmt           *sql.Stmt
	upsertDeviceSourceStmt             *sql.Stmt
	upsertNetworkStmt                  *sql.Stmt
	upsertNetworkIdentityStmt          *sql.Stmt
	upsertOpenPortStmt                 *sql.Stmt
	upsertSourceStmt                   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		adoptCurationStmt:                  q.adoptCurationStmt,
		allCurrentAddressesStmt:            q.allCurrentAddressesStmt,
		allNetworksStmt:                    q.allNetworksStmt,
		closePortStmt:                      q.closePortStmt,
		commonOpenServicesStmt:             q.commonOpenServicesStmt,
		createAPITokenStmt:                 q.createAPITokenStmt,
		createDeviceStmt:                   q.createDeviceStmt,
		createEventStmt:                    q.createEventStmt,
		createScanStmt:                     q.createScanStmt,
		createUserStmt:                     q.createUserStmt,
		currentAddressesStmt:               q.currentAddressesStmt,
		deleteAPITokenStmt:                 q.deleteAPITokenStmt,
		deleteDeviceStmt:                   q.deleteDeviceStmt,
		deviceNetworkNamesStmt:             q.deviceNetworkNamesStmt,
		deviceStatsStmt:                    q.deviceStatsStmt,
		finishScanStmt:                     q.finishScanStmt,
		getAddressStmt:                     q.getAddressStmt,
		getDeviceStmt:                      q.getDeviceStmt,
		getDeviceByCurrentIPStmt:           q.getDeviceByCurrentIPStmt,
		getDeviceByMACStmt:                 q.getDeviceByMACStmt,
		getUserByUsernameStmt:              q.getUserByUsernameStmt,
		identifyDeviceStmt:                 q.identifyDeviceStmt,
		insertAddressStmt:                  q.insertAddressStmt,
		latestSuccessfulScanFinishedAtStmt: q.latestSuccessfulScanFinishedAtStmt,
		listAPITokensByUserStmt:            q.listAPITokensByUserStmt,
		listDeviceAddressesStmt:            q.listDeviceAddressesStmt,
		listDeviceEventsStmt:               q.listDeviceEventsStmt,
		listDeviceOpenPortsStmt:            q.listDeviceOpenPortsStmt,
		listDevicePortsStmt:                q.listDevicePortsStmt,
		listDeviceSourcesStmt:              q.listDeviceSourcesStmt,
		listDevicesStmt:                    q.listDevicesStmt,
		listGroupsStmt:                     q.listGroupsStmt,
		listNetworksStmt:                   q.listNetworksStmt,
		moveAddressesStmt:                  q.moveAddressesStmt,
		moveDeviceSourcesStmt:              q.moveDeviceSourcesStmt,
		moveEventsStmt:                     q.moveEventsStmt,
		portStatsStmt:                      q.portStatsStmt,
		refreshAddressStmt:                 q.refreshAddressStmt,
		releaseAddressStmt:                 q.releaseAddressStmt,
		retireAddressStmt:                  q.retireAddressStmt,
		setDeviceClassStmt:                 q.setDeviceClassStmt,
		setDeviceHostnameStmt:              q.setDeviceHostnameStmt,
		touchAPITokenByHashStmt:            q.touchAPITokenByHashStmt,
		touchDeviceStmt:                    q.touchDeviceStmt,
		updateDeviceCurationStmt:           q.updateDeviceCurationStmt,
		upsertDeviceSourceStmt:             q.upsertDeviceSourceStmt,
		upsertNetworkStmt:                  q.upsertNetworkStmt,
		upsertNetworkIdentityStmt:          q.upsertNetworkIdentityStmt,
		upsertOpenPortStmt:                 q.upsertOpenPortStmt,
		upsertSourceStmt:                   q.upsertSourceStmt,
	}
}
