// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package models

import (
	"context"
	"database/sql"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const adoptCuration = `-- name: AdoptCuration :exec
UPDATE devices
SET label      = COALESCE(label, ?1),
    notes      = COALESCE(notes, ?2),
    group_name = COALESCE(group_name, ?3),
    first_seen = ?4
WHERE id = ?5
`

type AdoptCurationParams struct {
	FoldedLabel     sql.NullString `json:"folded_label"`
	FoldedNotes     sql.NullString `json:"folded_notes"`
	FoldedGroupName sql.NullString `json:"folded_group_name"`
	FirstSeen       dbtype.Time    `json:"first_seen"`
	ID              int64          `json:"id"`
}

// A device folded into another may carry a label the user set before its MAC
// was known, and the earlier of the two first_seen values is the true one.
//
//	UPDATE devices
//	SET label      = COALESCE(label, ?1),
//	    notes      = COALESCE(notes, ?2),
//	    group_name = COALESCE(group_name, ?3),
//	    first_seen = ?4
//	WHERE id = ?5
func (q *Queries) AdoptCuration(ctx context.Context, arg AdoptCurationParams) error {
	_, err := q.exec(ctx, q.adoptCurationStmt, adoptCuration,
		arg.FoldedLabel,
		arg.FoldedNotes,
		arg.FoldedGroupName,
		arg.FirstSeen,
		arg.ID,
	)
	return err
}

const allCurrentAddresses = `-- name: AllCurrentAddresses :many

SELECT a.device_id, a.ip
FROM addresses a
         JOIN devices d ON d.id = a.device_id
WHERE a.is_current = 1
  AND d.is_ignored = 0
ORDER BY a.device_id, a.ip
`

type AllCurrentAddressesRow struct {
	DeviceID int64       `json:"device_id"`
	IP       dbtype.Addr `json:"ip"`
}

// Ports.
// Every address a port scan should probe: the current address of every device
// the user has not ignored. The scan works from what discovery has already
// found rather than sweeping, so this is its whole target list.
//
//	SELECT a.device_id, a.ip
//	FROM addresses a
//	         JOIN devices d ON d.id = a.device_id
//	WHERE a.is_current = 1
//	  AND d.is_ignored = 0
//	ORDER BY a.device_id, a.ip
func (q *Queries) AllCurrentAddresses(ctx context.Context) ([]*AllCurrentAddressesRow, error) {
	rows, err := q.query(ctx, q.allCurrentAddressesStmt, allCurrentAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AllCurrentAddressesRow
	for rows.Next() {
		var i AllCurrentAddressesRow
		if err := rows.Scan(&i.DeviceID, &i.IP); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allNetworks = `-- name: AllNetworks :many
SELECT id, cidr
FROM networks
ORDER BY id
`

type AllNetworksRow struct {
	ID   int64         `json:"id"`
	Cidr dbtype.Prefix `json:"cidr"`
}

// Every recorded network, for matching an address to the prefix containing it.
// SQLite cannot test containment, so the comparison happens in Go and this
// returns the whole (small) table rather than filtering.
//
//	SELECT id, cidr
//	FROM networks
//	ORDER BY id
func (q *Queries) AllNetworks(ctx context.Context) ([]*AllNetworksRow, error) {
	rows, err := q.query(ctx, q.allNetworksStmt, allNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AllNetworksRow
	for rows.Next() {
		var i AllNetworksRow
		if err := rows.Scan(&i.ID, &i.Cidr); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closePort = `-- name: ClosePort :exec
UPDATE device_ports
SET state      = 'closed',
    last_seen  = ?1,
    changed_at = ?1
WHERE device_id = ?2
  AND port = ?3
  AND state = 'open'
`

type ClosePortParams struct {
	SeenAt   dbtype.Time `json:"seen_at"`
	DeviceID int64       `json:"device_id"`
	Port     int64       `json:"port"`
}

// A port we had open did not answer this run. Keep the row, flip the state,
// record when it went.
//
//	UPDATE device_ports
//	SET state      = 'closed',
//	    last_seen  = ?1,
//	    changed_at = ?1
//	WHERE device_id = ?2
//	  AND port = ?3
//	  AND state = 'open'
func (q *Queries) ClosePort(ctx context.Context, arg ClosePortParams) error {
	_, err := q.exec(ctx, q.closePortStmt, closePort, arg.SeenAt, arg.DeviceID, arg.Port)
	return err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (mac, identity_source, is_randomised, vendor, hostname, hostname_source,
                     first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen, device_class, device_class_confidence
`

type CreateDeviceParams struct {
	MAC            dbtype.MAC            `json:"mac"`
	IdentitySource dbtype.IdentitySource `json:"identity_source"`
	IsRandomised   bool                  `json:"is_randomised"`
	Vendor         sql.NullString        `json:"vendor"`
	Hostname       sql.NullString        `json:"hostname"`
	HostnameSource dbtype.HostnameSource `json:"hostname_source"`
	FirstSeen      dbtype.Time           `json:"first_seen"`
	LastSeen       dbtype.Time           `json:"last_seen"`
}

// CreateDevice
//
//	INSERT INTO devices (mac, identity_source, is_randomised, vendor, hostname, hostname_source,
//	                     first_seen, last_seen)
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?)
//	RETURNING id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen, device_class, device_class_confidence
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (*Device, error) {
	row := q.queryRow(ctx, q.createDeviceStmt, createDevice,
		arg.MAC,
		arg.IdentitySource,
		arg.IsRandomised,
		arg.Vendor,
		arg.Hostname,
		arg.HostnameSource,
		arg.FirstSeen,
		arg.LastSeen,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MAC,
		&i.IdentitySource,
		&i.IsRandomised,
		&i.Vendor,
		&i.Hostname,
		&i.HostnameSource,
		&i.DeviceType,
		&i.Label,
		&i.Notes,
		&i.GroupName,
		&i.IsIgnored,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DeviceClass,
		&i.DeviceClassConfidence,
	)
	return &i, err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (device_id, scan_id, kind, old_value, new_value, detail, occurred_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	DeviceID   sql.NullInt64    `json:"device_id"`
	ScanID     sql.NullInt64    `json:"scan_id"`
	Kind       dbtype.EventKind `json:"kind"`
	OldValue   sql.NullString   `json:"old_value"`
	NewValue   sql.NullString   `json:"new_value"`
	Detail     sql.NullString   `json:"detail"`
	OccurredAt dbtype.Time      `json:"occurred_at"`
}

// CreateEvent
//
//	INSERT INTO events (device_id, scan_id, kind, old_value, new_value, detail, occurred_at)
//	VALUES (?, ?, ?, ?, ?, ?, ?)
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.exec(ctx, q.createEventStmt, createEvent,
		arg.DeviceID,
		arg.ScanID,
		arg.Kind,
		arg.OldValue,
		arg.NewValue,
		arg.Detail,
		arg.OccurredAt,
	)
	return err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (source_id, kind, network_id, started_at)
VALUES (?, ?, ?, ?)
RETURNING id, source_id, kind, network_id, status, error, found_count, started_at, finished_at
`

type CreateScanParams struct {
	SourceID  int64           `json:"source_id"`
	Kind      dbtype.ScanKind `json:"kind"`
	NetworkID sql.NullInt64   `json:"network_id"`
	StartedAt dbtype.Time     `json:"started_at"`
}

// CreateScan
//
//	INSERT INTO scans (source_id, kind, network_id, started_at)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, source_id, kind, network_id, status, error, found_count, started_at, finished_at
func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (*Scan, error) {
	row := q.queryRow(ctx, q.createScanStmt, createScan,
		arg.SourceID,
		arg.Kind,
		arg.NetworkID,
		arg.StartedAt,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Kind,
		&i.NetworkID,
		&i.Status,
		&i.Error,
		&i.FoundCount,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const currentAddresses = `-- name: CurrentAddresses :many
SELECT id, device_id, network_id, ip, is_current, first_seen, last_seen
FROM addresses
WHERE device_id = ?
  AND is_current = 1
`

// Every address a device holds right now, for deciding which of them it has
// moved off after a sweep that answered on another.
//
//	SELECT id, device_id, network_id, ip, is_current, first_seen, last_seen
//	FROM addresses
//	WHERE device_id = ?
//	  AND is_current = 1
func (q *Queries) CurrentAddresses(ctx context.Context, deviceID int64) ([]*Address, error) {
	rows, err := q.query(ctx, q.currentAddressesStmt, currentAddresses, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NetworkID,
			&i.IP,
			&i.IsCurrent,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE
FROM devices
WHERE id = ?
`

// DeleteDevice
//
//	DELETE
//	FROM devices
//	WHERE id = ?
func (q *Queries) DeleteDevice(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteDeviceStmt, deleteDevice, id)
	return err
}

const deviceNetworkNames = `-- name: DeviceNetworkNames :many
SELECT DISTINCT n.name AS name
FROM addresses a
         JOIN networks n ON n.id = a.network_id
WHERE a.device_id = ?
  AND a.is_current = 1
  AND n.name IS NOT NULL
  AND n.name <> ''
`

// The names of the segments a device currently sits on, for the classifier: a
// VLAN called "IoT" or "cameras" is a hint about what belongs on it. Usually one
// row; a multi-homed device on two named segments returns both.
//
//	SELECT DISTINCT n.name AS name
//	FROM addresses a
//	         JOIN networks n ON n.id = a.network_id
//	WHERE a.device_id = ?
//	  AND a.is_current = 1
//	  AND n.name IS NOT NULL
//	  AND n.name <> ''
func (q *Queries) DeviceNetworkNames(ctx context.Context, deviceID int64) ([]sql.NullString, error) {
	rows, err := q.query(ctx, q.deviceNetworkNamesStmt, deviceNetworkNames, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var name sql.NullString
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deviceStats = `-- name: DeviceStats :one

SELECT COUNT(*)                                                                       AS total,
       CAST(COALESCE(SUM(CASE WHEN is_ignored = 1 THEN 1 ELSE 0 END), 0) AS INTEGER)  AS ignored,
       CAST(COALESCE(SUM(CASE WHEN last_seen >= ?1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS online,
       CAST(COALESCE(SUM(CASE WHEN first_seen >= ?2 THEN 1 ELSE 0 END), 0) AS INTEGER)   AS discovered
FROM devices
`

type DeviceStatsParams struct {
	OnlineSince dbtype.Time `json:"online_since"`
	NewSince    dbtype.Time `json:"new_since"`
}

type DeviceStatsRow struct {
	Total      int64 `json:"total"`
	Ignored    int64 `json:"ignored"`
	Online     int64 `json:"online"`
	Discovered int64 `json:"discovered"`
}

// The device columns come from a LEFT JOIN because an event outlives the device
// it described: deleting one sets events.device_id to NULL rather than taking
// the record with it.
// The two logs are read with a query builder rather than from here: paging
// them seeks past the row the last page ended on, and the seek is a clause that
// is present or absent. See internal/db/models/inventory_page.go.
//
//	SELECT COUNT(*)                                                                       AS total,
//	       CAST(COALESCE(SUM(CASE WHEN is_ignored = 1 THEN 1 ELSE 0 END), 0) AS INTEGER)  AS ignored,
//	       CAST(COALESCE(SUM(CASE WHEN last_seen >= ?1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS online,
//	       CAST(COALESCE(SUM(CASE WHEN first_seen >= ?2 THEN 1 ELSE 0 END), 0) AS INTEGER)   AS discovered
//	FROM devices
func (q *Queries) DeviceStats(ctx context.Context, arg DeviceStatsParams) (*DeviceStatsRow, error) {
	row := q.queryRow(ctx, q.deviceStatsStmt, deviceStats, arg.OnlineSince, arg.NewSince)
	var i DeviceStatsRow
	err := row.Scan(
		&i.Total,
		&i.Ignored,
		&i.Online,
		&i.Discovered,
	)
	return &i, err
}

const finishScan = `-- name: FinishScan :exec
UPDATE scans
SET status      = ?1,
    error       = ?2,
    found_count = ?3,
    finished_at = ?4
WHERE id = ?5
`

type FinishScanParams struct {
	Status     dbtype.ScanStatus `json:"status"`
	Error      sql.NullString    `json:"error"`
	FoundCount int64             `json:"found_count"`
	FinishedAt dbtype.NullTime   `json:"finished_at"`
	ID         int64             `json:"id"`
}

// FinishScan
//
//	UPDATE scans
//	SET status      = ?1,
//	    error       = ?2,
//	    found_count = ?3,
//	    finished_at = ?4
//	WHERE id = ?5
func (q *Queries) FinishScan(ctx context.Context, arg FinishScanParams) error {
	_, err := q.exec(ctx, q.finishScanStmt, finishScan,
		arg.Status,
		arg.Error,
		arg.FoundCount,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getAddress = `-- name: GetAddress :one
SELECT id, device_id, network_id, ip, is_current, first_seen, last_seen
FROM addresses
WHERE device_id = ?
  AND ip = ?
`

type GetAddressParams struct {
	DeviceID int64       `json:"device_id"`
	IP       dbtype.Addr `json:"ip"`
}

// GetAddress
//
//	SELECT id, device_id, network_id, ip, is_current, first_seen, last_seen
//	FROM addresses
//	WHERE device_id = ?
//	  AND ip = ?
func (q *Queries) GetAddress(ctx context.Context, arg GetAddressParams) (*Address, error) {
	row := q.queryRow(ctx, q.getAddressStmt, getAddress, arg.DeviceID, arg.IP)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.NetworkID,
		&i.IP,
		&i.IsCurrent,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return &i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen, device_class, device_class_confidence
FROM devices
WHERE id = ?
`

// GetDevice
//
//	SELECT id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen, device_class, device_class_confidence
//	FROM devices
//	WHERE id = ?
func (q *Queries) GetDevice(ctx context.Context, id int64) (*Device, error) {
	row := q.queryRow(ctx, q.getDeviceStmt, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MAC,
		&i.IdentitySource,
		&i.IsRandomised,
		&i.Vendor,
		&i.Hostname,
		&i.HostnameSource,
		&i.DeviceType,
		&i.Label,
		&i.Notes,
		&i.GroupName,
		&i.IsIgnored,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DeviceClass,
		&i.DeviceClassConfidence,
	)
	return &i, err
}

const getDeviceByCurrentIP = `-- name: GetDeviceByCurrentIP :one
SELECT d.id, d.mac, d.identity_source, d.is_randomised, d.vendor, d.hostname, d.hostname_source, d.device_type, d.label, d.notes, d.group_name, d.is_ignored, d.first_seen, d.last_seen, d.device_class, d.device_class_confidence
FROM devices d
         JOIN addresses a ON a.device_id = d.id
WHERE a.ip = ?
  AND a.is_current = 1
`

type GetDeviceByCurrentIPRow struct {
	Device Device `json:"device"`
}

// GetDeviceByCurrentIP
//
//	SELECT d.id, d.mac, d.identity_source, d.is_randomised, d.vendor, d.hostname, d.hostname_source, d.device_type, d.label, d.notes, d.group_name, d.is_ignored, d.first_seen, d.last_seen, d.device_class, d.device_class_confidence
//	FROM devices d
//	         JOIN addresses a ON a.device_id = d.id
//	WHERE a.ip = ?
//	  AND a.is_current = 1
func (q *Queries) GetDeviceByCurrentIP(ctx context.Context, ip dbtype.Addr) (*GetDeviceByCurrentIPRow, error) {
	row := q.queryRow(ctx, q.getDeviceByCurrentIPStmt, getDeviceByCurrentIP, ip)
	var i GetDeviceByCurrentIPRow
	err := row.Scan(
		&i.Device.ID,
		&i.Device.MAC,
		&i.Device.IdentitySource,
		&i.Device.IsRandomised,
		&i.Device.Vendor,
		&i.Device.Hostname,
		&i.Device.HostnameSource,
		&i.Device.DeviceType,
		&i.Device.Label,
		&i.Device.Notes,
		&i.Device.GroupName,
		&i.Device.IsIgnored,
		&i.Device.FirstSeen,
		&i.Device.LastSeen,
		&i.Device.DeviceClass,
		&i.Device.DeviceClassConfidence,
	)
	return &i, err
}

const getDeviceByMAC = `-- name: GetDeviceByMAC :one
SELECT id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen, device_class, device_class_confidence
FROM devices
WHERE mac = ?
`

// GetDeviceByMAC
//
//	SELECT id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen, device_class, device_class_confidence
//	FROM devices
//	WHERE mac = ?
func (q *Queries) GetDeviceByMAC(ctx context.Context, mac dbtype.MAC) (*Device, error) {
	row := q.queryRow(ctx, q.getDeviceByMACStmt, getDeviceByMAC, mac)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MAC,
		&i.IdentitySource,
		&i.IsRandomised,
		&i.Vendor,
		&i.Hostname,
		&i.HostnameSource,
		&i.DeviceType,
		&i.Label,
		&i.Notes,
		&i.GroupName,
		&i.IsIgnored,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DeviceClass,
		&i.DeviceClassConfidence,
	)
	return &i, err
}

const identifyDevice = `-- name: IdentifyDevice :exec
UPDATE devices
SET mac             = ?1,
    identity_source = 'MAC',
    is_randomised   = ?2,
    vendor          = ?3
WHERE id = ?4
`

type IdentifyDeviceParams struct {
	MAC          dbtype.MAC     `json:"mac"`
	IsRandomised bool           `json:"is_randomised"`
	Vendor       sql.NullString `json:"vendor"`
	ID           int64          `json:"id"`
}

// IdentifyDevice
//
//	UPDATE devices
//	SET mac             = ?1,
//	    identity_source = 'MAC',
//	    is_randomised   = ?2,
//	    vendor          = ?3
//	WHERE id = ?4
func (q *Queries) IdentifyDevice(ctx context.Context, arg IdentifyDeviceParams) error {
	_, err := q.exec(ctx, q.identifyDeviceStmt, identifyDevice,
		arg.MAC,
		arg.IsRandomised,
		arg.Vendor,
		arg.ID,
	)
	return err
}

const insertAddress = `-- name: InsertAddress :one
INSERT INTO addresses (device_id, network_id, ip, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?)
RETURNING id, device_id, network_id, ip, is_current, first_seen, last_seen
`

type InsertAddressParams struct {
	DeviceID  int64         `json:"device_id"`
	NetworkID sql.NullInt64 `json:"network_id"`
	IP        dbtype.Addr   `json:"ip"`
	FirstSeen dbtype.Time   `json:"first_seen"`
	LastSeen  dbtype.Time   `json:"last_seen"`
}

// InsertAddress
//
//	INSERT INTO addresses (device_id, network_id, ip, first_seen, last_seen)
//	VALUES (?, ?, ?, ?, ?)
//	RETURNING id, device_id, network_id, ip, is_current, first_seen, last_seen
func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) (*Address, error) {
	row := q.queryRow(ctx, q.insertAddressStmt, insertAddress,
		arg.DeviceID,
		arg.NetworkID,
		arg.IP,
		arg.FirstSeen,
		arg.LastSeen,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.NetworkID,
		&i.IP,
		&i.IsCurrent,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return &i, err
}

const latestSuccessfulScanFinishedAt = `-- name: LatestSuccessfulScanFinishedAt :one
SELECT finished_at
FROM scans
WHERE kind = ?
  AND status = 'OK'
  AND finished_at IS NOT NULL
ORDER BY finished_at DESC, id DESC
LIMIT 1
`

// When a scan of this kind last finished with something to show for it, which
// is the anchor the poller schedules from: it waits an interval after the work
// ends, not after it begins, so the two agree on what an interval measures.
//
// Only scans that succeeded count. A failed one gathered nothing and a scan
// whose process died mid-run never wrote a finish at all; crediting either
// would hold the next run off for an interval that produced no data, which is
// the staleness the interval exists to bound.
//
//	SELECT finished_at
//	FROM scans
//	WHERE kind = ?
//	  AND status = 'OK'
//	  AND finished_at IS NOT NULL
//	ORDER BY finished_at DESC, id DESC
//	LIMIT 1
func (q *Queries) LatestSuccessfulScanFinishedAt(ctx context.Context, kind dbtype.ScanKind) (dbtype.NullTime, error) {
	row := q.queryRow(ctx, q.latestSuccessfulScanFinishedAtStmt, latestSuccessfulScanFinishedAt, kind)
	var finished_at dbtype.NullTime
	err := row.Scan(&finished_at)
	return finished_at, err
}

const listDeviceAddresses = `-- name: ListDeviceAddresses :many
SELECT id, device_id, network_id, ip, is_current, first_seen, last_seen
FROM addresses
WHERE device_id = ?
ORDER BY is_current DESC, last_seen DESC
`

// Current addresses first, then the ones the device has released: "where did
// this used to live" is the reason the released rows are kept.
//
//	SELECT id, device_id, network_id, ip, is_current, first_seen, last_seen
//	FROM addresses
//	WHERE device_id = ?
//	ORDER BY is_current DESC, last_seen DESC
func (q *Queries) ListDeviceAddresses(ctx context.Context, deviceID int64) ([]*Address, error) {
	rows, err := q.query(ctx, q.listDeviceAddressesStmt, listDeviceAddresses, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NetworkID,
			&i.IP,
			&i.IsCurrent,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceEvents = `-- name: ListDeviceEvents :many
SELECT id, device_id, scan_id, kind, old_value, new_value, detail, occurred_at
FROM events
WHERE device_id = ?
ORDER BY occurred_at DESC, id DESC
LIMIT ?
`

type ListDeviceEventsParams struct {
	DeviceID sql.NullInt64 `json:"device_id"`
	Limit    int64         `json:"limit"`
}

// Timestamps only resolve to the millisecond, so id breaks the ties within one
// scan, which writes every one of its events on the same stamp.
//
//	SELECT id, device_id, scan_id, kind, old_value, new_value, detail, occurred_at
//	FROM events
//	WHERE device_id = ?
//	ORDER BY occurred_at DESC, id DESC
//	LIMIT ?
func (q *Queries) ListDeviceEvents(ctx context.Context, arg ListDeviceEventsParams) ([]*Event, error) {
	rows, err := q.query(ctx, q.listDeviceEventsStmt, listDeviceEvents, arg.DeviceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.ScanID,
			&i.Kind,
			&i.OldValue,
			&i.NewValue,
			&i.Detail,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceOpenPorts = `-- name: ListDeviceOpenPorts :many
SELECT device_id, port, state, service, first_seen, last_seen, changed_at
FROM device_ports
WHERE device_id = ?
  AND state = 'open'
`

// The ports currently recorded open on a device, for a fresh scan to diff
// itself against. Closed rows are history and left out: a scan no longer seeing
// a port only matters for one we thought was open.
//
//	SELECT device_id, port, state, service, first_seen, last_seen, changed_at
//	FROM device_ports
//	WHERE device_id = ?
//	  AND state = 'open'
func (q *Queries) ListDeviceOpenPorts(ctx context.Context, deviceID int64) ([]*DevicePort, error) {
	rows, err := q.query(ctx, q.listDeviceOpenPortsStmt, listDeviceOpenPorts, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DevicePort
	for rows.Next() {
		var i DevicePort
		if err := rows.Scan(
			&i.DeviceID,
			&i.Port,
			&i.State,
			&i.Service,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicePorts = `-- name: ListDevicePorts :many
SELECT device_id, port, state, service, first_seen, last_seen, changed_at
FROM device_ports
WHERE device_id = ?
ORDER BY state DESC, port
`

// Every port ever seen open on a device, for the device page. Open ones lead --
// 'open' sorts after 'closed', so DESC puts them first -- then by number. A
// closed row is where a service used to answer, which is worth seeing beside
// the ones that still do.
//
//	SELECT device_id, port, state, service, first_seen, last_seen, changed_at
//	FROM device_ports
//	WHERE device_id = ?
//	ORDER BY state DESC, port
func (q *Queries) ListDevicePorts(ctx context.Context, deviceID int64) ([]*DevicePort, error) {
	rows, err := q.query(ctx, q.listDevicePortsStmt, listDevicePorts, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DevicePort
	for rows.Next() {
		var i DevicePort
		if err := rows.Scan(
			&i.DeviceID,
			&i.Port,
			&i.State,
			&i.Service,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceSources = `-- name: ListDeviceSources :many
SELECT ds.device_id, ds.source_id, ds.hostname, ds.hostname_source, ds.detail, ds.first_seen, ds.last_seen, s.name AS source_name, s.kind AS source_kind
FROM device_sources ds
         JOIN sources s ON s.id = ds.source_id
WHERE ds.device_id = ?
ORDER BY ds.last_seen DESC, s.name
`

type ListDeviceSourcesRow struct {
	DeviceSource DeviceSource      `json:"device_source"`
	SourceName   string            `json:"source_name"`
	SourceKind   dbtype.SourceKind `json:"source_kind"`
}

// Election reads this to pick the name the device list shows and searches on;
// the device page reads it to show the claims that lost.
//
//	SELECT ds.device_id, ds.source_id, ds.hostname, ds.hostname_source, ds.detail, ds.first_seen, ds.last_seen, s.name AS source_name, s.kind AS source_kind
//	FROM device_sources ds
//	         JOIN sources s ON s.id = ds.source_id
//	WHERE ds.device_id = ?
//	ORDER BY ds.last_seen DESC, s.name
func (q *Queries) ListDeviceSources(ctx context.Context, deviceID int64) ([]*ListDeviceSourcesRow, error) {
	rows, err := q.query(ctx, q.listDeviceSourcesStmt, listDeviceSources, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDeviceSourcesRow
	for rows.Next() {
		var i ListDeviceSourcesRow
		if err := rows.Scan(
			&i.DeviceSource.DeviceID,
			&i.DeviceSource.SourceID,
			&i.DeviceSource.Hostname,
			&i.DeviceSource.HostnameSource,
			&i.DeviceSource.Detail,
			&i.DeviceSource.FirstSeen,
			&i.DeviceSource.LastSeen,
			&i.SourceName,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many

SELECT d.id, d.mac, d.identity_source, d.is_randomised, d.vendor, d.hostname, d.hostname_source, d.device_type, d.label, d.notes, d.group_name, d.is_ignored, d.first_seen, d.last_seen, d.device_class, d.device_class_confidence,
       CAST(COALESCE((SELECT GROUP_CONCAT(a.ip, ' ')
                      FROM addresses a
                      WHERE a.device_id = d.id
                        AND a.is_current = 1), '') AS TEXT) AS current_ips,
       CAST(COALESCE((SELECT GROUP_CONCAT(p.port, ' ')
                      FROM device_ports p
                      WHERE p.device_id = d.id
                        AND p.state = 'open'), '') AS TEXT) AS open_ports,
       CAST(COALESCE((SELECT GROUP_CONCAT(DISTINCT a.network_id)
                      FROM addresses a
                      WHERE a.device_id = d.id
                        AND a.is_current = 1
                        AND a.network_id IS NOT NULL), '') AS TEXT) AS network_ids
FROM devices d
WHERE (d.is_ignored = 0 OR d.is_ignored = ?1)
  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
  AND (CAST(?3 AS INTEGER) IS NULL
    OR EXISTS (SELECT 1
               FROM addresses a
               WHERE a.device_id = d.id
                 AND a.is_current = 1
                 AND a.network_id = CAST(?3 AS INTEGER)))
  AND (CAST(?4 AS TEXT) IS NULL
    OR d.label LIKE '%' || CAST(?4 AS TEXT) || '%'
    OR d.hostname LIKE '%' || CAST(?4 AS TEXT) || '%'
    OR d.vendor LIKE '%' || CAST(?4 AS TEXT) || '%'
    OR d.mac LIKE '%' || CAST(?4 AS TEXT) || '%'
    OR EXISTS (SELECT 1
               FROM addresses a
               WHERE a.device_id = d.id
                 AND a.is_current = 1
                 AND a.ip LIKE '%' || CAST(?4 AS TEXT) || '%'))
ORDER BY d.last_seen DESC
`

type ListDevicesParams struct {
	IncludeIgnored bool           `json:"include_ignored"`
	GroupName      sql.NullString `json:"group_name"`
	NetworkID      sql.NullInt64  `json:"network_id"`
	Q              sql.NullString `json:"q"`
}

type ListDevicesRow struct {
	Device     Device `json:"device"`
	CurrentIps string `json:"current_ips"`
	OpenPorts  string `json:"open_ports"`
	NetworkIds string `json:"network_ids"`
}

// Reads.
// The current addresses come back on the device's own row rather than through a
// join, so one query answers the list. The open ports and the ids of the
// networks those addresses sit on ride along the same way, so a list can say
// what a device exposes and where it lives without a query per row.
// GROUP_CONCAT has no ordering worth relying on and the address column is TEXT,
// which sorts 192.0.2.9 after 192.0.2.100, so the caller splits and orders
// what it needs ordered.
//
// is_ignored compares against the argument rather than testing a flag: passing
// false leaves the clause admitting only unignored rows, and passing true makes
// the second half admit the rest.
//
//	SELECT d.id, d.mac, d.identity_source, d.is_randomised, d.vendor, d.hostname, d.hostname_source, d.device_type, d.label, d.notes, d.group_name, d.is_ignored, d.first_seen, d.last_seen, d.device_class, d.device_class_confidence,
//	       CAST(COALESCE((SELECT GROUP_CONCAT(a.ip, ' ')
//	                      FROM addresses a
//	                      WHERE a.device_id = d.id
//	                        AND a.is_current = 1), '') AS TEXT) AS current_ips,
//	       CAST(COALESCE((SELECT GROUP_CONCAT(p.port, ' ')
//	                      FROM device_ports p
//	                      WHERE p.device_id = d.id
//	                        AND p.state = 'open'), '') AS TEXT) AS open_ports,
//	       CAST(COALESCE((SELECT GROUP_CONCAT(DISTINCT a.network_id)
//	                      FROM addresses a
//	                      WHERE a.device_id = d.id
//	                        AND a.is_current = 1
//	                        AND a.network_id IS NOT NULL), '') AS TEXT) AS network_ids
//	FROM devices d
//	WHERE (d.is_ignored = 0 OR d.is_ignored = ?1)
//	  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
//	  AND (CAST(?3 AS INTEGER) IS NULL
//	    OR EXISTS (SELECT 1
//	               FROM addresses a
//	               WHERE a.device_id = d.id
//	                 AND a.is_current = 1
//	                 AND a.network_id = CAST(?3 AS INTEGER)))
//	  AND (CAST(?4 AS TEXT) IS NULL
//	    OR d.label LIKE '%' || CAST(?4 AS TEXT) || '%'
//	    OR d.hostname LIKE '%' || CAST(?4 AS TEXT) || '%'
//	    OR d.vendor LIKE '%' || CAST(?4 AS TEXT) || '%'
//	    OR d.mac LIKE '%' || CAST(?4 AS TEXT) || '%'
//	    OR EXISTS (SELECT 1
//	               FROM addresses a
//	               WHERE a.device_id = d.id
//	                 AND a.is_current = 1
//	                 AND a.ip LIKE '%' || CAST(?4 AS TEXT) || '%'))
//	ORDER BY d.last_seen DESC
func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]*ListDevicesRow, error) {
	rows, err := q.query(ctx, q.listDevicesStmt, listDevices,
		arg.IncludeIgnored,
		arg.GroupName,
		arg.NetworkID,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDevicesRow
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.MAC,
			&i.Device.IdentitySource,
			&i.Device.IsRandomised,
			&i.Device.Vendor,
			&i.Device.Hostname,
			&i.Device.HostnameSource,
			&i.Device.DeviceType,
			&i.Device.Label,
			&i.Device.Notes,
			&i.Device.GroupName,
			&i.Device.IsIgnored,
			&i.Device.FirstSeen,
			&i.Device.LastSeen,
			&i.Device.DeviceClass,
			&i.Device.DeviceClassConfidence,
			&i.CurrentIps,
			&i.OpenPorts,
			&i.NetworkIds,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT DISTINCT CAST(group_name AS TEXT) AS group_name
FROM devices
WHERE group_name IS NOT NULL
  AND group_name <> ''
ORDER BY group_name
`

// ListGroups
//
//	SELECT DISTINCT CAST(group_name AS TEXT) AS group_name
//	FROM devices
//	WHERE group_name IS NOT NULL
//	  AND group_name <> ''
//	ORDER BY group_name
func (q *Queries) ListGroups(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listGroupsStmt, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworks = `-- name: ListNetworks :many
SELECT n.id,
       n.cidr,
       n.name,
       n.vlan_id,
       CAST(COUNT(DISTINCT d.id) AS INTEGER) AS total,
       CAST(COUNT(DISTINCT CASE
                               WHEN d.last_seen >= ?1 THEN d.id
           END) AS INTEGER)                  AS online
FROM networks n
         LEFT JOIN addresses a ON a.network_id = n.id AND a.is_current = 1
         LEFT JOIN devices d ON d.id = a.device_id AND d.is_ignored = 0
GROUP BY n.id
ORDER BY n.cidr
`

type ListNetworksRow struct {
	ID     int64          `json:"id"`
	Cidr   dbtype.Prefix  `json:"cidr"`
	Name   sql.NullString `json:"name"`
	VlanID sql.NullInt64  `json:"vlan_id"`
	Total  int64          `json:"total"`
	Online int64          `json:"online"`
}

// Every network a sweep has recorded, with how many devices hold an address on
// it now. A device counts on each network it currently holds an address on:
// the overview asks what is on a prefix, not how the inventory divides into
// disjoint parts. A network no sweep has found anything on still lists, at
// zero -- that it is quiet is the fact worth showing.
//
// Ignored devices are left out, so the count agrees with the list the network
// page draws below it: the join drops them and the counts are over d.id rather
// than a.device_id, which would still be set for an address whose device the
// join excluded.
//
//	SELECT n.id,
//	       n.cidr,
//	       n.name,
//	       n.vlan_id,
//	       CAST(COUNT(DISTINCT d.id) AS INTEGER) AS total,
//	       CAST(COUNT(DISTINCT CASE
//	                               WHEN d.last_seen >= ?1 THEN d.id
//	           END) AS INTEGER)                  AS online
//	FROM networks n
//	         LEFT JOIN addresses a ON a.network_id = n.id AND a.is_current = 1
//	         LEFT JOIN devices d ON d.id = a.device_id AND d.is_ignored = 0
//	GROUP BY n.id
//	ORDER BY n.cidr
func (q *Queries) ListNetworks(ctx context.Context, onlineSince dbtype.Time) ([]*ListNetworksRow, error) {
	rows, err := q.query(ctx, q.listNetworksStmt, listNetworks, onlineSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListNetworksRow
	for rows.Next() {
		var i ListNetworksRow
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Name,
			&i.VlanID,
			&i.Total,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAddresses = `-- name: MoveAddresses :exec
UPDATE OR IGNORE addresses
SET device_id = ?1
WHERE device_id = ?2
`

type MoveAddressesParams struct {
	IntoID int64 `json:"into_id"`
	FromID int64 `json:"from_id"`
}

// Rows the surviving device already holds for the same address are left behind
// and go with the folded device when it is deleted.
//
//	UPDATE OR IGNORE addresses
//	SET device_id = ?1
//	WHERE device_id = ?2
func (q *Queries) MoveAddresses(ctx context.Context, arg MoveAddressesParams) error {
	_, err := q.exec(ctx, q.moveAddressesStmt, moveAddresses, arg.IntoID, arg.FromID)
	return err
}

const moveDeviceSources = `-- name: MoveDeviceSources :exec
INSERT INTO device_sources (device_id, source_id, hostname, hostname_source, detail, first_seen, last_seen)
SELECT ?1, ghost.source_id, ghost.hostname, ghost.hostname_source, ghost.detail,
       ghost.first_seen, ghost.last_seen
FROM device_sources ghost
WHERE ghost.device_id = ?2
ON CONFLICT (device_id, source_id)
    DO UPDATE SET hostname        = IIF(excluded.last_seen > device_sources.last_seen,
                                        excluded.hostname, device_sources.hostname),
                  hostname_source = IIF(excluded.last_seen > device_sources.last_seen,
                                        excluded.hostname_source, device_sources.hostname_source),
                  detail          = IIF(excluded.last_seen > device_sources.last_seen,
                                        excluded.detail, device_sources.detail),
                  first_seen      = MIN(device_sources.first_seen, excluded.first_seen),
                  last_seen       = MAX(device_sources.last_seen, excluded.last_seen)
`

type MoveDeviceSourcesParams struct {
	IntoID int64 `json:"into_id"`
	FromID int64 `json:"from_id"`
}

// Claims follow the device on a fold. A source that filed against both rows
// collides on the primary key, and the claim that survives takes the newer
// reading's name with the outer bounds of both sightings.
//
//	INSERT INTO device_sources (device_id, source_id, hostname, hostname_source, detail, first_seen, last_seen)
//	SELECT ?1, ghost.source_id, ghost.hostname, ghost.hostname_source, ghost.detail,
//	       ghost.first_seen, ghost.last_seen
//	FROM device_sources ghost
//	WHERE ghost.device_id = ?2
//	ON CONFLICT (device_id, source_id)
//	    DO UPDATE SET hostname        = IIF(excluded.last_seen > device_sources.last_seen,
//	                                        excluded.hostname, device_sources.hostname),
//	                  hostname_source = IIF(excluded.last_seen > device_sources.last_seen,
//	                                        excluded.hostname_source, device_sources.hostname_source),
//	                  detail          = IIF(excluded.last_seen > device_sources.last_seen,
//	                                        excluded.detail, device_sources.detail),
//	                  first_seen      = MIN(device_sources.first_seen, excluded.first_seen),
//	                  last_seen       = MAX(device_sources.last_seen, excluded.last_seen)
func (q *Queries) MoveDeviceSources(ctx context.Context, arg MoveDeviceSourcesParams) error {
	_, err := q.exec(ctx, q.moveDeviceSourcesStmt, moveDeviceSources, arg.IntoID, arg.FromID)
	return err
}

const moveEvents = `-- name: MoveEvents :exec
UPDATE events
SET device_id = ?1
WHERE device_id = ?2
`

type MoveEventsParams struct {
	IntoID sql.NullInt64 `json:"into_id"`
	FromID sql.NullInt64 `json:"from_id"`
}

// MoveEvents
//
//	UPDATE events
//	SET device_id = ?1
//	WHERE device_id = ?2
func (q *Queries) MoveEvents(ctx context.Context, arg MoveEventsParams) error {
	_, err := q.exec(ctx, q.moveEventsStmt, moveEvents, arg.IntoID, arg.FromID)
	return err
}

const refreshAddress = `-- name: RefreshAddress :exec
UPDATE addresses
SET is_current = 1,
    network_id = COALESCE(?1, network_id),
    last_seen  = ?2
WHERE id = ?3
`

type RefreshAddressParams struct {
	NetworkID sql.NullInt64 `json:"network_id"`
	LastSeen  dbtype.Time   `json:"last_seen"`
	ID        int64         `json:"id"`
}

// COALESCE, not assignment: a source that cannot say which network an address
// is on must leave the one a sweep established rather than erase it.
//
//	UPDATE addresses
//	SET is_current = 1,
//	    network_id = COALESCE(?1, network_id),
//	    last_seen  = ?2
//	WHERE id = ?3
func (q *Queries) RefreshAddress(ctx context.Context, arg RefreshAddressParams) error {
	_, err := q.exec(ctx, q.refreshAddressStmt, refreshAddress, arg.NetworkID, arg.LastSeen, arg.ID)
	return err
}

const releaseAddress = `-- name: ReleaseAddress :exec
UPDATE addresses
SET is_current = 0
WHERE ip = ?1
  AND is_current = 1
  AND device_id <> ?2
`

type ReleaseAddressParams struct {
	IP       dbtype.Addr `json:"ip"`
	DeviceID int64       `json:"device_id"`
}

// Only one device may hold an address as current, so the previous holder is
// released before the new claim rather than colliding with the partial index.
//
//	UPDATE addresses
//	SET is_current = 0
//	WHERE ip = ?1
//	  AND is_current = 1
//	  AND device_id <> ?2
func (q *Queries) ReleaseAddress(ctx context.Context, arg ReleaseAddressParams) error {
	_, err := q.exec(ctx, q.releaseAddressStmt, releaseAddress, arg.IP, arg.DeviceID)
	return err
}

const retireAddress = `-- name: RetireAddress :exec
UPDATE addresses
SET is_current = 0
WHERE id = ?
`

// Drop an address a device has moved off: the sweep answered for it elsewhere
// in the prefix while this one stayed silent past the grace window. The row
// stays so the history does, and last_seen keeps its last real sighting.
//
//	UPDATE addresses
//	SET is_current = 0
//	WHERE id = ?
func (q *Queries) RetireAddress(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.retireAddressStmt, retireAddress, id)
	return err
}

const setDeviceClass = `-- name: SetDeviceClass :exec

UPDATE devices
SET device_class            = ?1,
    device_class_confidence = ?2
WHERE id = ?3
`

type SetDeviceClassParams struct {
	DeviceClass           sql.NullString `json:"device_class"`
	DeviceClassConfidence sql.NullString `json:"device_class_confidence"`
	ID                    int64          `json:"id"`
}

// Classification.
// The classifier's guess and its confidence, kept apart from the user's own
// device_type so an override is never overwritten by a scan.
//
//	UPDATE devices
//	SET device_class            = ?1,
//	    device_class_confidence = ?2
//	WHERE id = ?3
func (q *Queries) SetDeviceClass(ctx context.Context, arg SetDeviceClassParams) error {
	_, err := q.exec(ctx, q.setDeviceClassStmt, setDeviceClass, arg.DeviceClass, arg.DeviceClassConfidence, arg.ID)
	return err
}

const setDeviceHostname = `-- name: SetDeviceHostname :exec
UPDATE devices
SET hostname        = ?1,
    hostname_source = ?2
WHERE id = ?3
`

type SetDeviceHostnameParams struct {
	Hostname       sql.NullString        `json:"hostname"`
	HostnameSource dbtype.HostnameSource `json:"hostname_source"`
	ID             int64                 `json:"id"`
}

// SetDeviceHostname
//
//	UPDATE devices
//	SET hostname        = ?1,
//	    hostname_source = ?2
//	WHERE id = ?3
func (q *Queries) SetDeviceHostname(ctx context.Context, arg SetDeviceHostnameParams) error {
	_, err := q.exec(ctx, q.setDeviceHostnameStmt, setDeviceHostname, arg.Hostname, arg.HostnameSource, arg.ID)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices
SET last_seen = ?1
WHERE id = ?2
`

type TouchDeviceParams struct {
	LastSeen dbtype.Time `json:"last_seen"`
	ID       int64       `json:"id"`
}

// TouchDevice
//
//	UPDATE devices
//	SET last_seen = ?1
//	WHERE id = ?2
func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.exec(ctx, q.touchDeviceStmt, touchDevice, arg.LastSeen, arg.ID)
	return err
}

const updateDeviceCuration = `-- name: UpdateDeviceCuration :one

UPDATE devices
SET label       = ?1,
    notes       = ?2,
    group_name  = ?3,
    device_type = ?4,
    is_ignored  = ?5
WHERE id = ?6
RETURNING id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen, device_class, device_class_confidence
`

type UpdateDeviceCurationParams struct {
	Label      sql.NullString `json:"label"`
	Notes      sql.NullString `json:"notes"`
	GroupName  sql.NullString `json:"group_name"`
	DeviceType sql.NullString `json:"device_type"`
	IsIgnored  bool           `json:"is_ignored"`
	ID         int64          `json:"id"`
}

// Writes.
// Every user-owned column is set rather than merged: the form submits all of
// them, so an omitted one means cleared, not unchanged.
//
//	UPDATE devices
//	SET label       = ?1,
//	    notes       = ?2,
//	    group_name  = ?3,
//	    device_type = ?4,
//	    is_ignored  = ?5
//	WHERE id = ?6
//	RETURNING id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen, device_class, device_class_confidence
func (q *Queries) UpdateDeviceCuration(ctx context.Context, arg UpdateDeviceCurationParams) (*Device, error) {
	row := q.queryRow(ctx, q.updateDeviceCurationStmt, updateDeviceCuration,
		arg.Label,
		arg.Notes,
		arg.GroupName,
		arg.DeviceType,
		arg.IsIgnored,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.MAC,
		&i.IdentitySource,
		&i.IsRandomised,
		&i.Vendor,
		&i.Hostname,
		&i.HostnameSource,
		&i.DeviceType,
		&i.Label,
		&i.Notes,
		&i.GroupName,
		&i.IsIgnored,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DeviceClass,
		&i.DeviceClassConfidence,
	)
	return &i, err
}

const upsertDeviceSource = `-- name: UpsertDeviceSource :exec
INSERT INTO device_sources (device_id, source_id, hostname, hostname_source, detail, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (device_id, source_id)
    DO UPDATE SET hostname        = CASE
                                        WHEN excluded.hostname IS NOT NULL THEN excluded.hostname
                                        ELSE device_sources.hostname END,
                  hostname_source = CASE
                                        WHEN excluded.hostname IS NOT NULL THEN excluded.hostname_source
                                        ELSE device_sources.hostname_source END,
                  detail          = excluded.detail,
                  last_seen       = excluded.last_seen
`

type UpsertDeviceSourceParams struct {
	DeviceID       int64                 `json:"device_id"`
	SourceID       int64                 `json:"source_id"`
	Hostname       sql.NullString        `json:"hostname"`
	HostnameSource dbtype.HostnameSource `json:"hostname_source"`
	Detail         sql.NullString        `json:"detail"`
	FirstSeen      dbtype.Time           `json:"first_seen"`
	LastSeen       dbtype.Time           `json:"last_seen"`
}

// Upserted rather than replaced, so first_seen survives every later reading.
//
// A name only moves when this source offers one: an empty reading leaves the
// last name it knew in place rather than clearing it. A sweep resolves a name
// per address, so a multi-homed host with a PTR on one interface and none on
// another would otherwise thrash its name every pass; and a device that stops
// answering has not been renamed, it has gone quiet. last_seen still ages, so
// how stale the kept name is stays visible. A different non-empty name, from
// this source or a higher one, still replaces it.
//
//	INSERT INTO device_sources (device_id, source_id, hostname, hostname_source, detail, first_seen, last_seen)
//	VALUES (?, ?, ?, ?, ?, ?, ?)
//	ON CONFLICT (device_id, source_id)
//	    DO UPDATE SET hostname        = CASE
//	                                        WHEN excluded.hostname IS NOT NULL THEN excluded.hostname
//	                                        ELSE device_sources.hostname END,
//	                  hostname_source = CASE
//	                                        WHEN excluded.hostname IS NOT NULL THEN excluded.hostname_source
//	                                        ELSE device_sources.hostname_source END,
//	                  detail          = excluded.detail,
//	                  last_seen       = excluded.last_seen
func (q *Queries) UpsertDeviceSource(ctx context.Context, arg UpsertDeviceSourceParams) error {
	_, err := q.exec(ctx, q.upsertDeviceSourceStmt, upsertDeviceSource,
		arg.DeviceID,
		arg.SourceID,
		arg.Hostname,
		arg.HostnameSource,
		arg.Detail,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}

const upsertNetwork = `-- name: UpsertNetwork :one
INSERT INTO networks (cidr, created_at)
VALUES (?, ?)
ON CONFLICT (cidr) DO UPDATE SET cidr = excluded.cidr
RETURNING id, cidr, name, vlan_id, created_at
`

type UpsertNetworkParams struct {
	Cidr      dbtype.Prefix `json:"cidr"`
	CreatedAt dbtype.Time   `json:"created_at"`
}

// UpsertNetwork
//
//	INSERT INTO networks (cidr, created_at)
//	VALUES (?, ?)
//	ON CONFLICT (cidr) DO UPDATE SET cidr = excluded.cidr
//	RETURNING id, cidr, name, vlan_id, created_at
func (q *Queries) UpsertNetwork(ctx context.Context, arg UpsertNetworkParams) (*Network, error) {
	row := q.queryRow(ctx, q.upsertNetworkStmt, upsertNetwork, arg.Cidr, arg.CreatedAt)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Name,
		&i.VlanID,
		&i.CreatedAt,
	)
	return &i, err
}

const upsertNetworkIdentity = `-- name: UpsertNetworkIdentity :exec
INSERT INTO networks (cidr, name, vlan_id, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (cidr) DO UPDATE SET name    = excluded.name,
                                 vlan_id = excluded.vlan_id
`

type UpsertNetworkIdentityParams struct {
	Cidr      dbtype.Prefix  `json:"cidr"`
	Name      sql.NullString `json:"name"`
	VlanID    sql.NullInt64  `json:"vlan_id"`
	CreatedAt dbtype.Time    `json:"created_at"`
}

// What a source says a segment is. name and vlan_id are assigned rather than
// coalesced: a VLAN renamed on the router is renamed here, and one that loses
// its tag loses it here too.
//
//	INSERT INTO networks (cidr, name, vlan_id, created_at)
//	VALUES (?, ?, ?, ?)
//	ON CONFLICT (cidr) DO UPDATE SET name    = excluded.name,
//	                                 vlan_id = excluded.vlan_id
func (q *Queries) UpsertNetworkIdentity(ctx context.Context, arg UpsertNetworkIdentityParams) error {
	_, err := q.exec(ctx, q.upsertNetworkIdentityStmt, upsertNetworkIdentity,
		arg.Cidr,
		arg.Name,
		arg.VlanID,
		arg.CreatedAt,
	)
	return err
}

const upsertOpenPort = `-- name: UpsertOpenPort :exec
INSERT INTO device_ports (device_id, port, state, service, first_seen, last_seen, changed_at)
VALUES (?1, ?2, 'open', ?3,
        ?4, ?4, ?4)
ON CONFLICT (device_id, port)
    DO UPDATE SET state      = 'open',
                  service    = excluded.service,
                  last_seen  = excluded.last_seen,
                  changed_at = IIF(device_ports.state <> 'open',
                                   excluded.changed_at, device_ports.changed_at)
`

type UpsertOpenPortParams struct {
	DeviceID int64          `json:"device_id"`
	Port     int64          `json:"port"`
	Service  sql.NullString `json:"service"`
	SeenAt   dbtype.Time    `json:"seen_at"`
}

// A port answered. A new row, or a closed one coming back: first_seen holds the
// first time it was ever open and changed_at moves only on a real transition,
// so "open since" and "state changed" stay distinct.
//
//	INSERT INTO device_ports (device_id, port, state, service, first_seen, last_seen, changed_at)
//	VALUES (?1, ?2, 'open', ?3,
//	        ?4, ?4, ?4)
//	ON CONFLICT (device_id, port)
//	    DO UPDATE SET state      = 'open',
//	                  service    = excluded.service,
//	                  last_seen  = excluded.last_seen,
//	                  changed_at = IIF(device_ports.state <> 'open',
//	                                   excluded.changed_at, device_ports.changed_at)
func (q *Queries) UpsertOpenPort(ctx context.Context, arg UpsertOpenPortParams) error {
	_, err := q.exec(ctx, q.upsertOpenPortStmt, upsertOpenPort,
		arg.DeviceID,
		arg.Port,
		arg.Service,
		arg.SeenAt,
	)
	return err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources (kind, name, created_at)
VALUES (?, ?, ?)
ON CONFLICT (name) DO UPDATE SET kind = excluded.kind
RETURNING id, kind, name, created_at
`

type UpsertSourceParams struct {
	Kind      dbtype.SourceKind `json:"kind"`
	Name      string            `json:"name"`
	CreatedAt dbtype.Time       `json:"created_at"`
}

// UpsertSource
//
//	INSERT INTO sources (kind, name, created_at)
//	VALUES (?, ?, ?)
//	ON CONFLICT (name) DO UPDATE SET kind = excluded.kind
//	RETURNING id, kind, name, created_at
func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (*Source, error) {
	row := q.queryRow(ctx, q.upsertSourceStmt, upsertSource, arg.Kind, arg.Name, arg.CreatedAt)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
	)
	return &i, err
}
