// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package models

import (
	"context"
	"database/sql"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const adoptCuration = `-- name: AdoptCuration :exec
UPDATE devices
SET label      = COALESCE(label, ?1),
    notes      = COALESCE(notes, ?2),
    group_name = COALESCE(group_name, ?3),
    first_seen = ?4
WHERE id = ?5
`

type AdoptCurationParams struct {
	FoldedLabel     sql.NullString `json:"folded_label"`
	FoldedNotes     sql.NullString `json:"folded_notes"`
	FoldedGroupName sql.NullString `json:"folded_group_name"`
	FirstSeen       dbtype.Time    `json:"first_seen"`
	ID              int64          `json:"id"`
}

// A device folded into another may carry a label the user set before its MAC
// was known, and the earlier of the two first_seen values is the true one.
func (q *Queries) AdoptCuration(ctx context.Context, arg AdoptCurationParams) error {
	_, err := q.exec(ctx, q.adoptCurationStmt, adoptCuration,
		arg.FoldedLabel,
		arg.FoldedNotes,
		arg.FoldedGroupName,
		arg.FirstSeen,
		arg.ID,
	)
	return err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (mac, identity_source, is_randomised, vendor, hostname, hostname_source,
                     first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen
`

type CreateDeviceParams struct {
	Mac            dbtype.MAC            `json:"mac"`
	IdentitySource dbtype.IdentitySource `json:"identity_source"`
	IsRandomised   bool                  `json:"is_randomised"`
	Vendor         sql.NullString        `json:"vendor"`
	Hostname       sql.NullString        `json:"hostname"`
	HostnameSource dbtype.HostnameSource `json:"hostname_source"`
	FirstSeen      dbtype.Time           `json:"first_seen"`
	LastSeen       dbtype.Time           `json:"last_seen"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.queryRow(ctx, q.createDeviceStmt, createDevice,
		arg.Mac,
		arg.IdentitySource,
		arg.IsRandomised,
		arg.Vendor,
		arg.Hostname,
		arg.HostnameSource,
		arg.FirstSeen,
		arg.LastSeen,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Mac,
		&i.IdentitySource,
		&i.IsRandomised,
		&i.Vendor,
		&i.Hostname,
		&i.HostnameSource,
		&i.DeviceType,
		&i.Label,
		&i.Notes,
		&i.GroupName,
		&i.IsIgnored,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (device_id, scan_id, kind, old_value, new_value, detail, occurred_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	DeviceID   sql.NullInt64    `json:"device_id"`
	ScanID     sql.NullInt64    `json:"scan_id"`
	Kind       dbtype.EventKind `json:"kind"`
	OldValue   sql.NullString   `json:"old_value"`
	NewValue   sql.NullString   `json:"new_value"`
	Detail     sql.NullString   `json:"detail"`
	OccurredAt dbtype.Time      `json:"occurred_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.exec(ctx, q.createEventStmt, createEvent,
		arg.DeviceID,
		arg.ScanID,
		arg.Kind,
		arg.OldValue,
		arg.NewValue,
		arg.Detail,
		arg.OccurredAt,
	)
	return err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (source_id, kind, network_id, started_at)
VALUES (?, ?, ?, ?)
RETURNING id, source_id, kind, network_id, status, error, found_count, started_at, finished_at
`

type CreateScanParams struct {
	SourceID  int64           `json:"source_id"`
	Kind      dbtype.ScanKind `json:"kind"`
	NetworkID sql.NullInt64   `json:"network_id"`
	StartedAt dbtype.Time     `json:"started_at"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.queryRow(ctx, q.createScanStmt, createScan,
		arg.SourceID,
		arg.Kind,
		arg.NetworkID,
		arg.StartedAt,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Kind,
		&i.NetworkID,
		&i.Status,
		&i.Error,
		&i.FoundCount,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE
FROM devices
WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteDeviceStmt, deleteDevice, id)
	return err
}

const deviceStats = `-- name: DeviceStats :one
SELECT COUNT(*)                                                                       AS total,
       CAST(COALESCE(SUM(CASE WHEN is_ignored = 1 THEN 1 ELSE 0 END), 0) AS INTEGER)  AS ignored,
       CAST(COALESCE(SUM(CASE WHEN last_seen >= ?1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS online,
       CAST(COALESCE(SUM(CASE WHEN first_seen >= ?2 THEN 1 ELSE 0 END), 0) AS INTEGER)   AS discovered
FROM devices
`

type DeviceStatsParams struct {
	OnlineSince dbtype.Time `json:"online_since"`
	NewSince    dbtype.Time `json:"new_since"`
}

type DeviceStatsRow struct {
	Total      int64 `json:"total"`
	Ignored    int64 `json:"ignored"`
	Online     int64 `json:"online"`
	Discovered int64 `json:"discovered"`
}

func (q *Queries) DeviceStats(ctx context.Context, arg DeviceStatsParams) (DeviceStatsRow, error) {
	row := q.queryRow(ctx, q.deviceStatsStmt, deviceStats, arg.OnlineSince, arg.NewSince)
	var i DeviceStatsRow
	err := row.Scan(
		&i.Total,
		&i.Ignored,
		&i.Online,
		&i.Discovered,
	)
	return i, err
}

const finishScan = `-- name: FinishScan :exec
UPDATE scans
SET status      = ?1,
    error       = ?2,
    found_count = ?3,
    finished_at = ?4
WHERE id = ?5
`

type FinishScanParams struct {
	Status     dbtype.ScanStatus `json:"status"`
	Error      sql.NullString    `json:"error"`
	FoundCount int64             `json:"found_count"`
	FinishedAt dbtype.NullTime   `json:"finished_at"`
	ID         int64             `json:"id"`
}

func (q *Queries) FinishScan(ctx context.Context, arg FinishScanParams) error {
	_, err := q.exec(ctx, q.finishScanStmt, finishScan,
		arg.Status,
		arg.Error,
		arg.FoundCount,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getAddress = `-- name: GetAddress :one
SELECT id, device_id, network_id, ip, is_current, first_seen, last_seen
FROM addresses
WHERE device_id = ?
  AND ip = ?
`

type GetAddressParams struct {
	DeviceID int64       `json:"device_id"`
	Ip       dbtype.Addr `json:"ip"`
}

func (q *Queries) GetAddress(ctx context.Context, arg GetAddressParams) (Address, error) {
	row := q.queryRow(ctx, q.getAddressStmt, getAddress, arg.DeviceID, arg.Ip)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.NetworkID,
		&i.Ip,
		&i.IsCurrent,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen
FROM devices
WHERE id = ?
`

func (q *Queries) GetDevice(ctx context.Context, id int64) (Device, error) {
	row := q.queryRow(ctx, q.getDeviceStmt, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Mac,
		&i.IdentitySource,
		&i.IsRandomised,
		&i.Vendor,
		&i.Hostname,
		&i.HostnameSource,
		&i.DeviceType,
		&i.Label,
		&i.Notes,
		&i.GroupName,
		&i.IsIgnored,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const getDeviceByCurrentIP = `-- name: GetDeviceByCurrentIP :one
SELECT d.id, d.mac, d.identity_source, d.is_randomised, d.vendor, d.hostname, d.hostname_source, d.device_type, d.label, d.notes, d.group_name, d.is_ignored, d.first_seen, d.last_seen
FROM devices d
         JOIN addresses a ON a.device_id = d.id
WHERE a.ip = ?
  AND a.is_current = 1
`

type GetDeviceByCurrentIPRow struct {
	Device Device `json:"device"`
}

func (q *Queries) GetDeviceByCurrentIP(ctx context.Context, ip dbtype.Addr) (GetDeviceByCurrentIPRow, error) {
	row := q.queryRow(ctx, q.getDeviceByCurrentIPStmt, getDeviceByCurrentIP, ip)
	var i GetDeviceByCurrentIPRow
	err := row.Scan(
		&i.Device.ID,
		&i.Device.Mac,
		&i.Device.IdentitySource,
		&i.Device.IsRandomised,
		&i.Device.Vendor,
		&i.Device.Hostname,
		&i.Device.HostnameSource,
		&i.Device.DeviceType,
		&i.Device.Label,
		&i.Device.Notes,
		&i.Device.GroupName,
		&i.Device.IsIgnored,
		&i.Device.FirstSeen,
		&i.Device.LastSeen,
	)
	return i, err
}

const getDeviceByMAC = `-- name: GetDeviceByMAC :one
SELECT id, mac, identity_source, is_randomised, vendor, hostname, hostname_source, device_type, label, notes, group_name, is_ignored, first_seen, last_seen
FROM devices
WHERE mac = ?
`

func (q *Queries) GetDeviceByMAC(ctx context.Context, mac dbtype.MAC) (Device, error) {
	row := q.queryRow(ctx, q.getDeviceByMACStmt, getDeviceByMAC, mac)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Mac,
		&i.IdentitySource,
		&i.IsRandomised,
		&i.Vendor,
		&i.Hostname,
		&i.HostnameSource,
		&i.DeviceType,
		&i.Label,
		&i.Notes,
		&i.GroupName,
		&i.IsIgnored,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const identifyDevice = `-- name: IdentifyDevice :exec
UPDATE devices
SET mac             = ?1,
    identity_source = 'MAC',
    is_randomised   = ?2,
    vendor          = ?3
WHERE id = ?4
`

type IdentifyDeviceParams struct {
	Mac          dbtype.MAC     `json:"mac"`
	IsRandomised bool           `json:"is_randomised"`
	Vendor       sql.NullString `json:"vendor"`
	ID           int64          `json:"id"`
}

func (q *Queries) IdentifyDevice(ctx context.Context, arg IdentifyDeviceParams) error {
	_, err := q.exec(ctx, q.identifyDeviceStmt, identifyDevice,
		arg.Mac,
		arg.IsRandomised,
		arg.Vendor,
		arg.ID,
	)
	return err
}

const insertAddress = `-- name: InsertAddress :one
INSERT INTO addresses (device_id, network_id, ip, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?)
RETURNING id, device_id, network_id, ip, is_current, first_seen, last_seen
`

type InsertAddressParams struct {
	DeviceID  int64         `json:"device_id"`
	NetworkID sql.NullInt64 `json:"network_id"`
	Ip        dbtype.Addr   `json:"ip"`
	FirstSeen dbtype.Time   `json:"first_seen"`
	LastSeen  dbtype.Time   `json:"last_seen"`
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) (Address, error) {
	row := q.queryRow(ctx, q.insertAddressStmt, insertAddress,
		arg.DeviceID,
		arg.NetworkID,
		arg.Ip,
		arg.FirstSeen,
		arg.LastSeen,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.NetworkID,
		&i.Ip,
		&i.IsCurrent,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const listDeviceAddresses = `-- name: ListDeviceAddresses :many
SELECT id, device_id, network_id, ip, is_current, first_seen, last_seen
FROM addresses
WHERE device_id = ?
ORDER BY is_current DESC, last_seen DESC
`

// Current addresses first, then the ones the device has released: "where did
// this used to live" is the reason the released rows are kept.
func (q *Queries) ListDeviceAddresses(ctx context.Context, deviceID int64) ([]Address, error) {
	rows, err := q.query(ctx, q.listDeviceAddressesStmt, listDeviceAddresses, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.NetworkID,
			&i.Ip,
			&i.IsCurrent,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceEvents = `-- name: ListDeviceEvents :many
SELECT id, device_id, scan_id, kind, old_value, new_value, detail, occurred_at
FROM events
WHERE device_id = ?
ORDER BY occurred_at DESC, id DESC
LIMIT ?
`

type ListDeviceEventsParams struct {
	DeviceID sql.NullInt64 `json:"device_id"`
	Limit    int64         `json:"limit"`
}

// Timestamps only resolve to the millisecond, so id breaks the ties within one
// scan, which writes every one of its events on the same stamp.
func (q *Queries) ListDeviceEvents(ctx context.Context, arg ListDeviceEventsParams) ([]Event, error) {
	rows, err := q.query(ctx, q.listDeviceEventsStmt, listDeviceEvents, arg.DeviceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.ScanID,
			&i.Kind,
			&i.OldValue,
			&i.NewValue,
			&i.Detail,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many

SELECT d.id, d.mac, d.identity_source, d.is_randomised, d.vendor, d.hostname, d.hostname_source, d.device_type, d.label, d.notes, d.group_name, d.is_ignored, d.first_seen, d.last_seen,
       CAST(COALESCE((SELECT GROUP_CONCAT(a.ip, ' ')
                      FROM addresses a
                      WHERE a.device_id = d.id
                        AND a.is_current = 1), '') AS TEXT) AS current_ips
FROM devices d
WHERE (d.is_ignored = 0 OR d.is_ignored = ?1)
  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) IS NULL
    OR d.label LIKE '%' || CAST(?3 AS TEXT) || '%'
    OR d.hostname LIKE '%' || CAST(?3 AS TEXT) || '%'
    OR d.vendor LIKE '%' || CAST(?3 AS TEXT) || '%'
    OR d.mac LIKE '%' || CAST(?3 AS TEXT) || '%'
    OR EXISTS (SELECT 1
               FROM addresses a
               WHERE a.device_id = d.id
                 AND a.is_current = 1
                 AND a.ip LIKE '%' || CAST(?3 AS TEXT) || '%'))
ORDER BY d.last_seen DESC
`

type ListDevicesParams struct {
	IncludeIgnored bool           `json:"include_ignored"`
	GroupName      sql.NullString `json:"group_name"`
	Q              sql.NullString `json:"q"`
}

type ListDevicesRow struct {
	Device     Device `json:"device"`
	CurrentIps string `json:"current_ips"`
}

// Reads.
// The current addresses come back on the device's own row rather than through a
// join, so one query answers the list. GROUP_CONCAT has no ordering worth
// relying on and the column is TEXT, which sorts 192.0.2.9 after 192.0.2.100,
// so the caller splits and orders them.
//
// is_ignored compares against the argument rather than testing a flag: passing
// false leaves the clause admitting only unignored rows, and passing true makes
// the second half admit the rest.
func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error) {
	rows, err := q.query(ctx, q.listDevicesStmt, listDevices, arg.IncludeIgnored, arg.GroupName, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesRow
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.Mac,
			&i.Device.IdentitySource,
			&i.Device.IsRandomised,
			&i.Device.Vendor,
			&i.Device.Hostname,
			&i.Device.HostnameSource,
			&i.Device.DeviceType,
			&i.Device.Label,
			&i.Device.Notes,
			&i.Device.GroupName,
			&i.Device.IsIgnored,
			&i.Device.FirstSeen,
			&i.Device.LastSeen,
			&i.CurrentIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.device_id, e.scan_id, e.kind, e.old_value, e.new_value, e.detail, e.occurred_at,
       d.label    AS device_label,
       d.hostname AS device_hostname,
       d.mac      AS device_mac
FROM events e
         LEFT JOIN devices d ON d.id = e.device_id
ORDER BY e.occurred_at DESC, e.id DESC
LIMIT ? OFFSET ?
`

type ListEventsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListEventsRow struct {
	Event          Event          `json:"event"`
	DeviceLabel    sql.NullString `json:"device_label"`
	DeviceHostname sql.NullString `json:"device_hostname"`
	DeviceMac      dbtype.MAC     `json:"device_mac"`
}

// The device columns come from a LEFT JOIN because an event outlives the device
// it described: deleting one sets events.device_id to NULL rather than taking
// the record with it.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.query(ctx, q.listEventsStmt, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.Event.ID,
			&i.Event.DeviceID,
			&i.Event.ScanID,
			&i.Event.Kind,
			&i.Event.OldValue,
			&i.Event.NewValue,
			&i.Event.Detail,
			&i.Event.OccurredAt,
			&i.DeviceLabel,
			&i.DeviceHostname,
			&i.DeviceMac,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT DISTINCT CAST(group_name AS TEXT) AS group_name
FROM devices
WHERE group_name IS NOT NULL
  AND group_name <> ''
ORDER BY group_name
`

func (q *Queries) ListGroups(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listGroupsStmt, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScans = `-- name: ListScans :many
SELECT s.id, s.source_id, s.kind, s.network_id, s.status, s.error, s.found_count, s.started_at, s.finished_at,
       src.name                          AS source_name,
       CAST(COALESCE(n.cidr, '') AS TEXT) AS network_cidr
FROM scans s
         JOIN sources src ON src.id = s.source_id
         LEFT JOIN networks n ON n.id = s.network_id
ORDER BY s.started_at DESC, s.id DESC
LIMIT ? OFFSET ?
`

type ListScansParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListScansRow struct {
	Scan        Scan   `json:"scan"`
	SourceName  string `json:"source_name"`
	NetworkCidr string `json:"network_cidr"`
}

// network_cidr is cast and coalesced rather than selected as itself: the column
// override types it as a non-null Prefix, which cannot scan the NULL a scan
// with no network -- or one whose network was deleted -- produces here.
func (q *Queries) ListScans(ctx context.Context, arg ListScansParams) ([]ListScansRow, error) {
	rows, err := q.query(ctx, q.listScansStmt, listScans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScansRow
	for rows.Next() {
		var i ListScansRow
		if err := rows.Scan(
			&i.Scan.ID,
			&i.Scan.SourceID,
			&i.Scan.Kind,
			&i.Scan.NetworkID,
			&i.Scan.Status,
			&i.Scan.Error,
			&i.Scan.FoundCount,
			&i.Scan.StartedAt,
			&i.Scan.FinishedAt,
			&i.SourceName,
			&i.NetworkCidr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAddresses = `-- name: MoveAddresses :exec
UPDATE OR IGNORE addresses
SET device_id = ?1
WHERE device_id = ?2
`

type MoveAddressesParams struct {
	IntoID int64 `json:"into_id"`
	FromID int64 `json:"from_id"`
}

// Rows the surviving device already holds for the same address are left behind
// and go with the folded device when it is deleted.
func (q *Queries) MoveAddresses(ctx context.Context, arg MoveAddressesParams) error {
	_, err := q.exec(ctx, q.moveAddressesStmt, moveAddresses, arg.IntoID, arg.FromID)
	return err
}

const moveEvents = `-- name: MoveEvents :exec
UPDATE events
SET device_id = ?1
WHERE device_id = ?2
`

type MoveEventsParams struct {
	IntoID sql.NullInt64 `json:"into_id"`
	FromID sql.NullInt64 `json:"from_id"`
}

func (q *Queries) MoveEvents(ctx context.Context, arg MoveEventsParams) error {
	_, err := q.exec(ctx, q.moveEventsStmt, moveEvents, arg.IntoID, arg.FromID)
	return err
}

const refreshAddress = `-- name: RefreshAddress :exec
UPDATE addresses
SET is_current = 1,
    network_id = ?1,
    last_seen  = ?2
WHERE id = ?3
`

type RefreshAddressParams struct {
	NetworkID sql.NullInt64 `json:"network_id"`
	LastSeen  dbtype.Time   `json:"last_seen"`
	ID        int64         `json:"id"`
}

func (q *Queries) RefreshAddress(ctx context.Context, arg RefreshAddressParams) error {
	_, err := q.exec(ctx, q.refreshAddressStmt, refreshAddress, arg.NetworkID, arg.LastSeen, arg.ID)
	return err
}

const releaseAddress = `-- name: ReleaseAddress :exec
UPDATE addresses
SET is_current = 0
WHERE ip = ?1
  AND is_current = 1
  AND device_id <> ?2
`

type ReleaseAddressParams struct {
	Ip       dbtype.Addr `json:"ip"`
	DeviceID int64       `json:"device_id"`
}

// Only one device may hold an address as current, so the previous holder is
// released before the new claim rather than colliding with the partial index.
func (q *Queries) ReleaseAddress(ctx context.Context, arg ReleaseAddressParams) error {
	_, err := q.exec(ctx, q.releaseAddressStmt, releaseAddress, arg.Ip, arg.DeviceID)
	return err
}

const setDeviceHostname = `-- name: SetDeviceHostname :exec
UPDATE devices
SET hostname        = ?1,
    hostname_source = ?2
WHERE id = ?3
`

type SetDeviceHostnameParams struct {
	Hostname       sql.NullString        `json:"hostname"`
	HostnameSource dbtype.HostnameSource `json:"hostname_source"`
	ID             int64                 `json:"id"`
}

func (q *Queries) SetDeviceHostname(ctx context.Context, arg SetDeviceHostnameParams) error {
	_, err := q.exec(ctx, q.setDeviceHostnameStmt, setDeviceHostname, arg.Hostname, arg.HostnameSource, arg.ID)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices
SET last_seen = ?1
WHERE id = ?2
`

type TouchDeviceParams struct {
	LastSeen dbtype.Time `json:"last_seen"`
	ID       int64       `json:"id"`
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.exec(ctx, q.touchDeviceStmt, touchDevice, arg.LastSeen, arg.ID)
	return err
}

const upsertNetwork = `-- name: UpsertNetwork :one
INSERT INTO networks (cidr, created_at)
VALUES (?, ?)
ON CONFLICT (cidr) DO UPDATE SET cidr = excluded.cidr
RETURNING id, cidr, name, vlan_id, created_at
`

type UpsertNetworkParams struct {
	Cidr      dbtype.Prefix `json:"cidr"`
	CreatedAt dbtype.Time   `json:"created_at"`
}

func (q *Queries) UpsertNetwork(ctx context.Context, arg UpsertNetworkParams) (Network, error) {
	row := q.queryRow(ctx, q.upsertNetworkStmt, upsertNetwork, arg.Cidr, arg.CreatedAt)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Name,
		&i.VlanID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSource = `-- name: UpsertSource :one
INSERT INTO sources (kind, name, created_at)
VALUES (?, ?, ?)
ON CONFLICT (name) DO UPDATE SET kind = excluded.kind
RETURNING id, kind, name, created_at
`

type UpsertSourceParams struct {
	Kind      dbtype.SourceKind `json:"kind"`
	Name      string            `json:"name"`
	CreatedAt dbtype.Time       `json:"created_at"`
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) (Source, error) {
	row := q.queryRow(ctx, q.upsertSourceStmt, upsertSource, arg.Kind, arg.Name, arg.CreatedAt)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
