// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package models

import (
	"context"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const createNotifyRule = `-- name: CreateNotifyRule :exec
INSERT INTO notify_rules (destination, kind)
VALUES (?, ?)
`

type CreateNotifyRuleParams struct {
	Destination string           `json:"destination"`
	Kind        dbtype.EventKind `json:"kind"`
}

// CreateNotifyRule
//
//	INSERT INTO notify_rules (destination, kind)
//	VALUES (?, ?)
func (q *Queries) CreateNotifyRule(ctx context.Context, arg CreateNotifyRuleParams) error {
	_, err := q.exec(ctx, q.createNotifyRuleStmt, createNotifyRule, arg.Destination, arg.Kind)
	return err
}

const deleteNotifyRules = `-- name: DeleteNotifyRules :exec
DELETE
FROM notify_rules
WHERE destination = ?
`

// DeleteNotifyRules
//
//	DELETE
//	FROM notify_rules
//	WHERE destination = ?
func (q *Queries) DeleteNotifyRules(ctx context.Context, destination string) error {
	_, err := q.exec(ctx, q.deleteNotifyRulesStmt, deleteNotifyRules, destination)
	return err
}

const notifyRules = `-- name: NotifyRules :many
SELECT kind
FROM notify_rules
WHERE destination = ?
ORDER BY kind
`

// NotifyRules
//
//	SELECT kind
//	FROM notify_rules
//	WHERE destination = ?
//	ORDER BY kind
func (q *Queries) NotifyRules(ctx context.Context, destination string) ([]dbtype.EventKind, error) {
	rows, err := q.query(ctx, q.notifyRulesStmt, notifyRules, destination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []dbtype.EventKind
	for rows.Next() {
		var kind dbtype.EventKind
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
