// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probes.sql

package models

import (
	"context"
	"database/sql"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const answerProbes = `-- name: AnswerProbes :exec
UPDATE probes_hourly
SET answered = MIN(attempts, answered + CAST(?1 AS INTEGER))
WHERE device_id = ?2
  AND hour = ?3
  AND source_id = ?4
  AND peer_ip = ?5
  AND protocol = ?6
`

type AnswerProbesParams struct {
	Late     int64       `json:"late"`
	DeviceID int64       `json:"device_id"`
	Hour     dbtype.Time `json:"hour"`
	SourceID int64       `json:"source_id"`
	PeerIP   dbtype.Addr `json:"peer_ip"`
	Protocol int64       `json:"protocol"`
}

// A device's answer that arrived a flush after the probe it answers.
//
//	UPDATE probes_hourly
//	SET answered = MIN(attempts, answered + CAST(?1 AS INTEGER))
//	WHERE device_id = ?2
//	  AND hour = ?3
//	  AND source_id = ?4
//	  AND peer_ip = ?5
//	  AND protocol = ?6
func (q *Queries) AnswerProbes(ctx context.Context, arg AnswerProbesParams) error {
	_, err := q.exec(ctx, q.answerProbesStmt, answerProbes,
		arg.Late,
		arg.DeviceID,
		arg.Hour,
		arg.SourceID,
		arg.PeerIP,
		arg.Protocol,
	)
	return err
}

const deleteProbesBefore = `-- name: DeleteProbesBefore :execrows
DELETE
FROM probes_hourly
WHERE hour < ?
`

// DeleteProbesBefore
//
//	DELETE
//	FROM probes_hourly
//	WHERE hour < ?
func (q *Queries) DeleteProbesBefore(ctx context.Context, hour dbtype.Time) (int64, error) {
	result, err := q.exec(ctx, q.deleteProbesBeforeStmt, deleteProbesBefore, hour)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const outsideAddresses = `-- name: OutsideAddresses :many
SELECT DISTINCT CAST(address AS TEXT) AS address
FROM outside_addresses
WHERE last_seen >= ?
ORDER BY address
`

// The outside addresses any router named since a given moment.
//
//	SELECT DISTINCT CAST(address AS TEXT) AS address
//	FROM outside_addresses
//	WHERE last_seen >= ?
//	ORDER BY address
func (q *Queries) OutsideAddresses(ctx context.Context, lastSeen dbtype.Time) ([]string, error) {
	rows, err := q.query(ctx, q.outsideAddressesStmt, outsideAddresses, lastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const probePorts = `-- name: ProbePorts :one
SELECT port_count, ports
FROM probes_hourly
WHERE device_id = ?
  AND hour = ?
  AND source_id = ?
  AND peer_ip = ?
  AND protocol = ?
`

type ProbePortsParams struct {
	DeviceID int64       `json:"device_id"`
	Hour     dbtype.Time `json:"hour"`
	SourceID int64       `json:"source_id"`
	PeerIP   dbtype.Addr `json:"peer_ip"`
	Protocol int64       `json:"protocol"`
}

type ProbePortsRow struct {
	PortCount int64  `json:"port_count"`
	Ports     string `json:"ports"`
}

// The ports already on record for one device, peer and hour, so a flush can
// merge its own into them.
//
//	SELECT port_count, ports
//	FROM probes_hourly
//	WHERE device_id = ?
//	  AND hour = ?
//	  AND source_id = ?
//	  AND peer_ip = ?
//	  AND protocol = ?
func (q *Queries) ProbePorts(ctx context.Context, arg ProbePortsParams) (*ProbePortsRow, error) {
	row := q.queryRow(ctx, q.probePortsStmt, probePorts,
		arg.DeviceID,
		arg.Hour,
		arg.SourceID,
		arg.PeerIP,
		arg.Protocol,
	)
	var i ProbePortsRow
	err := row.Scan(&i.PortCount, &i.Ports)
	return &i, err
}

const probedDevices = `-- name: ProbedDevices :many
SELECT d.id,
       CAST(COALESCE(d.label, '') AS TEXT)        AS label,
       CAST(COALESCE(d.hostname, '') AS TEXT)     AS hostname,
       CAST(COALESCE(d.mac, '') AS TEXT)          AS mac,
       p.outside,
       CAST(COUNT(DISTINCT p.peer_ip) AS INTEGER) AS peers,
       CAST(COUNT(DISTINCT p.peer_asn) AS INTEGER) AS orgs,
       CAST(SUM(p.attempts) AS INTEGER)           AS attempts,
       CAST(SUM(p.answered) AS INTEGER)           AS answered,
       CAST(MAX(p.port_count) AS INTEGER)         AS max_ports,
       CAST(GROUP_CONCAT(p.ports, ',') AS TEXT)   AS ports,
       CAST(MAX(p.hour) AS TEXT)                  AS last_hour
FROM probes_hourly p
         JOIN devices d ON d.id = p.device_id
WHERE p.hour >= ?1
  AND d.is_ignored = 0
  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
GROUP BY d.id, p.outside
ORDER BY SUM(p.attempts) DESC, d.id
`

type ProbedDevicesParams struct {
	Since     dbtype.Time    `json:"since"`
	GroupName sql.NullString `json:"group_name"`
}

type ProbedDevicesRow struct {
	ID       int64  `json:"id"`
	Label    string `json:"label"`
	Hostname string `json:"hostname"`
	MAC      string `json:"mac"`
	Outside  int64  `json:"outside"`
	Peers    int64  `json:"peers"`
	Orgs     int64  `json:"orgs"`
	Attempts int64  `json:"attempts"`
	Answered int64  `json:"answered"`
	MaxPorts int64  `json:"max_ports"`
	Ports    string `json:"ports"`
	LastHour string `json:"last_hour"`
}

// The devices the internet probed since a given hour, one row per device and
// whether its outside address was what was tried, most probes first. ports is
// every hour's sample joined; the caller merges them.
//
//	SELECT d.id,
//	       CAST(COALESCE(d.label, '') AS TEXT)        AS label,
//	       CAST(COALESCE(d.hostname, '') AS TEXT)     AS hostname,
//	       CAST(COALESCE(d.mac, '') AS TEXT)          AS mac,
//	       p.outside,
//	       CAST(COUNT(DISTINCT p.peer_ip) AS INTEGER) AS peers,
//	       CAST(COUNT(DISTINCT p.peer_asn) AS INTEGER) AS orgs,
//	       CAST(SUM(p.attempts) AS INTEGER)           AS attempts,
//	       CAST(SUM(p.answered) AS INTEGER)           AS answered,
//	       CAST(MAX(p.port_count) AS INTEGER)         AS max_ports,
//	       CAST(GROUP_CONCAT(p.ports, ',') AS TEXT)   AS ports,
//	       CAST(MAX(p.hour) AS TEXT)                  AS last_hour
//	FROM probes_hourly p
//	         JOIN devices d ON d.id = p.device_id
//	WHERE p.hour >= ?1
//	  AND d.is_ignored = 0
//	  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
//	GROUP BY d.id, p.outside
//	ORDER BY SUM(p.attempts) DESC, d.id
func (q *Queries) ProbedDevices(ctx context.Context, arg ProbedDevicesParams) ([]*ProbedDevicesRow, error) {
	rows, err := q.query(ctx, q.probedDevicesStmt, probedDevices, arg.Since, arg.GroupName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProbedDevicesRow
	for rows.Next() {
		var i ProbedDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Hostname,
			&i.MAC,
			&i.Outside,
			&i.Peers,
			&i.Orgs,
			&i.Attempts,
			&i.Answered,
			&i.MaxPorts,
			&i.Ports,
			&i.LastHour,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOutsideAddress = `-- name: UpsertOutsideAddress :exec
INSERT INTO outside_addresses (source_id, address, first_seen, last_seen)
VALUES (?, ?, ?, ?)
ON CONFLICT (source_id, address) DO UPDATE
    SET last_seen = MAX(last_seen, excluded.last_seen)
`

type UpsertOutsideAddressParams struct {
	SourceID  int64       `json:"source_id"`
	Address   dbtype.Addr `json:"address"`
	FirstSeen dbtype.Time `json:"first_seen"`
	LastSeen  dbtype.Time `json:"last_seen"`
}

// A router named this outside address again.
//
//	INSERT INTO outside_addresses (source_id, address, first_seen, last_seen)
//	VALUES (?, ?, ?, ?)
//	ON CONFLICT (source_id, address) DO UPDATE
//	    SET last_seen = MAX(last_seen, excluded.last_seen)
func (q *Queries) UpsertOutsideAddress(ctx context.Context, arg UpsertOutsideAddressParams) error {
	_, err := q.exec(ctx, q.upsertOutsideAddressStmt, upsertOutsideAddress,
		arg.SourceID,
		arg.Address,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}

const upsertProbes = `-- name: UpsertProbes :exec
INSERT INTO probes_hourly (source_id, device_id, hour, peer_ip, peer_asn, protocol,
                           attempts, answered, port_count, ports, outside)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (device_id, hour, source_id, peer_ip, protocol) DO UPDATE
    SET peer_asn   = COALESCE(excluded.peer_asn, peer_asn),
        attempts   = attempts + excluded.attempts,
        answered   = answered + excluded.answered,
        port_count = MAX(port_count, excluded.port_count),
        ports      = excluded.ports,
        outside    = MAX(outside, excluded.outside)
`

type UpsertProbesParams struct {
	SourceID  int64         `json:"source_id"`
	DeviceID  int64         `json:"device_id"`
	Hour      dbtype.Time   `json:"hour"`
	PeerIP    dbtype.Addr   `json:"peer_ip"`
	PeerASN   sql.NullInt64 `json:"peer_asn"`
	Protocol  int64         `json:"protocol"`
	Attempts  int64         `json:"attempts"`
	Answered  int64         `json:"answered"`
	PortCount int64         `json:"port_count"`
	Ports     string        `json:"ports"`
	Outside   int64         `json:"outside"`
}

// One flush adds to the hour's probe counts. The caller has already merged the
// port sample with the one on record, so it replaces it.
//
//	INSERT INTO probes_hourly (source_id, device_id, hour, peer_ip, peer_asn, protocol,
//	                           attempts, answered, port_count, ports, outside)
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
//	ON CONFLICT (device_id, hour, source_id, peer_ip, protocol) DO UPDATE
//	    SET peer_asn   = COALESCE(excluded.peer_asn, peer_asn),
//	        attempts   = attempts + excluded.attempts,
//	        answered   = answered + excluded.answered,
//	        port_count = MAX(port_count, excluded.port_count),
//	        ports      = excluded.ports,
//	        outside    = MAX(outside, excluded.outside)
func (q *Queries) UpsertProbes(ctx context.Context, arg UpsertProbesParams) error {
	_, err := q.exec(ctx, q.upsertProbesStmt, upsertProbes,
		arg.SourceID,
		arg.DeviceID,
		arg.Hour,
		arg.PeerIP,
		arg.PeerASN,
		arg.Protocol,
		arg.Attempts,
		arg.Answered,
		arg.PortCount,
		arg.Ports,
		arg.Outside,
	)
	return err
}
