// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package models

import (
	"context"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const countUnusedRecoveryCodesByUser = `-- name: CountUnusedRecoveryCodesByUser :one
SELECT COUNT(*)
FROM user_recovery_codes
WHERE user_id = ?
  AND used_at IS NULL
`

// CountUnusedRecoveryCodesByUser
//
//	SELECT COUNT(*)
//	FROM user_recovery_codes
//	WHERE user_id = ?
//	  AND used_at IS NULL
func (q *Queries) CountUnusedRecoveryCodesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.queryRow(ctx, q.countUnusedRecoveryCodesByUserStmt, countUnusedRecoveryCodesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO user_recovery_codes (user_id, code_hash)
VALUES (?, ?)
RETURNING id, user_id, code_hash, created_at, used_at
`

type CreateRecoveryCodeParams struct {
	UserID   int64  `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

// CreateRecoveryCode
//
//	INSERT INTO user_recovery_codes (user_id, code_hash)
//	VALUES (?, ?)
//	RETURNING id, user_id, code_hash, created_at, used_at
func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (*UserRecoveryCode, error) {
	row := q.queryRow(ctx, q.createRecoveryCodeStmt, createRecoveryCode, arg.UserID, arg.CodeHash)
	var i UserRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}

const deleteRecoveryCodesByUser = `-- name: DeleteRecoveryCodesByUser :exec
DELETE
FROM user_recovery_codes
WHERE user_id = ?
`

// DeleteRecoveryCodesByUser
//
//	DELETE
//	FROM user_recovery_codes
//	WHERE user_id = ?
func (q *Queries) DeleteRecoveryCodesByUser(ctx context.Context, userID int64) error {
	_, err := q.exec(ctx, q.deleteRecoveryCodesByUserStmt, deleteRecoveryCodesByUser, userID)
	return err
}

const redeemRecoveryCode = `-- name: RedeemRecoveryCode :one
UPDATE user_recovery_codes
SET used_at = ?
WHERE user_id = ?
  AND code_hash = ?
  AND used_at IS NULL
RETURNING id, user_id, code_hash, created_at, used_at
`

type RedeemRecoveryCodeParams struct {
	UsedAt   dbtype.NullTime `json:"used_at"`
	UserID   int64           `json:"user_id"`
	CodeHash string          `json:"code_hash"`
}

// used_at IS NULL in the WHERE clause is what makes redemption single-use
// atomically: a second attempt at the same code finds no row rather than a
// race against a read-then-write.
//
//	UPDATE user_recovery_codes
//	SET used_at = ?
//	WHERE user_id = ?
//	  AND code_hash = ?
//	  AND used_at IS NULL
//	RETURNING id, user_id, code_hash, created_at, used_at
func (q *Queries) RedeemRecoveryCode(ctx context.Context, arg RedeemRecoveryCodeParams) (*UserRecoveryCode, error) {
	row := q.queryRow(ctx, q.redeemRecoveryCodeStmt, redeemRecoveryCode, arg.UsedAt, arg.UserID, arg.CodeHash)
	var i UserRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return &i, err
}
