// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topology.sql

package models

import (
	"context"
	"database/sql"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const deleteTopologyNeighbours = `-- name: DeleteTopologyNeighbours :exec
DELETE
FROM topology_neighbours
WHERE source_id = ?
`

// DeleteTopologyNeighbours
//
//	DELETE
//	FROM topology_neighbours
//	WHERE source_id = ?
func (q *Queries) DeleteTopologyNeighbours(ctx context.Context, sourceID int64) error {
	_, err := q.exec(ctx, q.deleteTopologyNeighboursStmt, deleteTopologyNeighbours, sourceID)
	return err
}

const deleteTopologyPorts = `-- name: DeleteTopologyPorts :exec
DELETE
FROM topology_ports
WHERE source_id = ?
`

// DeleteTopologyPorts
//
//	DELETE
//	FROM topology_ports
//	WHERE source_id = ?
func (q *Queries) DeleteTopologyPorts(ctx context.Context, sourceID int64) error {
	_, err := q.exec(ctx, q.deleteTopologyPortsStmt, deleteTopologyPorts, sourceID)
	return err
}

const deleteTopologySightingsBefore = `-- name: DeleteTopologySightingsBefore :execrows
DELETE
FROM topology_sightings
WHERE last_seen < ?
`

// DeleteTopologySightingsBefore
//
//	DELETE
//	FROM topology_sightings
//	WHERE last_seen < ?
func (q *Queries) DeleteTopologySightingsBefore(ctx context.Context, lastSeen dbtype.Time) (int64, error) {
	result, err := q.exec(ctx, q.deleteTopologySightingsBeforeStmt, deleteTopologySightingsBefore, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertTopologyNeighbour = `-- name: InsertTopologyNeighbour :exec
INSERT INTO topology_neighbours (source_id, port, mac, identity, platform, board, their_port, address)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (source_id, port, mac, identity) DO NOTHING
`

type InsertTopologyNeighbourParams struct {
	SourceID  int64          `json:"source_id"`
	Port      string         `json:"port"`
	MAC       string         `json:"mac"`
	Identity  string         `json:"identity"`
	Platform  sql.NullString `json:"platform"`
	Board     sql.NullString `json:"board"`
	TheirPort sql.NullString `json:"their_port"`
	Address   sql.NullString `json:"address"`
}

// InsertTopologyNeighbour
//
//	INSERT INTO topology_neighbours (source_id, port, mac, identity, platform, board, their_port, address)
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?)
//	ON CONFLICT (source_id, port, mac, identity) DO NOTHING
func (q *Queries) InsertTopologyNeighbour(ctx context.Context, arg InsertTopologyNeighbourParams) error {
	_, err := q.exec(ctx, q.insertTopologyNeighbourStmt, insertTopologyNeighbour,
		arg.SourceID,
		arg.Port,
		arg.MAC,
		arg.Identity,
		arg.Platform,
		arg.Board,
		arg.TheirPort,
		arg.Address,
	)
	return err
}

const insertTopologyPort = `-- name: InsertTopologyPort :exec
INSERT INTO topology_ports (source_id, name, kind, pvid, tagged, untagged, running)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertTopologyPortParams struct {
	SourceID int64  `json:"source_id"`
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Pvid     int64  `json:"pvid"`
	Tagged   string `json:"tagged"`
	Untagged string `json:"untagged"`
	Running  bool   `json:"running"`
}

// InsertTopologyPort
//
//	INSERT INTO topology_ports (source_id, name, kind, pvid, tagged, untagged, running)
//	VALUES (?, ?, ?, ?, ?, ?, ?)
func (q *Queries) InsertTopologyPort(ctx context.Context, arg InsertTopologyPortParams) error {
	_, err := q.exec(ctx, q.insertTopologyPortStmt, insertTopologyPort,
		arg.SourceID,
		arg.Name,
		arg.Kind,
		arg.Pvid,
		arg.Tagged,
		arg.Untagged,
		arg.Running,
	)
	return err
}

const lastTopologyReadAt = `-- name: LastTopologyReadAt :one
SELECT read_at
FROM topology_nodes
ORDER BY read_at DESC
LIMIT 1
`

// When any source was last read for its topology. No row when none has been.
//
//	SELECT read_at
//	FROM topology_nodes
//	ORDER BY read_at DESC
//	LIMIT 1
func (q *Queries) LastTopologyReadAt(ctx context.Context) (dbtype.Time, error) {
	row := q.queryRow(ctx, q.lastTopologyReadAtStmt, lastTopologyReadAt)
	var read_at dbtype.Time
	err := row.Scan(&read_at)
	return read_at, err
}

const listTopologyNeighbours = `-- name: ListTopologyNeighbours :many
SELECT source_id, port, mac, identity, platform, board, their_port, address
FROM topology_neighbours
ORDER BY source_id, port, mac, identity
`

// ListTopologyNeighbours
//
//	SELECT source_id, port, mac, identity, platform, board, their_port, address
//	FROM topology_neighbours
//	ORDER BY source_id, port, mac, identity
func (q *Queries) ListTopologyNeighbours(ctx context.Context) ([]*TopologyNeighbour, error) {
	rows, err := q.query(ctx, q.listTopologyNeighboursStmt, listTopologyNeighbours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TopologyNeighbour
	for rows.Next() {
		var i TopologyNeighbour
		if err := rows.Scan(
			&i.SourceID,
			&i.Port,
			&i.MAC,
			&i.Identity,
			&i.Platform,
			&i.Board,
			&i.TheirPort,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologyNodes = `-- name: ListTopologyNodes :many
SELECT n.source_id, n.identity, n.gateway, n.own_macs, n.read_at, s.name AS source_name
FROM topology_nodes n
         JOIN sources s ON s.id = n.source_id
ORDER BY s.name
`

type ListTopologyNodesRow struct {
	SourceID   int64          `json:"source_id"`
	Identity   sql.NullString `json:"identity"`
	Gateway    bool           `json:"gateway"`
	OwnMacs    string         `json:"own_macs"`
	ReadAt     dbtype.Time    `json:"read_at"`
	SourceName string         `json:"source_name"`
}

// ListTopologyNodes
//
//	SELECT n.source_id, n.identity, n.gateway, n.own_macs, n.read_at, s.name AS source_name
//	FROM topology_nodes n
//	         JOIN sources s ON s.id = n.source_id
//	ORDER BY s.name
func (q *Queries) ListTopologyNodes(ctx context.Context) ([]*ListTopologyNodesRow, error) {
	rows, err := q.query(ctx, q.listTopologyNodesStmt, listTopologyNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTopologyNodesRow
	for rows.Next() {
		var i ListTopologyNodesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.Identity,
			&i.Gateway,
			&i.OwnMacs,
			&i.ReadAt,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologyPorts = `-- name: ListTopologyPorts :many
SELECT source_id, name, kind, pvid, tagged, untagged, running
FROM topology_ports
ORDER BY source_id, name
`

// ListTopologyPorts
//
//	SELECT source_id, name, kind, pvid, tagged, untagged, running
//	FROM topology_ports
//	ORDER BY source_id, name
func (q *Queries) ListTopologyPorts(ctx context.Context) ([]*TopologyPort, error) {
	rows, err := q.query(ctx, q.listTopologyPortsStmt, listTopologyPorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TopologyPort
	for rows.Next() {
		var i TopologyPort
		if err := rows.Scan(
			&i.SourceID,
			&i.Name,
			&i.Kind,
			&i.Pvid,
			&i.Tagged,
			&i.Untagged,
			&i.Running,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologySightings = `-- name: ListTopologySightings :many
SELECT source_id, port, mac, vlan, wifi, ssid, band, first_seen, last_seen
FROM topology_sightings
ORDER BY source_id, port, mac, vlan
`

// ListTopologySightings
//
//	SELECT source_id, port, mac, vlan, wifi, ssid, band, first_seen, last_seen
//	FROM topology_sightings
//	ORDER BY source_id, port, mac, vlan
func (q *Queries) ListTopologySightings(ctx context.Context) ([]*TopologySighting, error) {
	rows, err := q.query(ctx, q.listTopologySightingsStmt, listTopologySightings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TopologySighting
	for rows.Next() {
		var i TopologySighting
		if err := rows.Scan(
			&i.SourceID,
			&i.Port,
			&i.MAC,
			&i.Vlan,
			&i.Wifi,
			&i.Ssid,
			&i.Band,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTopologyNode = `-- name: UpsertTopologyNode :exec
INSERT INTO topology_nodes (source_id, identity, gateway, own_macs, read_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (source_id) DO UPDATE
    SET identity = excluded.identity,
        gateway  = excluded.gateway,
        own_macs = excluded.own_macs,
        read_at  = excluded.read_at
`

type UpsertTopologyNodeParams struct {
	SourceID int64          `json:"source_id"`
	Identity sql.NullString `json:"identity"`
	Gateway  bool           `json:"gateway"`
	OwnMacs  string         `json:"own_macs"`
	ReadAt   dbtype.Time    `json:"read_at"`
}

// UpsertTopologyNode
//
//	INSERT INTO topology_nodes (source_id, identity, gateway, own_macs, read_at)
//	VALUES (?, ?, ?, ?, ?)
//	ON CONFLICT (source_id) DO UPDATE
//	    SET identity = excluded.identity,
//	        gateway  = excluded.gateway,
//	        own_macs = excluded.own_macs,
//	        read_at  = excluded.read_at
func (q *Queries) UpsertTopologyNode(ctx context.Context, arg UpsertTopologyNodeParams) error {
	_, err := q.exec(ctx, q.upsertTopologyNodeStmt, upsertTopologyNode,
		arg.SourceID,
		arg.Identity,
		arg.Gateway,
		arg.OwnMacs,
		arg.ReadAt,
	)
	return err
}

const upsertTopologySighting = `-- name: UpsertTopologySighting :exec
INSERT INTO topology_sightings (source_id, port, mac, vlan, wifi, ssid, band, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (source_id, mac, port, vlan) DO UPDATE
    SET wifi      = excluded.wifi,
        ssid      = excluded.ssid,
        band      = excluded.band,
        last_seen = excluded.last_seen
`

type UpsertTopologySightingParams struct {
	SourceID  int64          `json:"source_id"`
	Port      string         `json:"port"`
	MAC       string         `json:"mac"`
	Vlan      int64          `json:"vlan"`
	Wifi      bool           `json:"wifi"`
	Ssid      sql.NullString `json:"ssid"`
	Band      sql.NullString `json:"band"`
	FirstSeen dbtype.Time    `json:"first_seen"`
	LastSeen  dbtype.Time    `json:"last_seen"`
}

// A read that sees the address again moves its last sighting on, and takes
// what the radio says now about the network it joined.
//
//	INSERT INTO topology_sightings (source_id, port, mac, vlan, wifi, ssid, band, first_seen, last_seen)
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
//	ON CONFLICT (source_id, mac, port, vlan) DO UPDATE
//	    SET wifi      = excluded.wifi,
//	        ssid      = excluded.ssid,
//	        band      = excluded.band,
//	        last_seen = excluded.last_seen
func (q *Queries) UpsertTopologySighting(ctx context.Context, arg UpsertTopologySightingParams) error {
	_, err := q.exec(ctx, q.upsertTopologySightingStmt, upsertTopologySighting,
		arg.SourceID,
		arg.Port,
		arg.MAC,
		arg.Vlan,
		arg.Wifi,
		arg.Ssid,
		arg.Band,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
