// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traffic.sql

package models

import (
	"context"
	"database/sql"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const anyTraffic = `-- name: AnyTraffic :one
SELECT CAST(EXISTS (SELECT 1 FROM traffic_hourly)
    OR EXISTS (SELECT 1 FROM attempts_hourly)
    OR EXISTS (SELECT 1 FROM broadcasts_hourly) AS INTEGER) AS recorded
`

// Whether any traffic has been recorded at all, which is how a view tells
// "nothing was exchanged" from "nothing is collecting". Attempts and
// broadcasts count: a network whose only traffic so far is a scan, or
// devices announcing themselves, is still being collected.
//
//	SELECT CAST(EXISTS (SELECT 1 FROM traffic_hourly)
//	    OR EXISTS (SELECT 1 FROM attempts_hourly)
//	    OR EXISTS (SELECT 1 FROM broadcasts_hourly) AS INTEGER) AS recorded
func (q *Queries) AnyTraffic(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.anyTrafficStmt, anyTraffic)
	var recorded int64
	err := row.Scan(&recorded)
	return recorded, err
}

const busiestDevices = `-- name: BusiestDevices :many
SELECT d.id,
       CAST(COALESCE(d.label, '') AS TEXT)    AS label,
       CAST(COALESCE(d.hostname, '') AS TEXT) AS hostname,
       CAST(COALESCE(d.mac, '') AS TEXT)      AS mac,
       CAST(SUM(t.bytes_out) AS INTEGER)      AS bytes_out,
       CAST(SUM(t.bytes_in) AS INTEGER)       AS bytes_in
FROM traffic_hourly t
         JOIN devices d ON d.id = t.device_id
WHERE t.hour >= ?1
  AND d.is_ignored = 0
  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
GROUP BY d.id
ORDER BY SUM(t.bytes_out + t.bytes_in) DESC, d.id
LIMIT ?3
`

type BusiestDevicesParams struct {
	Since     dbtype.Time    `json:"since"`
	GroupName sql.NullString `json:"group_name"`
	LimitRows int64          `json:"limit_rows"`
}

type BusiestDevicesRow struct {
	ID       int64  `json:"id"`
	Label    string `json:"label"`
	Hostname string `json:"hostname"`
	MAC      string `json:"mac"`
	BytesOut int64  `json:"bytes_out"`
	BytesIn  int64  `json:"bytes_in"`
}

// The devices that moved the most data since a given hour. A conversation
// between two devices counts toward both, since each of them did move it.
//
//	SELECT d.id,
//	       CAST(COALESCE(d.label, '') AS TEXT)    AS label,
//	       CAST(COALESCE(d.hostname, '') AS TEXT) AS hostname,
//	       CAST(COALESCE(d.mac, '') AS TEXT)      AS mac,
//	       CAST(SUM(t.bytes_out) AS INTEGER)      AS bytes_out,
//	       CAST(SUM(t.bytes_in) AS INTEGER)       AS bytes_in
//	FROM traffic_hourly t
//	         JOIN devices d ON d.id = t.device_id
//	WHERE t.hour >= ?1
//	  AND d.is_ignored = 0
//	  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
//	GROUP BY d.id
//	ORDER BY SUM(t.bytes_out + t.bytes_in) DESC, d.id
//	LIMIT ?3
func (q *Queries) BusiestDevices(ctx context.Context, arg BusiestDevicesParams) ([]*BusiestDevicesRow, error) {
	rows, err := q.query(ctx, q.busiestDevicesStmt, busiestDevices, arg.Since, arg.GroupName, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BusiestDevicesRow
	for rows.Next() {
		var i BusiestDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Hostname,
			&i.MAC,
			&i.BytesOut,
			&i.BytesIn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTrafficBefore = `-- name: DeleteTrafficBefore :execrows
DELETE
FROM traffic_hourly
WHERE hour < ?
`

// DeleteTrafficBefore
//
//	DELETE
//	FROM traffic_hourly
//	WHERE hour < ?
func (q *Queries) DeleteTrafficBefore(ctx context.Context, hour dbtype.Time) (int64, error) {
	result, err := q.exec(ctx, q.deleteTrafficBeforeStmt, deleteTrafficBefore, hour)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deviceTraffic = `-- name: DeviceTraffic :many
SELECT CAST(COALESCE(t.peer_device_id, 0) AS INTEGER)    AS peer_device_id,
       CAST(t.peer_ip AS TEXT)                           AS peer_ip,
       CAST(COALESCE(MAX(t.peer_name), '') AS TEXT)      AS peer_name,
       CAST(COALESCE(MAX(t.peer_asn), 0) AS INTEGER)     AS peer_asn,
       CAST(COALESCE(MAX(pd.label), '') AS TEXT)         AS peer_label,
       CAST(COALESCE(MAX(pd.hostname), '') AS TEXT)      AS peer_hostname,
       CAST(COALESCE(MAX(pd.mac), '') AS TEXT)           AS peer_mac,
       t.protocol,
       t.service_port,
       CAST(SUM(t.bytes_out) AS INTEGER)                 AS bytes_out,
       CAST(SUM(t.bytes_in) AS INTEGER)                  AS bytes_in,
       CAST(SUM(t.connections) AS INTEGER)               AS connections,
       CAST(SUM(t.connections_in) AS INTEGER)            AS connections_in,
       CAST(MAX(t.hour) AS TEXT)                         AS last_hour
FROM traffic_hourly t
         LEFT JOIN devices pd ON pd.id = t.peer_device_id
WHERE t.device_id = ?
  AND t.hour >= ?
GROUP BY COALESCE(t.peer_device_id, 0), t.peer_ip, t.protocol, t.service_port
ORDER BY SUM(t.bytes_out + t.bytes_in) DESC, t.peer_ip, t.service_port
LIMIT ?
`

type DeviceTrafficParams struct {
	DeviceID int64       `json:"device_id"`
	Hour     dbtype.Time `json:"hour"`
	Limit    int64       `json:"limit"`
}

type DeviceTrafficRow struct {
	PeerDeviceID  int64  `json:"peer_device_id"`
	PeerIP        string `json:"peer_ip"`
	PeerName      string `json:"peer_name"`
	PeerASN       int64  `json:"peer_asn"`
	PeerLabel     string `json:"peer_label"`
	PeerHostname  string `json:"peer_hostname"`
	PeerMAC       string `json:"peer_mac"`
	Protocol      int64  `json:"protocol"`
	ServicePort   int64  `json:"service_port"`
	BytesOut      int64  `json:"bytes_out"`
	BytesIn       int64  `json:"bytes_in"`
	Connections   int64  `json:"connections"`
	ConnectionsIn int64  `json:"connections_in"`
	LastHour      string `json:"last_hour"`
}

// One device's conversations since a given hour, one row per peer and
// service, busiest first. A peer that was a known device carries that
// device's naming fields so the page can link to it; the grouping keeps an
// address that changed hands between two devices as two peers.
//
//	SELECT CAST(COALESCE(t.peer_device_id, 0) AS INTEGER)    AS peer_device_id,
//	       CAST(t.peer_ip AS TEXT)                           AS peer_ip,
//	       CAST(COALESCE(MAX(t.peer_name), '') AS TEXT)      AS peer_name,
//	       CAST(COALESCE(MAX(t.peer_asn), 0) AS INTEGER)     AS peer_asn,
//	       CAST(COALESCE(MAX(pd.label), '') AS TEXT)         AS peer_label,
//	       CAST(COALESCE(MAX(pd.hostname), '') AS TEXT)      AS peer_hostname,
//	       CAST(COALESCE(MAX(pd.mac), '') AS TEXT)           AS peer_mac,
//	       t.protocol,
//	       t.service_port,
//	       CAST(SUM(t.bytes_out) AS INTEGER)                 AS bytes_out,
//	       CAST(SUM(t.bytes_in) AS INTEGER)                  AS bytes_in,
//	       CAST(SUM(t.connections) AS INTEGER)               AS connections,
//	       CAST(SUM(t.connections_in) AS INTEGER)            AS connections_in,
//	       CAST(MAX(t.hour) AS TEXT)                         AS last_hour
//	FROM traffic_hourly t
//	         LEFT JOIN devices pd ON pd.id = t.peer_device_id
//	WHERE t.device_id = ?
//	  AND t.hour >= ?
//	GROUP BY COALESCE(t.peer_device_id, 0), t.peer_ip, t.protocol, t.service_port
//	ORDER BY SUM(t.bytes_out + t.bytes_in) DESC, t.peer_ip, t.service_port
//	LIMIT ?
func (q *Queries) DeviceTraffic(ctx context.Context, arg DeviceTrafficParams) ([]*DeviceTrafficRow, error) {
	rows, err := q.query(ctx, q.deviceTrafficStmt, deviceTraffic, arg.DeviceID, arg.Hour, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DeviceTrafficRow
	for rows.Next() {
		var i DeviceTrafficRow
		if err := rows.Scan(
			&i.PeerDeviceID,
			&i.PeerIP,
			&i.PeerName,
			&i.PeerASN,
			&i.PeerLabel,
			&i.PeerHostname,
			&i.PeerMAC,
			&i.Protocol,
			&i.ServicePort,
			&i.BytesOut,
			&i.BytesIn,
			&i.Connections,
			&i.ConnectionsIn,
			&i.LastHour,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const earliestTraffic = `-- name: EarliestTraffic :one
SELECT CAST(COALESCE(MIN(hour), '') AS TEXT) AS first_hour
FROM traffic_hourly
`

// The first hour anything was recorded, or empty when nothing has been: how
// far back "first contact" can honestly look.
//
//	SELECT CAST(COALESCE(MIN(hour), '') AS TEXT) AS first_hour
//	FROM traffic_hourly
func (q *Queries) EarliestTraffic(ctx context.Context) (string, error) {
	row := q.queryRow(ctx, q.earliestTrafficStmt, earliestTraffic)
	var first_hour string
	err := row.Scan(&first_hour)
	return first_hour, err
}

const firstContacts = `-- name: FirstContacts :many
SELECT d.id,
       CAST(COALESCE(d.label, '') AS TEXT)    AS label,
       CAST(COALESCE(d.hostname, '') AS TEXT) AS hostname,
       CAST(COALESCE(d.mac, '') AS TEXT)      AS mac,
       CAST(t.peer_asn AS INTEGER)            AS peer_asn,
       CAST(MIN(t.peer_ip) AS TEXT)           AS peer_ip,
       CAST(MIN(t.hour) AS TEXT)              AS first_hour,
       CAST(SUM(t.bytes_out + t.bytes_in) AS INTEGER) AS bytes
FROM traffic_hourly t
         JOIN devices d ON d.id = t.device_id
WHERE t.peer_asn IS NOT NULL
  AND d.is_ignored = 0
  AND (CAST(?1 AS TEXT) IS NULL OR d.group_name = CAST(?1 AS TEXT))
GROUP BY d.id, t.peer_asn
HAVING MIN(t.hour) >= ?2
ORDER BY MIN(t.hour) DESC, d.id
LIMIT ?3
`

type FirstContactsParams struct {
	GroupName sql.NullString `json:"group_name"`
	Since     dbtype.Time    `json:"since"`
	LimitRows int64          `json:"limit_rows"`
}

type FirstContactsRow struct {
	ID        int64  `json:"id"`
	Label     string `json:"label"`
	Hostname  string `json:"hostname"`
	MAC       string `json:"mac"`
	PeerASN   int64  `json:"peer_asn"`
	PeerIP    string `json:"peer_ip"`
	FirstHour string `json:"first_hour"`
	Bytes     int64  `json:"bytes"`
}

// Each device's first exchange with an organisation, when it fell at or after
// a given hour: the organisations a device started talking to lately. Keyed on
// the organisation, so a service moving between the
// addresses of one provider is not news.
//
//	SELECT d.id,
//	       CAST(COALESCE(d.label, '') AS TEXT)    AS label,
//	       CAST(COALESCE(d.hostname, '') AS TEXT) AS hostname,
//	       CAST(COALESCE(d.mac, '') AS TEXT)      AS mac,
//	       CAST(t.peer_asn AS INTEGER)            AS peer_asn,
//	       CAST(MIN(t.peer_ip) AS TEXT)           AS peer_ip,
//	       CAST(MIN(t.hour) AS TEXT)              AS first_hour,
//	       CAST(SUM(t.bytes_out + t.bytes_in) AS INTEGER) AS bytes
//	FROM traffic_hourly t
//	         JOIN devices d ON d.id = t.device_id
//	WHERE t.peer_asn IS NOT NULL
//	  AND d.is_ignored = 0
//	  AND (CAST(?1 AS TEXT) IS NULL OR d.group_name = CAST(?1 AS TEXT))
//	GROUP BY d.id, t.peer_asn
//	HAVING MIN(t.hour) >= ?2
//	ORDER BY MIN(t.hour) DESC, d.id
//	LIMIT ?3
func (q *Queries) FirstContacts(ctx context.Context, arg FirstContactsParams) ([]*FirstContactsRow, error) {
	rows, err := q.query(ctx, q.firstContactsStmt, firstContacts, arg.GroupName, arg.Since, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*FirstContactsRow
	for rows.Next() {
		var i FirstContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Hostname,
			&i.MAC,
			&i.PeerASN,
			&i.PeerIP,
			&i.FirstHour,
			&i.Bytes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incomingFromInternet = `-- name: IncomingFromInternet :many
SELECT d.id,
       CAST(COALESCE(d.label, '') AS TEXT)          AS label,
       CAST(COALESCE(d.hostname, '') AS TEXT)       AS hostname,
       CAST(COALESCE(d.mac, '') AS TEXT)            AS mac,
       t.protocol,
       t.service_port,
       CAST(SUM(t.connections_in) AS INTEGER)       AS connections,
       CAST(COUNT(DISTINCT t.peer_ip) AS INTEGER)   AS peers,
       CAST(COUNT(DISTINCT t.peer_asn) AS INTEGER)  AS orgs,
       CAST(SUM(t.bytes_in) AS INTEGER)             AS bytes_in,
       CAST(SUM(t.bytes_out) AS INTEGER)            AS bytes_out,
       CAST(MAX(t.hour) AS TEXT)                    AS last_hour
FROM traffic_hourly t
         JOIN devices d ON d.id = t.device_id
WHERE t.peer_asn IS NOT NULL
  AND t.connections_in > 0
  AND t.hour >= ?1
  AND d.is_ignored = 0
  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
GROUP BY d.id, t.protocol, t.service_port
ORDER BY SUM(t.connections_in) DESC, d.id, t.service_port
LIMIT ?3
`

type IncomingFromInternetParams struct {
	Since     dbtype.Time    `json:"since"`
	GroupName sql.NullString `json:"group_name"`
	LimitRows int64          `json:"limit_rows"`
}

type IncomingFromInternetRow struct {
	ID          int64  `json:"id"`
	Label       string `json:"label"`
	Hostname    string `json:"hostname"`
	MAC         string `json:"mac"`
	Protocol    int64  `json:"protocol"`
	ServicePort int64  `json:"service_port"`
	Connections int64  `json:"connections"`
	Peers       int64  `json:"peers"`
	Orgs        int64  `json:"orgs"`
	BytesIn     int64  `json:"bytes_in"`
	BytesOut    int64  `json:"bytes_out"`
	LastHour    string `json:"last_hour"`
}

// The devices internet peers opened connections to since a given hour, one
// row per device and service: what the network exposes, as used. Only peers an
// organisation announces count as the internet.
//
//	SELECT d.id,
//	       CAST(COALESCE(d.label, '') AS TEXT)          AS label,
//	       CAST(COALESCE(d.hostname, '') AS TEXT)       AS hostname,
//	       CAST(COALESCE(d.mac, '') AS TEXT)            AS mac,
//	       t.protocol,
//	       t.service_port,
//	       CAST(SUM(t.connections_in) AS INTEGER)       AS connections,
//	       CAST(COUNT(DISTINCT t.peer_ip) AS INTEGER)   AS peers,
//	       CAST(COUNT(DISTINCT t.peer_asn) AS INTEGER)  AS orgs,
//	       CAST(SUM(t.bytes_in) AS INTEGER)             AS bytes_in,
//	       CAST(SUM(t.bytes_out) AS INTEGER)            AS bytes_out,
//	       CAST(MAX(t.hour) AS TEXT)                    AS last_hour
//	FROM traffic_hourly t
//	         JOIN devices d ON d.id = t.device_id
//	WHERE t.peer_asn IS NOT NULL
//	  AND t.connections_in > 0
//	  AND t.hour >= ?1
//	  AND d.is_ignored = 0
//	  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
//	GROUP BY d.id, t.protocol, t.service_port
//	ORDER BY SUM(t.connections_in) DESC, d.id, t.service_port
//	LIMIT ?3
func (q *Queries) IncomingFromInternet(ctx context.Context, arg IncomingFromInternetParams) ([]*IncomingFromInternetRow, error) {
	rows, err := q.query(ctx, q.incomingFromInternetStmt, incomingFromInternet, arg.Since, arg.GroupName, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*IncomingFromInternetRow
	for rows.Next() {
		var i IncomingFromInternetRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Hostname,
			&i.MAC,
			&i.Protocol,
			&i.ServicePort,
			&i.Connections,
			&i.Peers,
			&i.Orgs,
			&i.BytesIn,
			&i.BytesOut,
			&i.LastHour,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organisationDevices = `-- name: OrganisationDevices :many
SELECT CAST(t.peer_asn AS INTEGER)            AS peer_asn,
       d.id,
       CAST(COALESCE(d.label, '') AS TEXT)    AS label,
       CAST(COALESCE(d.hostname, '') AS TEXT) AS hostname,
       CAST(COALESCE(d.mac, '') AS TEXT)      AS mac,
       CAST(SUM(t.bytes_out) AS INTEGER)      AS bytes_out,
       CAST(SUM(t.bytes_in) AS INTEGER)       AS bytes_in
FROM traffic_hourly t
         JOIN devices d ON d.id = t.device_id
WHERE t.peer_asn IS NOT NULL
  AND t.hour >= ?1
  AND d.is_ignored = 0
  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
GROUP BY t.peer_asn, d.id
ORDER BY t.peer_asn, SUM(t.bytes_out + t.bytes_in) DESC, d.id
`

type OrganisationDevicesParams struct {
	Since     dbtype.Time    `json:"since"`
	GroupName sql.NullString `json:"group_name"`
}

type OrganisationDevicesRow struct {
	PeerASN  int64  `json:"peer_asn"`
	ID       int64  `json:"id"`
	Label    string `json:"label"`
	Hostname string `json:"hostname"`
	MAC      string `json:"mac"`
	BytesOut int64  `json:"bytes_out"`
	BytesIn  int64  `json:"bytes_in"`
}

// What each device exchanged with each organisation since a given hour, for
// the breakdown under the busiest organisations. Every pair comes back; the
// caller keeps the organisations it shows.
//
//	SELECT CAST(t.peer_asn AS INTEGER)            AS peer_asn,
//	       d.id,
//	       CAST(COALESCE(d.label, '') AS TEXT)    AS label,
//	       CAST(COALESCE(d.hostname, '') AS TEXT) AS hostname,
//	       CAST(COALESCE(d.mac, '') AS TEXT)      AS mac,
//	       CAST(SUM(t.bytes_out) AS INTEGER)      AS bytes_out,
//	       CAST(SUM(t.bytes_in) AS INTEGER)       AS bytes_in
//	FROM traffic_hourly t
//	         JOIN devices d ON d.id = t.device_id
//	WHERE t.peer_asn IS NOT NULL
//	  AND t.hour >= ?1
//	  AND d.is_ignored = 0
//	  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
//	GROUP BY t.peer_asn, d.id
//	ORDER BY t.peer_asn, SUM(t.bytes_out + t.bytes_in) DESC, d.id
func (q *Queries) OrganisationDevices(ctx context.Context, arg OrganisationDevicesParams) ([]*OrganisationDevicesRow, error) {
	rows, err := q.query(ctx, q.organisationDevicesStmt, organisationDevices, arg.Since, arg.GroupName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OrganisationDevicesRow
	for rows.Next() {
		var i OrganisationDevicesRow
		if err := rows.Scan(
			&i.PeerASN,
			&i.ID,
			&i.Label,
			&i.Hostname,
			&i.MAC,
			&i.BytesOut,
			&i.BytesIn,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topOrganisations = `-- name: TopOrganisations :many
SELECT CAST(t.peer_asn AS INTEGER)              AS peer_asn,
       CAST(MIN(t.peer_ip) AS TEXT)             AS peer_ip,
       CAST(SUM(t.bytes_out) AS INTEGER)        AS bytes_out,
       CAST(SUM(t.bytes_in) AS INTEGER)         AS bytes_in,
       CAST(COUNT(DISTINCT t.device_id) AS INTEGER) AS devices
FROM traffic_hourly t
         JOIN devices d ON d.id = t.device_id
WHERE t.peer_asn IS NOT NULL
  AND t.hour >= ?1
  AND d.is_ignored = 0
  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
GROUP BY t.peer_asn
ORDER BY SUM(t.bytes_out + t.bytes_in) DESC, t.peer_asn
LIMIT ?3
`

type TopOrganisationsParams struct {
	Since     dbtype.Time    `json:"since"`
	GroupName sql.NullString `json:"group_name"`
	LimitRows int64          `json:"limit_rows"`
}

type TopOrganisationsRow struct {
	PeerASN  int64  `json:"peer_asn"`
	PeerIP   string `json:"peer_ip"`
	BytesOut int64  `json:"bytes_out"`
	BytesIn  int64  `json:"bytes_in"`
	Devices  int64  `json:"devices"`
}

// The organisations the whole network exchanged the most with since a given
// hour, and how many devices reached each.
//
//	SELECT CAST(t.peer_asn AS INTEGER)              AS peer_asn,
//	       CAST(MIN(t.peer_ip) AS TEXT)             AS peer_ip,
//	       CAST(SUM(t.bytes_out) AS INTEGER)        AS bytes_out,
//	       CAST(SUM(t.bytes_in) AS INTEGER)         AS bytes_in,
//	       CAST(COUNT(DISTINCT t.device_id) AS INTEGER) AS devices
//	FROM traffic_hourly t
//	         JOIN devices d ON d.id = t.device_id
//	WHERE t.peer_asn IS NOT NULL
//	  AND t.hour >= ?1
//	  AND d.is_ignored = 0
//	  AND (CAST(?2 AS TEXT) IS NULL OR d.group_name = CAST(?2 AS TEXT))
//	GROUP BY t.peer_asn
//	ORDER BY SUM(t.bytes_out + t.bytes_in) DESC, t.peer_asn
//	LIMIT ?3
func (q *Queries) TopOrganisations(ctx context.Context, arg TopOrganisationsParams) ([]*TopOrganisationsRow, error) {
	rows, err := q.query(ctx, q.topOrganisationsStmt, topOrganisations, arg.Since, arg.GroupName, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TopOrganisationsRow
	for rows.Next() {
		var i TopOrganisationsRow
		if err := rows.Scan(
			&i.PeerASN,
			&i.PeerIP,
			&i.BytesOut,
			&i.BytesIn,
			&i.Devices,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trafficMapDevices = `-- name: TrafficMapDevices :many
SELECT d.id,
       CAST(COALESCE(d.label, '') AS TEXT)       AS label,
       CAST(COALESCE(d.hostname, '') AS TEXT)    AS hostname,
       CAST(COALESCE(d.mac, '') AS TEXT)         AS mac,
       CAST(COALESCE(d.device_type, '') AS TEXT) AS device_type,
       CAST(COALESCE((SELECT MIN(a.network_id)
                      FROM addresses a
                      WHERE a.device_id = d.id
                        AND a.is_current = 1), 0) AS INTEGER) AS network_id,
       CAST(SUM(t.bytes_out + t.bytes_in) AS INTEGER) AS bytes
FROM traffic_hourly t
         JOIN devices d ON d.id = t.device_id
WHERE t.hour >= ?1
  AND d.is_ignored = 0
GROUP BY d.id
ORDER BY bytes DESC, d.id
`

type TrafficMapDevicesRow struct {
	ID         int64  `json:"id"`
	Label      string `json:"label"`
	Hostname   string `json:"hostname"`
	MAC        string `json:"mac"`
	DeviceType string `json:"device_type"`
	NetworkID  int64  `json:"network_id"`
	Bytes      int64  `json:"bytes"`
}

// The devices with traffic since a given hour, for the map: who each is, the
// network one of its current addresses sits on, and how much it moved.
//
//	SELECT d.id,
//	       CAST(COALESCE(d.label, '') AS TEXT)       AS label,
//	       CAST(COALESCE(d.hostname, '') AS TEXT)    AS hostname,
//	       CAST(COALESCE(d.mac, '') AS TEXT)         AS mac,
//	       CAST(COALESCE(d.device_type, '') AS TEXT) AS device_type,
//	       CAST(COALESCE((SELECT MIN(a.network_id)
//	                      FROM addresses a
//	                      WHERE a.device_id = d.id
//	                        AND a.is_current = 1), 0) AS INTEGER) AS network_id,
//	       CAST(SUM(t.bytes_out + t.bytes_in) AS INTEGER) AS bytes
//	FROM traffic_hourly t
//	         JOIN devices d ON d.id = t.device_id
//	WHERE t.hour >= ?1
//	  AND d.is_ignored = 0
//	GROUP BY d.id
//	ORDER BY bytes DESC, d.id
func (q *Queries) TrafficMapDevices(ctx context.Context, since dbtype.Time) ([]*TrafficMapDevicesRow, error) {
	rows, err := q.query(ctx, q.trafficMapDevicesStmt, trafficMapDevices, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TrafficMapDevicesRow
	for rows.Next() {
		var i TrafficMapDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Hostname,
			&i.MAC,
			&i.DeviceType,
			&i.NetworkID,
			&i.Bytes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trafficMapLinks = `-- name: TrafficMapLinks :many
SELECT t.device_id,
       CAST(COALESCE(t.peer_device_id, 0) AS INTEGER) AS peer_device_id,
       CAST(COALESCE(t.peer_asn, 0) AS INTEGER)       AS peer_asn,
       CAST(MIN(t.peer_ip) AS TEXT)                   AS peer_ip,
       CAST(SUM(t.bytes_out + t.bytes_in) AS INTEGER) AS bytes,
       -- Each protocol and service port the pair used, as "6/443,17/123".
       CAST(GROUP_CONCAT(DISTINCT t.protocol || '/' || t.service_port) AS TEXT) AS services
FROM traffic_hourly t
         JOIN devices d ON d.id = t.device_id
         LEFT JOIN devices p ON p.id = t.peer_device_id
WHERE t.hour >= ?1
  AND d.is_ignored = 0
  AND ((t.peer_device_id IS NOT NULL AND t.peer_device_id > t.device_id AND p.is_ignored = 0)
    OR (t.peer_device_id IS NULL AND t.peer_asn IS NOT NULL))
GROUP BY t.device_id, t.peer_device_id, t.peer_asn
ORDER BY bytes DESC, t.device_id, peer_device_id, peer_asn
`

type TrafficMapLinksRow struct {
	DeviceID     int64  `json:"device_id"`
	PeerDeviceID int64  `json:"peer_device_id"`
	PeerASN      int64  `json:"peer_asn"`
	PeerIP       string `json:"peer_ip"`
	Bytes        int64  `json:"bytes"`
	Services     string `json:"services"`
}

// What each device exchanged since a given hour with each other device and
// each organisation, for the map. A conversation between two devices is
// written from both sides; only the side with the lower id is kept, so each
// pair comes back once, with the services it used. Peers that are neither a
// device nor an organisation have nowhere to go on the map and are left out.
//
//	SELECT t.device_id,
//	       CAST(COALESCE(t.peer_device_id, 0) AS INTEGER) AS peer_device_id,
//	       CAST(COALESCE(t.peer_asn, 0) AS INTEGER)       AS peer_asn,
//	       CAST(MIN(t.peer_ip) AS TEXT)                   AS peer_ip,
//	       CAST(SUM(t.bytes_out + t.bytes_in) AS INTEGER) AS bytes,
//	       -- Each protocol and service port the pair used, as "6/443,17/123".
//	       CAST(GROUP_CONCAT(DISTINCT t.protocol || '/' || t.service_port) AS TEXT) AS services
//	FROM traffic_hourly t
//	         JOIN devices d ON d.id = t.device_id
//	         LEFT JOIN devices p ON p.id = t.peer_device_id
//	WHERE t.hour >= ?1
//	  AND d.is_ignored = 0
//	  AND ((t.peer_device_id IS NOT NULL AND t.peer_device_id > t.device_id AND p.is_ignored = 0)
//	    OR (t.peer_device_id IS NULL AND t.peer_asn IS NOT NULL))
//	GROUP BY t.device_id, t.peer_device_id, t.peer_asn
//	ORDER BY bytes DESC, t.device_id, peer_device_id, peer_asn
func (q *Queries) TrafficMapLinks(ctx context.Context, since dbtype.Time) ([]*TrafficMapLinksRow, error) {
	rows, err := q.query(ctx, q.trafficMapLinksStmt, trafficMapLinks, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TrafficMapLinksRow
	for rows.Next() {
		var i TrafficMapLinksRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.PeerDeviceID,
			&i.PeerASN,
			&i.PeerIP,
			&i.Bytes,
			&i.Services,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trafficWorldPeers = `-- name: TrafficWorldPeers :many
SELECT t.device_id,
       t.peer_ip,
       CAST(COALESCE(t.peer_asn, 0) AS INTEGER)       AS peer_asn,
       CAST(SUM(t.bytes_out + t.bytes_in) AS INTEGER) AS bytes
FROM traffic_hourly t
         JOIN devices d ON d.id = t.device_id
WHERE t.hour >= ?1
  AND d.is_ignored = 0
  AND t.peer_device_id IS NULL
  AND t.peer_asn IS NOT NULL
GROUP BY t.device_id, t.peer_ip
ORDER BY bytes DESC, t.device_id, t.peer_ip
`

type TrafficWorldPeersRow struct {
	DeviceID int64       `json:"device_id"`
	PeerIP   dbtype.Addr `json:"peer_ip"`
	PeerASN  int64       `json:"peer_asn"`
	Bytes    int64       `json:"bytes"`
}

// What each device exchanged with each internet address since a given hour,
// for placing the addresses on the world map. Grouped by address, since one
// organisation's addresses sit in many countries.
//
//	SELECT t.device_id,
//	       t.peer_ip,
//	       CAST(COALESCE(t.peer_asn, 0) AS INTEGER)       AS peer_asn,
//	       CAST(SUM(t.bytes_out + t.bytes_in) AS INTEGER) AS bytes
//	FROM traffic_hourly t
//	         JOIN devices d ON d.id = t.device_id
//	WHERE t.hour >= ?1
//	  AND d.is_ignored = 0
//	  AND t.peer_device_id IS NULL
//	  AND t.peer_asn IS NOT NULL
//	GROUP BY t.device_id, t.peer_ip
//	ORDER BY bytes DESC, t.device_id, t.peer_ip
func (q *Queries) TrafficWorldPeers(ctx context.Context, since dbtype.Time) ([]*TrafficWorldPeersRow, error) {
	rows, err := q.query(ctx, q.trafficWorldPeersStmt, trafficWorldPeers, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TrafficWorldPeersRow
	for rows.Next() {
		var i TrafficWorldPeersRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.PeerIP,
			&i.PeerASN,
			&i.Bytes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTraffic = `-- name: UpsertTraffic :exec
INSERT INTO traffic_hourly (source_id, device_id, hour, peer_device_id, peer_ip, peer_name, peer_asn,
                            protocol, service_port, bytes_out, bytes_in, packets_out, packets_in, connections,
                            connections_in)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (device_id, hour, source_id, peer_ip, protocol, service_port) DO UPDATE
    SET peer_device_id = COALESCE(excluded.peer_device_id, peer_device_id),
        peer_name      = COALESCE(excluded.peer_name, peer_name),
        peer_asn       = COALESCE(excluded.peer_asn, peer_asn),
        bytes_out      = bytes_out + excluded.bytes_out,
        bytes_in       = bytes_in + excluded.bytes_in,
        packets_out    = packets_out + excluded.packets_out,
        packets_in     = packets_in + excluded.packets_in,
        connections    = connections + excluded.connections,
        connections_in = connections_in + excluded.connections_in
`

type UpsertTrafficParams struct {
	SourceID      int64          `json:"source_id"`
	DeviceID      int64          `json:"device_id"`
	Hour          dbtype.Time    `json:"hour"`
	PeerDeviceID  sql.NullInt64  `json:"peer_device_id"`
	PeerIP        dbtype.Addr    `json:"peer_ip"`
	PeerName      sql.NullString `json:"peer_name"`
	PeerASN       sql.NullInt64  `json:"peer_asn"`
	Protocol      int64          `json:"protocol"`
	ServicePort   int64          `json:"service_port"`
	BytesOut      int64          `json:"bytes_out"`
	BytesIn       int64          `json:"bytes_in"`
	PacketsOut    int64          `json:"packets_out"`
	PacketsIn     int64          `json:"packets_in"`
	Connections   int64          `json:"connections"`
	ConnectionsIn int64          `json:"connections_in"`
}

// One flush adds to the hour's running totals. The peer's identity columns
// take the newest non-empty answer: a name that failed to resolve on one
// flush should not erase one that resolved on the last.
//
//	INSERT INTO traffic_hourly (source_id, device_id, hour, peer_device_id, peer_ip, peer_name, peer_asn,
//	                            protocol, service_port, bytes_out, bytes_in, packets_out, packets_in, connections,
//	                            connections_in)
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
//	ON CONFLICT (device_id, hour, source_id, peer_ip, protocol, service_port) DO UPDATE
//	    SET peer_device_id = COALESCE(excluded.peer_device_id, peer_device_id),
//	        peer_name      = COALESCE(excluded.peer_name, peer_name),
//	        peer_asn       = COALESCE(excluded.peer_asn, peer_asn),
//	        bytes_out      = bytes_out + excluded.bytes_out,
//	        bytes_in       = bytes_in + excluded.bytes_in,
//	        packets_out    = packets_out + excluded.packets_out,
//	        packets_in     = packets_in + excluded.packets_in,
//	        connections    = connections + excluded.connections,
//	        connections_in = connections_in + excluded.connections_in
func (q *Queries) UpsertTraffic(ctx context.Context, arg UpsertTrafficParams) error {
	_, err := q.exec(ctx, q.upsertTrafficStmt, upsertTraffic,
		arg.SourceID,
		arg.DeviceID,
		arg.Hour,
		arg.PeerDeviceID,
		arg.PeerIP,
		arg.PeerName,
		arg.PeerASN,
		arg.Protocol,
		arg.ServicePort,
		arg.BytesOut,
		arg.BytesIn,
		arg.PacketsOut,
		arg.PacketsIn,
		arg.Connections,
		arg.ConnectionsIn,
	)
	return err
}
