// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package models

import (
	"context"
	"database/sql"

	"github.com/pushkar-anand/jocasta/internal/db/dbtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users
`

// CountUsers
//
//	SELECT COUNT(*)
//	FROM users
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersStmt, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFirstUser = `-- name: CreateFirstUser :one
INSERT INTO users (username, password_hash, role)
SELECT ?1, ?2, 'admin'
WHERE NOT EXISTS (SELECT 1 FROM users)
RETURNING id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
`

type CreateFirstUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

// Inserts the admin only into an empty table, checked and written in one
// statement, so setup run twice at once makes one account. No row comes back
// when an account already exists.
//
//	INSERT INTO users (username, password_hash, role)
//	SELECT ?1, ?2, 'admin'
//	WHERE NOT EXISTS (SELECT 1 FROM users)
//	RETURNING id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
func (q *Queries) CreateFirstUser(ctx context.Context, arg CreateFirstUserParams) (*User, error) {
	row := q.queryRow(ctx, q.createFirstUserStmt, createFirstUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.TOTPConfirmedAt,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, role)
VALUES (?, ?, ?)
RETURNING id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
`

type CreateUserParams struct {
	Username     string          `json:"username"`
	PasswordHash string          `json:"password_hash"`
	Role         dbtype.UserRole `json:"role"`
}

// CreateUser
//
//	INSERT INTO users (username, password_hash, role)
//	VALUES (?, ?, ?)
//	RETURNING id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.TOTPConfirmedAt,
	)
	return &i, err
}

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE users
SET totp_enabled      = 0,
    totp_secret       = NULL,
    totp_confirmed_at = NULL
WHERE id = ?
`

// DisableUserTOTP
//
//	UPDATE users
//	SET totp_enabled      = 0,
//	    totp_secret       = NULL,
//	    totp_confirmed_at = NULL
//	WHERE id = ?
func (q *Queries) DisableUserTOTP(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.disableUserTOTPStmt, disableUserTOTP, id)
	return err
}

const enableUserTOTP = `-- name: EnableUserTOTP :execrows
UPDATE users
SET totp_enabled      = 1,
    totp_confirmed_at = ?
WHERE id = ?
  AND totp_enabled = 0
`

type EnableUserTOTPParams struct {
	TOTPConfirmedAt dbtype.NullTime `json:"totp_confirmed_at"`
	ID              int64           `json:"id"`
}

// totp_enabled = 0 makes a second confirmation, from another tab, change no
// row, so only one of them mints recovery codes.
//
//	UPDATE users
//	SET totp_enabled      = 1,
//	    totp_confirmed_at = ?
//	WHERE id = ?
//	  AND totp_enabled = 0
func (q *Queries) EnableUserTOTP(ctx context.Context, arg EnableUserTOTPParams) (int64, error) {
	result, err := q.exec(ctx, q.enableUserTOTPStmt, enableUserTOTP, arg.TOTPConfirmedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
FROM users
WHERE id = ?
`

// GetUserByID
//
//	SELECT id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
//	FROM users
//	WHERE id = ?
func (q *Queries) GetUserByID(ctx context.Context, id int64) (*User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.TOTPConfirmedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
FROM users
WHERE username = ?
`

// GetUserByUsername
//
//	SELECT id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
//	FROM users
//	WHERE username = ?
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.TOTPSecret,
		&i.TOTPEnabled,
		&i.TOTPConfirmedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
FROM users
ORDER BY created_at, id
`

// ListUsers
//
//	SELECT id, username, password_hash, role, created_at, totp_secret, totp_enabled, totp_confirmed_at
//	FROM users
//	ORDER BY created_at, id
func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.TOTPSecret,
			&i.TOTPEnabled,
			&i.TOTPConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :execrows
UPDATE users
SET totp_secret = ?
WHERE id = ?
  AND totp_enabled = 0
`

type SetUserTOTPSecretParams struct {
	TOTPSecret sql.NullString `json:"totp_secret"`
	ID         int64          `json:"id"`
}

// totp_enabled = 0 keeps the secret of an account with 2FA on out of reach of
// a session, which has not shown the password. No row changes then.
//
//	UPDATE users
//	SET totp_secret = ?
//	WHERE id = ?
//	  AND totp_enabled = 0
func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) (int64, error) {
	result, err := q.exec(ctx, q.setUserTOTPSecretStmt, setUserTOTPSecret, arg.TOTPSecret, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
