name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    uses: pushkar-anand/.github/.github/workflows/go-ci.yml@main
    with:
      run-lint: true
      generate-command: "make gen"
